<div class="col-xs-12 col-sm-4">
    <div class="block discount" id="block-discount" data-mage-init='{"collapsible":{"openedState": "active", "saveState": false}}'>
        <div class="title" data-role="title">
            <strong id="block-discount-heading" role="heading" aria-level="2">DISCOUNT CODES</strong>
        </div>
        <div class="content" >
            <form id="discount-coupon-form"
                  action="<?= $block->getUrl('checkout/cart/couponPost') ?>"
                  method="post"
                  data-mage-init='{"discountCode":{"couponCodeSelector": "#coupon_code",
                                               "removeCouponSelector": "#remove-coupon",
                                               "applyButton": "button.action.apply",
                                               "cancelButton": "button.action.cancel"}}'>
                <div class="fieldset coupon<?= strlen($block->getCouponCode()) ? ' applied' : '' ?>">
                    <input type="hidden" name="remove" id="remove-coupon" value="0"/>
                    <div class="field">
                        <label for="coupon_code" class="label"><span><?= __('Enter discount code') ?></span></label>
                        <div class="control">
                            <input type="text" class="input-text" id="coupon_code" name="coupon_code"
                                   value="<?= $block->escapeHtml($block->getCouponCode()) ?>"
                                   placeholder="<?= $block->escapeHtml(__('Enter discount code')); ?>"/>
                        </div>
                    </div>
                    <div class="actions-toolbar">
                        <?php if (!strlen($block->getCouponCode())): ?>
                            <div class="primary">
                                <button class="action apply primary" type="button" value="<?= __('Apply Discount') ?>">
                                    <span><?= __('Apply Discount') ?></span>
                                </button>
                            </div>
                        <?php else: ?>
                            <div class="primary">
                                <button type="button" class="action cancel primary" value="<?= __('Cancel Coupon') ?>">
                                    <span><?= __('Cancel Coupon') ?></span></button>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div class="clearfix pad40"></div>
</div>