<?php
/**  @var $block \Magento\Checkout\Block\Cart */
?>

<?php $mergedCells = ($this->helper('Magento\Tax\Helper\Data')->displayCartBothPrices() ? 2 : 1);
$size = count($block->getItems()); ?>
<?= $block->getChildHtml('form_before') ?>

<div class="col-xs-12 col-sm-12">
    <p class="headingCartPage">Check out our latest deals and start saving</p>

    <div class="topSectionCP">
        <b>Shopping Cart (<?= $size ?>)</b>
        <a href="/">Continue Shopping <span></span></a>
    </div>
    <div class="clearfix"></div>
    <p style="font-size: 12px;">If you have any queries, our Customer Service team will be happy to help - just call 1-888-900-6539</p>
    <div class="clearfix pad30"></div>

    <form action="<?= $block->getUrl('checkout/cart/updatePost') ?>" method="post" data-mage-init='{"validation":{}}'
          id="form-validate"  class="form form-cart ">
        <?= $block->getBlockHtml('formkey'); ?>
        <div class="cart table-responsive22">
            <table id="shopping-cart-table" class="table-bordered table cart items data"
                   data-mage-init='{"shoppingCart":{"emptyCartButton": "action.clear",
               "updateCartActionContainer": "#update_cart_action_container"}}'>
                <thead>
                    <tr>
                        <th class="colTb item"><span><?= __('Products') ?></span></th>
                        <th class="colTb price align-center"><span><?= __('Price') ?></span></th>
                        <th class="colTb qty align-center"><span><?= __('Qty') ?></span></th>
                        <th class="colTb subtotal align-center"><span><?= __('Total') ?></span></th>
                    </tr>
                </thead>
                <?php foreach ($block->getItems() as $_item): ?>
                    <?= $block->getItemHtml($_item) ?>
                <?php endforeach ?>
            </table>
        </div>
        <div class="cart main actions">
            <button type="submit"
                    name="update_cart_action"
                    data-cart-empty=""
                    value="empty_cart"
                    title="<?= $block->escapeHtml(__('Clear Shopping Cart')); ?>"
                    class="action clear" id="empty_cart_button">
                <span><?= __('Clear Shopping Cart'); ?></span>
            </button>
            <button type="submit"
                    name="update_cart_action"
                    data-cart-item-update=""
                    value="update_qty"
                    title="<?= $block->escapeHtml(__('Update Shopping Cart')); ?>"
                    class="action update">
                <span><?= __('Update Shopping Cart'); ?></span>
            </button>
            <input type="hidden" value="" id="update_cart_action_container" data-cart-item-update=""/>
        </div>
    </form>
    <?= $block->getChildHtml('checkout.cart.order.actions') ?>
    <?= $block->getChildHtml('shopping.cart.table.after'); ?>

    <div class="clearfix pad50"></div>

    <script type="text/javascript">
        require(['jquery', 'jquery/ui'], function($){
            $(document).ready(function($) {
                $('.showDetailCartCol').click(function(){
                    var itemDetail = $(this).parent().find('.item-options');
                    itemDetail.toggle();
                });
            });
        });
    </script>

</div>

<div class="clearfix"></div>