<?php
/** @var $block \Magento\Checkout\Block\Cart */
?>

<?php if (!$block->hasError()) { ?>
    <?php $methods = $block->getMethods('methods') ?: $block->getMethods('top_methods') ?>
    <div class="clearfix pad20"></div>
    <ul class="checkout methods items checkout-methods-items">
    <?php foreach ($methods as $method) { ?>
        <?php if ($methodHtml = $block->getMethodHtml($method)) { ?>
        <li class="item"><?= $methodHtml; ?></li>
        <?php } ?>
    <?php } ?>
    </ul>
<?php } ?>
