<?php /** @var $block \Magento\Checkout\Block\Cart\Shipping */ ?>

<div class="col-xs-12 col-sm-4 hidden" >
    <div id="block-shipping" class="block shipping hidden" data-mage-init='{"collapsible":{"openedState": "active", "saveState": true}}'>
        <div class="title" data-role="title">
            <strong id="block-shipping-heading" role="heading" aria-level="2">
                <?= $block->getQuote()->isVirtual() ? __('ESTIMATE TAX') : 'ESTIMATE SHIPPING AND TAX' ?>
            </strong>
        </div>
        <div id="block-summary" data-bind="scope:'block-summary'" class="content">
            <!-- ko template: getTemplate() --><!-- /ko -->
            <script type="text/x-magento-init">
            {
                "#block-summary": {
                    "Magento_Ui/js/core/app": <?= $block->getJsLayout(); ?>
                }
            }

            </script>
            <script>
                window.checkoutConfig = <?= \Zend_Json::encode($block->getCheckoutConfig()); ?>;
                window.customerData = window.checkoutConfig.customerData;
                window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
                require([
                    'mage/url',
                    'Magento_Ui/js/block-loader'
                ], function (url, blockLoader) {
                    blockLoader("<?= $block->getViewFileUrl('images/loader-1.gif'); ?>");
                    return url.setBaseUrl('<?= $block->getBaseUrl();?>');
                })
            </script>
        </div>
    </div>
    <div class="clearfix pad20"></div>
</div>
