<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_option = $block->getOption(); ?>
<?php $_fileInfo = $block->getFileInfo(); ?>
<?php $_fileExists = $_fileInfo->hasData(); ?>
<?php $_fileName = 'options_' . $_option->getId() . '_file'; ?>
<?php $_fieldNameAction = $_fileName . '_action'; ?>
<?php $_fieldValueAction = $_fileExists ? 'save_old' : 'save_new'; ?>
<?php $_fileNamed = $_fileName . '_name'; ?>
<?php $class = ($_option->getIsRequire()) ? ' required' : ''; ?>

<div class="col-xs-12  col-sm-6 field file<?= $class; ?>">
    <label class="label" for="<?= $_fileName; ?>" id="<?= $_fileName; ?>-label">
        <span><?=  $block->escapeHtml($_option->getTitle()) ?></span>
        <?= $block->getFormatedPrice() ?>
    </label>
    <?php if ($_fileExists): ?>
    <div class="control">
        <span class="<?= $_fileNamed ?>"><?= $block->escapeHtml($_fileInfo->getTitle()); ?></span>
        <a href="javascript:void(0)" class="label" id="change-<?= $_fileName ?>" >
            <?= __('Change') ?>
        </a>
        <?php if (!$_option->getIsRequire()): ?>
            <input type="checkbox" id="delete-<?= $_fileName ?>" />
            <span class="label"><?= __('Delete') ?></span>
        <?php endif; ?>
    </div>
    <?php endif; ?>
    <div class="control" id="input-box-<?= $_fileName ?>"
             data-mage-init='{"priceOptionFile":{
                "fileName":"<?= $_fileName ?>",
                "fileNamed":"<?= $_fileNamed ?>",
                "fieldNameAction":"<?= $_fieldNameAction ?>",
                "changeFileSelector":"#change-<?= $_fileName ?>",
                "deleteFileSelector":"#delete-<?= $_fileName ?>"}
             }'
            <?= $_fileExists ? 'style="display:none"' : '' ?>>
        <input type="file"
               name="<?= $_fileName; ?>"
               id="<?= $_fileName; ?>"
               class="product-custom-option<?= $_option->getIsRequire() ? ' required' : '' ?>"
               <?= $_fileExists ? 'disabled="disabled"' : '' ?> />
        <input type="hidden" name="<?= $_fieldNameAction; ?>" value="<?= $_fieldValueAction; ?>" />
        <?php if ($_option->getFileExtension()): ?>
            <p class="note">
                <?= __('Compatible file extensions to upload')?>: <strong><?= $_option->getFileExtension() ?></strong>
            </p>
        <?php endif; ?>
        <?php if ($_option->getImageSizeX() > 0): ?>
            <p class="note">
                <?= __('Maximum image width')?>: <strong><?= $_option->getImageSizeX() ?> <?= __('px.')?></strong>
            </p>
        <?php endif; ?>
        <?php if ($_option->getImageSizeY() > 0): ?>
            <p class="note">
                <?= __('Maximum image height')?>: <strong><?= $_option->getImageSizeY() ?> <?= __('px.')?></strong>
            </p>
        <?php endif; ?>
    </div>
</div>
