<?php /* @var $block \Magento\Catalog\Block\Product\View\Options\Type\Select */ ?>

<?php
$_option = $block->getOption();
$class = ($_option->getIsRequire()) ? ' required' : '';
?>
<div class="<?= $_option->getTitle(); ?>_<?= $_option->getId(); ?> col-xs-12 dropdownField <?= ($_option->getType() == 'radio') ? 'col-sm-12' : 'col-sm-6' ?> field<?= $class; ?>">
    <label class="label" for="select_<?= $_option->getId() ?>">
        <span><?=  $block->escapeHtml($_option->getTitle()) ?></span>
    </label>
    <div class="control changeSelectOp">
        <?= $block->getValuesHtml() ?>
        <?php if ($_option->getIsRequire()): ?>
            <?php if ($_option->getType() == \Magento\Catalog\Model\Product\Option::OPTION_TYPE_RADIO || $_option->getType() == \Magento\Catalog\Model\Product\Option::OPTION_TYPE_CHECKBOX): ?>
                <span id="options-<?= $_option->getId() ?>-container"></span>
            <?php endif; ?>
        <?php endif;?>
    </div>
</div>
