<?php
$_option = $block->getOption();
$class = ($_option->getIsRequire()) ? ' required' : '';
$label = $block->escapeHtml($_option->getTitle());
?>

<div
    class="<?= $_option->getTitle(); ?>_<?= $_option->getId(); ?> col-xs-12 <?= ($_option->getType() == 'area') ? ' textarea col-sm-12 ' : ' col-sm-6 ' ?>
     field <?= $class ?>">
    <label class="label" for="options_<?= $_option->getId() ?>_text">
        <span><?= $label ?></span>
        <?= $block->getFormatedPrice() ?>
    </label>

    <div class="control">
        <?php if ($_option->getType() == \Magento\Catalog\Model\Product\Option::OPTION_TYPE_FIELD): ?>
            <?php $_textValidate = null;
            if ($_option->getIsRequire()) {
                $_textValidate['required'] = true;
            }
            if ($_option->getMaxCharacters()) {
                $_textValidate['maxlength'] = $_option->getMaxCharacters();
            }
            ?>
            <input type="text"
                   id="options_<?= $_option->getId() ?>_text"
                   class="input-text product-custom-option"
                <?php if (!empty($_textValidate)) { ?>
                    data-validate="<?= $block->escapeHtml(json_encode($_textValidate)); ?>"
                <?php } ?>
                   name="options[<?= $_option->getId() ?>]"
                   value="<?= $block->escapeHtml($block->getDefaultValue()) ?>"/>
        <?php elseif ($_option->getType() == \Magento\Catalog\Model\Product\Option::OPTION_TYPE_AREA): ?>
            <?php $_textAreaValidate = null;
            if ($_option->getIsRequire()) {
                $_textAreaValidate['required'] = true;
            }
            if ($_option->getMaxCharacters()) {
                $_textAreaValidate['maxlength'] = $_option->getMaxCharacters();
            }
            ?>
            <textarea id="options_<?= $_option->getId() ?>_text"
                      class="product-custom-option"
                <?php if (!empty($_textAreaValidate)) { ?>
                    data-validate="<?= $block->escapeHtml(json_encode($_textAreaValidate)); ?>"
                <?php } ?>
                      name="options[<?= $_option->getId() ?>]"
                      rows="2"
                      cols="25"><?= $block->escapeHtml($block->getDefaultValue()) ?></textarea>
        <?php endif; ?>
        <?php if ($_option->getMaxCharacters()): ?>
            <p class="note"><?= __('Maximum number of characters:') ?>
                <strong><?= $_option->getMaxCharacters() ?></strong></p>
        <?php endif; ?>
    </div>

    <?php
    if (strpos($label, 'Width') !== false || strpos($label, 'Height') !== false) {
        echo '<p style="color:#1ca1ac; padding: 5px 0 0;font-size: 12px;" id="min_max_' . $_option->getId() . '"></p>';
    } ?>
</div>
