<?php $pts_range = $this->getProductPointsRange();?>
<?php $pts = (!count($pts_range)) ? $this->getProductPoints() : 0;?>
<?php //$pts = (count($pts_range) == 1 && !$pts) ? $pts_range[0] : 0;?>
<?php $style_block = (!count($pts_range) && !$pts) ? 'display:none;' : '';?>

<div style="<?php echo $style_block;?>" class="rewardpoints-product-point-text j2t-loyalty-points point-information-<?php echo $this->getProduct()->getId();?>" data-role="pointBox">
    <?php if($this->showImage() && ($size = $this->sizeImage()) && ($url = $this->getImageUrl())):?>
		<img class="reward-icon-image" src="<?php echo $url;?>" alt="<?php echo __("Reward Points");?>" width="<?php echo $size;?>" />
    <?php endif;?>
<?php if (count($pts_range) == 2):?>
	<?php echo __("With this product, you earn from <span class='j2t-pts-from'>%1</span> to <span class='j2t-pts-to'>%2</span> reward points.", $this->mathActionOnCatalogPages($pts_range[0]), $this->mathActionOnCatalogPages($pts_range[1])); ?>
<?php elseif (count($pts_range) == 1):?>
	<?php if ($this->isUpTo()):?>
		<?php echo __("With this product, you earn up to <span class='j2t-pts'>%1</span> reward points.", $this->mathActionOnCatalogPages($pts_range[0])); ?>
	<?php else:?>
		<?php echo __("With this product, you earn <span class='j2t-pts'>%1</span> reward points.", $this->mathActionOnCatalogPages($pts_range[0])); ?>
	<?php endif;?>
<?php else:?>
<?php if ($pts > 1):?>
<?php echo __("With this product, you earn <span class='j2t-pts'>%1</span> reward points.", $this->mathActionOnCatalogPages($pts)); ?>
<?php elseif($pts == 1):?>
<?php echo __("With this product, you earn <span class='j2t-pts'>%1</span> reward point.", $this->mathActionOnCatalogPages($pts)); ?>
<?php else:?>
<?php echo __("With this product, you earn <span class='j2t-pts'>%1</span> reward point(s).", $this->mathActionOnCatalogPages($pts)); ?>
<?php endif;?>
<?php endif;?>
<?php if ($this->showEquivalence() && count($pts_range) == 2 && ($eq1 = $this->getPointsEquivalence($this->mathActionOnCatalogPages($pts_range[0]))) && ($eq2 = $this->getPointsEquivalence($this->mathActionOnCatalogPages($pts_range[1])))):?>
	<span class="j2t-point-equivalence"><?php echo __("%1 points = %2 and %3 points = %4.", $this->mathActionOnCatalogPages($pts_range[0]), $eq1, $this->mathActionOnCatalogPages($pts_range[1]), $eq2)?></span>
<?php elseif($this->showEquivalence() && ($eq = $this->getPointsEquivalence($this->mathActionOnCatalogPages($pts)))):?>
    <span class="j2t-point-equivalence"><?php echo __("%1 points = %2.", $this->mathActionOnCatalogPages($pts), $eq)?></span>
<?php elseif($this->showEquivalence()):?>
	<span class="j2t-point-equivalence" style="display:none;"><?php echo __("%1 points = %2.", 0, 0)?></span>
<?php endif;?>
</div>
<?php // only for grouped and simple products on view page?>
<?php if($this->isAllowedCalculationQty() && count($pts_range) < 2):?>
<script>
	require([
		'jquery',
		'mage/mage',
	], function($){
		$(function() {
			var element_ctrl = "#qty";
			if ($("input[name='super_group\[<?php echo $this->getProduct()->getId();?>\]']").length > 0){
				element_ctrl = "input[name='super_group\[<?php echo $this->getProduct()->getId();?>\]']";
			}
			$(element_ctrl).on("change paste keyup", function() {
				var qty = ($(this).val() >= 0) ? $(this).val() : 1;
				var calc_equivalence = <?php echo $this->getDefaultPointMoneyEquivalence();?>;
				var points = <?php echo $pts ?>;
				var sentence = '<?php echo __("%1 points = %2.", '[[points]]', '[[money]]')?>';
				var point_div = '.point-information-<?php echo $this->getProduct()->getId();?> .j2t-pts';
				var equivalence_div = '.point-information-<?php echo $this->getProduct()->getId();?> .j2t-point-equivalence';
				var total_points = qty * points;
				total_points = <?php echo $this->getJSMathMethod();?>;
				$(point_div).html(total_points);
				var price = total_points * calc_equivalence;
				
				//currency BEGIN
				
				var format = <?php echo $this->priceFormat();?>;
				
				var precision = isNaN(format.requiredPrecision = Math.abs(format.requiredPrecision)) ? 2 : format.requiredPrecision,
					integerRequired = isNaN(format.integerRequired = Math.abs(format.integerRequired)) ? 1 : format.integerRequired,
					decimalSymbol = format.decimalSymbol === undefined ? "," : format.decimalSymbol,
					groupSymbol = format.groupSymbol === undefined ? "." : format.groupSymbol,
					groupLength = format.groupLength === undefined ? 3 : format.groupLength,
					s = '';

				var i = parseInt(price = Math.abs(+price || 0).toFixed(precision), 10) + '',
					pad = (i.length < integerRequired) ? (integerRequired - i.length) : 0;
				while (pad) {
					i = '0' + i;
					pad--;
				}
				var j = i.length > groupLength ? i.length % groupLength : 0,
					re = new RegExp("(\\d{" + groupLength + "})(?=\\d)", "g");

				/**
				 * replace(/-/, 0) is only for fixing Safari bug which appears
				 * when Math.abs(0).toFixed() executed on "0" number.
				 * Result is "0.-0" :(
				 */
				var r = (j ? i.substr(0, j) + groupSymbol : "") + i.substr(j).replace(re, "$1" + groupSymbol) +
						(precision ? decimalSymbol + Math.abs(price - i).toFixed(precision).replace(/-/, 0).slice(2) : ""),
					pattern = format.pattern.indexOf('{sign}') < 0 ? s + format.pattern : format.pattern.replace('{sign}', s);
				var money_value = pattern.replace('%s', r).replace(/^\s\s*/, '').replace(/\s\s*$/, '');
				
				var equivalence_replace = sentence.replace('[[points]]', total_points);
				equivalence_replace = equivalence_replace.replace('[[money]]', money_value);
				$(equivalence_div).html(equivalence_replace);
				//currency END
			});
		});
	});
</script>
<?php endif;?>