<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<form class="form quickrfq"
      action="<?= $block->getFormAction(); ?>"
      id="quickrfq_form"
      enctype="multipart/form-data"
      method="post"
      data-hasrequired="* Required Fields"
      data-mage-init='{"validation":{}}'>


    <fieldset class="fieldset">
        <div class="custom-title">
            <legend class="legend"><span>Custom Estimate</span></legend><br />
        </div>
        <div class="estimate-group row">
            <div class="col-xs-12 col-sm-6">
                <div class="field name required">
                    <label class="label" for="contact_name">Custom Quote Name</label>
                    <div class="control">
                        <input name="contact_name" id="contact_name" title="Contact Name" value="<?= $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
                    </div>
                </div>

                <div class="field email required">
                    <label class="label" for="email"><span>Email - Your User Name</span></label>
                    <div class="control">
                        <input name="email" id="email" title="Email" value="<?= $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6">
                <div class="field contact_name required">
                    <label class="label" for="company"><span>Company Name</span></label>
                    <div class="control">
                        <input name="company" id="company" value="" class="input-text" type="text" data-validate="{required:true}"/>
                    </div>
                </div>
            </div>
        </div>
        <div class="estimate-group row">
            <div class="col-xs-12 col-sm-6">
                <div class="field category">
                    <label class="label" for="category"><span>Category</span></label>
                    <div class="control">
                        <select name="category" id="category">
                            <option value="1">Banners</option>
                            <option value="2">Adhesive</option>
                            <option value="3">Digital Print</option>
                            <option value="4">Signs and Boards</option>
                            <option value="5">Banner Stands</option>
                            <option value="6">Car Wraps</option>
                            <option value="7">Lettering (Die Cut Vinyl - Plotter)</option>
                            <option value="8">Others</option>
                        </select>
                    </div>
                </div>

                <div class="field standtype standtype_options">
                    <label class="label" for="standtype"><span>Stand Type</span></label>
                    <div class="control">
                        <select name="standtype" id="standtype_options">
                            <option value="101">X-Frame</option>
                            <option value="102">Retractable Stand  (Roll-up, Pop-up)</option>
                            <option value="103">Outdoor Double Banner Stand</option>
                            <option value="104">Step and Repeat Banners</option>
                        </select>
                    </div>
                </div>

                <div class="field material material_01">
                    <label class="label" for="material"><span>Material</span></label>
                    <div class="control">
                        <select name="material" id="material_01">
                            <option value="11">13oz Scrim Vinyl   - Matte</option>
                            <option value="12">13oz Scrim Vinyl   - Gloss</option>
                            <option value="13">14oz Scrim Vinyl   - Matte</option>
                            <option value="14">14oz Scrim Vinyl   - Gloss</option>
                            <option value="15">16oz Blockout Banner</option>
                            <option value="16">Backlit Banner</option>
                            <option value="17">Fabric Banner - Premium</option>
                            <option value="18">Fabric Banner - Deluxe</option>
                            <option value="19">Mesh Banner</option>
                            <option value="20">Premium Coated Banner</option>
                            <option value="21">SuperSmooth Banner</option>
                        </select>
                    </div>
                </div>
                <div class="field material material_02">
                    <label class="label" for="material"><span>Material</span></label>
                    <div class="control">
                        <select name="material" id="material_02">
                            <option value="22">Window Vinyl Decal - White Gloss</option>
                            <option value="23">Window Vinyl Decal - White Matte</option>
                            <option value="24">Window Vinyl Decal - Clear</option>
                            <option value="25">Window Static Cling - White</option>
                            <option value="26">Windo Static Cling - Clear</option>
                            <option value="27">Perforated Stickers</option>
                            <option value="28">Wall Vinyl Decal</option>
                            <option value="29">Floor Graphics</option>
                            <option value="30">3M Controltac</option>
                        </select>
                    </div>
                </div>
                <div class="field material material_03">
                    <label class="label" for="material"><span>Material</span></label>
                    <div class="control">
                        <select name="material" id="material_03">
                            <option value="31">Backlit Film</option>
                            <option value="32">Canvas</option>
                            <option value="33">Car Magnets</option>
                            <option value="34">Digital Poster Gloss</option>
                            <option value="35">Digital Poster Matte</option>
                            <option value="36">Polyropylene (PET)</option>
                        </select>
                    </div>
                </div>
                <div class="field material material_04">
                    <label class="label" for="material"><span>Material</span></label>
                    <div class="control">
                        <select name="material" id="material_04">
                            <option value="40">Acrylic Boards</option>
                            <option value="41">Aluminum Sandwhich Board (Dibond)</option>
                            <option value="42">Aluminum Sheets</option>
                            <option value="43">Converd Coated Board</option>
                            <option value="44">Eagle Board</option>
                            <option value="45">Foam Board</option>
                            <option value="46">PVC</option>
                            <option value="47">Styrene Board</option>
                            <option value="48">Ultra/ Gator Board</option>
                            <option value="49">Coroplast (Yard Sign)</option>
                        </select>
                    </div>
                </div>
                <div class="field material material_05">
                    <label class="label" for="material"><span>Material</span></label>
                    <div class="control">
                        <select name="material" id="material_05">
                            <option value="13oz Scrim Vinyl   - Matte">13oz Scrim Vinyl   - Matte</option>
                            <option value="13oz Scrim Vinyl   - Gloss">13oz Scrim Vinyl   - Gloss</option>
                            <option value="14oz Scrim Vinyl   - Matte">14oz Scrim Vinyl   - Matte</option>
                            <option value="14oz Scrim Vinyl   - Gloss">14oz Scrim Vinyl   - Gloss</option>
                            <option value="SuperSmooth Banner">SuperSmooth Banner</option>
                            <option value="Polyropylene (PET)">Polyropylene (PET)</option>
                        </select>
                    </div>
                </div>
                <div class="field material material_06">
                    <label class="label" for="material"><span>Material</span></label>
                    <div class="control">
                        <select name="material" id="material_06">
                            <option value="SuperSmooth Banner">SuperSmooth Banner</option>
                            <option value="Premium Fabric">Premium Fabric</option>
                            <option value="Polypropylene (PET)">Polypropylene (PET)</option>
                        </select>
                    </div>
                </div>

                <div class="field size size_options">
                    <label class="label" for="size"><span>Size</span></label>
                    <div class="control">
                        <select name="size" id="size_options">
                            <option value="24inch x 63inch">24" x 63"</option>
                            <option value="30inch x 72inch">30" x 72"</option>
                            <option value="40inch x 78inch">40" x 78"</option>
                            <option value="0">Adjustable</option>
                        </select>
                    </div>
                </div>
                <div class="field size size_options_02">
                    <label class="label" for="size"><span>Size</span></label>
                    <div class="control">
                        <select name="size" id="size_options_02">
                            <option value="23inch x 80inch">23" x 80"</option>
                            <option value="33inch x 80inch">33" x 80"</option>
                            <option value="35inch x 80inch">35" x 80"</option>
                            <option value="47inch x 80inch">47" x 80"</option>
                        </select>
                    </div>
                </div>


                <div class="field budget finishing_options">
                    <label for="budget">Finishing Options</label>
                    <div class="input-box custom-multi-option">
                       <input name="budget" value="Hemming" type="checkbox">Hemming
                       <input name="budget" value="Grommets" type="checkbox">Grommets
                       <input name="budget" value="Pole Pockets" type="checkbox">Pole Pockets
                       <input name="budget" value="Wind Holes" type="checkbox">Wind Holes
                    </div>
                </div>

                <div class="field budget lamination_options">
                    <label for="budget">Lamination</label>
                    <div class="input-box custom-multi-option">
                        <input name="budget" value="High Gloss Lamination" type="checkbox">High Gloss Lamination
                        <input name="budget" value="Matte Lamination" type="checkbox">Matte Lamination
                        <input name="budget" value="Dry-Erase Lamination" type="checkbox">Dry-Erase Lamination
                    </div>
                </div>

                <div class="field lamination lamination_options_02">
                    <label class="label" for="lamination"><span>Lamination</span></label>
                    <div class="control">
                        <select name="lamination" id="lamination_options_02">
                            <option value="High Gloss Lamination">High Gloss Lamination</option>
                            <option value="Matte Lamination">Matte Lamination</option>
                            <option value="Dry-Erase Lamination">Dry-Erase Lamination</option>
                            <option value="NO Lamination">NO Lamination</option>
                        </select>
                    </div>
                </div>

                <div class="field grommet grommet_options">
                    <label class="label" for="grommet"><span>Grommets</span></label>
                    <div class="control">
                        <select name="grommet" id="grommet_options">
                            <option value="No Grommets">No Grommets</option>
                            <option value="Top Grommets">Top Grommets</option>
                            <option value="Bottom Grommets">Bottom Grommets</option>
                            <option value="All Corners Grommets">All Corners Grommets</option>
                        </select>
                    </div>
                </div>

                <div class="field round round_corners_options">
                    <label class="label" for="roundcorners"><span>Round Corners</span></label>
                    <div class="control">
                        <select name="roundcorners" id="round_corners_options">
                            <option value="1/2inch Rounded Corners ( 4 Corner)">1/2" Rounded Corners ( 4 Corner)</option>
                            <option value="No Rounded Corners">No Rounded Corners</option>
                        </select>
                    </div>
                </div>

                <div class="field color color_options">
                    <label class="label" for="color"><span>Color</span></label>
                    <div class="control">
                        <select name="color" id="color_options">
                            <option value="4:0  (Full Color One Side)">4:0  (Full Color One Side)</option>
                            <option value="4:4 (Full color Both Sides)">4:4 (Full color Both Sides)</option>
                        </select>
                    </div>
                </div>

                <div class="field frame frame_options">
                    <label class="label" for="frame"><span>Frame</span></label>
                    <div class="control">
                        <select name="frame" id="frame_options">
                            <option value="Framed">Framed</option>
                            <option value="Not Framed">Not Framed</option>
                        </select>
                    </div>
                </div>

                <div class="field diecut diecut_options">
                    <label class="label" for="diecut"><span>Die Cut</span></label>
                    <div class="control">
                        <select name="diecut" id="diecut_options">
                            <option value="No">No</option>
                            <option value="Yes">Yes</option>
                        </select>
                    </div>
                </div>

                <div class="field hstake hstake_options">
                    <label class="label" for="hstake"><span>H-Stakes</span></label>
                    <div class="control">
                        <select name="hstake" id="hstake_options">
                            <option value="No H-Stakes">No H-Stakes</option>
                            <option value="Standard H-Stake">Standard H-Stake</option>
                            <option value="Heavy Duty H-Stake">Heavy Duty H-Stake</option>
                        </select>
                    </div>
                </div>

                <div class="field thickness thickness_options">
                    <label class="label" for="thickness"><span>Thickness</span></label>
                    <div class="control">
                        <select name="thickness" id="thickness_options">
                            <option value="3/16inch">3/16"</option>
                            <option value="1/4inch">1/4"</option>
                            <option value="1/2inch">1/2"</option>
                        </select>
                    </div>
                </div>

                <div class="field thickness thickness_options_02">
                    <label class="label" for="thickness"><span>Thickness</span></label>
                    <div class="control">
                        <select name="thickness" id="thickness_options_02">
                            <option value="1 mil (1/32inch)">1 mil (1/32")</option>
                            <option value="3 mil (1/8inch)">3 mil (1/8")</option>
                            <option value="6 mil (1/4inch)">6 mil (1/4")</option>
                        </select>
                    </div>
                </div>

                <div class="field thickness thickness_options_03">
                    <label class="label" for="thickness"><span>Thickness</span></label>
                    <div class="control">
                        <select name="thickness" id="thickness_options_03">
                            <option value="3/16inch">3/16"</option>
                            <option value="1/2inch">1/2"</option>
                        </select>
                    </div>
                </div>

                <div class="field thickness thickness_options_04">
                    <label class="label" for="thickness"><span>Thickness</span></label>
                    <div class="control">
                        <select name="thickness" id="thickness_options_04">
                            <option value="4mm">4mm</option>
                            <option value="6mm">6mm</option>
                        </select>
                    </div>
                </div>

                <div class="field carmodel">
                    <label class="label" for="carmodel"><span>Car Model, Make and Year</span></label>
                    <div class="control">
                        <input name="carmodel" id="carmodel" title="carmodel" value="" class="input-text" type="text""/>
                    </div>
                </div>

                <div class="field carwrapping">
                    <label class="label" for="carwrapping"><span>Car Wrapping Design</span></label>
                    <div class="control">
                        <select name="carwrapping" id="carwrapping">
                            <option value="No - We have a car wrapping designer">No - We have a car wrapping designer</option>
                            <option value="Yes - please accommodate our design">Yes - please accommodate our design</option>
                        </select>
                    </div>
                </div>


            </div>

            <div class="col-xs-12 col-sm-6">

                <div class="size-options row">
                    <div class="col-xs-12 col-sm-4">
                        <div class="field width">
                            <label class="label" for="width"><span>Width</span></label>
                            <div class="control">
                                <input name="width" id="width" title="Width" value="" class="input-text" type="text""/>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-4">
                        <div class="field height">
                            <label class="label" for="height"><span>Height</span></label>
                            <div class="control">
                                <input name="height" id="height" title="Height" value="" class="input-text" type="text"/>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-4">
                        <div class="field quantity">
                            <label class="label" for="quantity"><span>Quantity</span></label>
                            <div class="control">
                                <input name="quantity" id="quantity" title="Quantity" value="" class="input-text" type="number" min="1" data-validate="{required:true}"/>
                            </div>
                        </div>
                    </div>
                </div>
<!--                <div class="finish-options row">-->
<!--                    <div class="col-xs-12 col-sm-6">-->
<!--                        <div class="field windholes">-->
<!--                            <label class="label" for="windholes">Wind Holes</span></label>-->
<!--                            <div class="control">-->
<!--                                <select name="windholes" id="windholes">-->
<!--                                    <option  value="N/A">Choose a selection...</option>-->
<!--                                    <option  value="Standard Wind Holes  +$5.00">Standard Wind Holes  +$5.00</option>-->
<!--                                    <option  value="No Wind Holes">No Wind Holes</option>-->
<!--                                </select>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                        <div class="field hemming">-->
<!--                            <label class="label" for="hemming">Hemming</span></label>-->
<!--                            <div class="control">-->
<!--                                <select name="hemming" id="hemming">-->
<!--                                    <option  value="N/A">Choose a selection...</option>-->
<!--                                    <option  value="Hemming">Hemming</option>-->
<!--                                    <option  value="No Hemming">No Hemming</option>-->
<!--                                </select>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                    <div class="col-xs-12 col-sm-6">-->
<!--                        <div class="field grommets">-->
<!--                            <label class="label" for="grommets">Grommets</span></label>-->
<!--                            <div class="control">-->
<!--                                <select name="grommets" id="grommets">-->
<!--                                    <option  value="N/A">Choose a selection...</option>-->
<!--                                    <option  value="Grommets Every 3 feet">Grommets Every 3 feet</option>-->
<!--                                    <option  value="4 Corners Only">4 Corners Only</option>-->
<!--                                    <option  value="No Grommets">No Grommets</option>-->
<!--                                </select>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                        <div class="field lamination">-->
<!--                            <label class="label" for="lamination">Lamination</span></label>-->
<!--                            <div class="control">-->
<!--                                <select name="lamination" id="lamination">-->
<!--                                    <option  value="N/A">Choose a selection...</option>-->
<!--                                    <option  value="Dry Erase Lamination  +$15.00">Dry Erase Lamination  +$15.00</option>-->
<!--                                    <option  value="Matte Lamination  +$4.81">Matte Lamination  +$4.81</option>-->
<!--                                    <option  value="High Gloss Lamination  +$4.80">High Gloss Lamination  +$4.80</option>-->
<!--                                    <option  value="FedEx Overnight">No Lamination</option>-->
<!--                                </select>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->

                <div class="field delivery">
                    <label class="label" for="delivery">Delivery Method Required</span></label>
                    <div class="control">
                        <select name="delivery" id="delivery">
                            <option  value="Pick-Up">Pick-Up</option>
                            <option  value="Free-Delivery">Free-Delivery</option>
                            <option  value="FedEx Ground">FedEx Ground</option>
                            <option  value="FedEx Overnight">FedEx Overnight</option>
                            <option  value="FedEx 2nd Day">FedEx 2nd Day</option>
                            <option  value="FedEx Express Saver">FedEx Express Saver</option>
                        </select>
                    </div>
                    <p>* Only Certain LA County (California) locations qualify for Free-Delivery</p>
                    <br/>
                </div>

                <div class="field overview required">
                    <label class="label" for="overview"><span>Additional Note</span></label>
                    <div class="control">
                        <textarea name="overview" id="overview" title="Brief Overview" class="input-text" cols="5" rows="7" data-validate="{required:true}"></textarea>
                    </div>
                </div>

                <div class="field prd">
                    <label for="prd">Upload Document:</label>
                    <div class="input-box">
                        <input type="file" id="prd" name="prd">
                        <br>
                        <p> <?= __("You can upload files with these file extensions only (%1)", $block->getAllowedFileExtensions()) ?> </p>
                    </div>
                </div>
            </div>
        </div>


        
        <?= $block->getChildHtml('form.additional.info'); ?>
    </fieldset>
    <div class="actions-toolbar custom-submit">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="Submit" class="action submit primary">
                <span>SUBMIT</span>
            </button>
        </div>
    </div>
</form>

<script type="text/javascript">
    require(['jquery', 'jquery/ui'], function ($) {
        $(document).ready(function () {
            // Custom Estimate
            $("#category").change(function () {
                var id = $(this).val();
                if (id == 1) {
                    $('.material_01').removeClass('hidden');
                    $('.material_01').addClass('active');
                    $('.material_02').addClass('hidden');
                    $('.material_03').addClass('hidden');
                    $('.material_04').addClass('hidden');
                    $('.material_05').addClass('hidden');
                    $('.material_06').addClass('hidden');
                    $('.finishing_options').removeClass('hidden');
                    $('.finishing_options').addClass('active');
                    $('.lamination_options').addClass('hidden');
                    $('.round_corners_options').addClass('hidden');
                    $('.color_options').addClass('hidden');
                    $('.diecut_options').addClass('hidden');
                    $('.frame_options').addClass('hidden');
                    $('.grommet_options').addClass('hidden');
                    $('.hstake_options').addClass('hidden');
                    $('.lamination_options_02').addClass('hidden');
                    $('.thickness_options').addClass('hidden');
                    $('.thickness_options_02').addClass('hidden');
                    $('.thickness_options_03').addClass('hidden');
                    $('.thickness_options_04').addClass('hidden');
                    $('.standtype_options').addClass('hidden');
                    $('.size_options').addClass('hidden');
                    $('.size_options_02').addClass('hidden');
                    $('.width').removeClass('hidden');
                    $('.width').addClass('active');
                    $('.height').removeClass('hidden');
                    $('.height').addClass('active');
                    $('.carmodel').addClass('hidden');
                    $('.carwrapping').addClass('hidden');
                } else if (id == 2) {
                    $('.material_01').addClass('hidden');
                    $('.material_02').removeClass('hidden');
                    $('.material_02').addClass('active');
                    $('.material_03').addClass('hidden');
                    $('.material_04').addClass('hidden');
                    $('.material_05').addClass('hidden');
                    $('.material_06').addClass('hidden');
                    $('.lamination_options').removeClass('hidden');
                    $('.lamination_options').addClass('active');
                    $('.round_corners_options').removeClass('hidden');
                    $('.round_corners_options').addClass('active');
                    $('.finishing_options').addClass('hidden');
                    $('.color_options').addClass('hidden');
                    $('.diecut_options').addClass('hidden');
                    $('.frame_options').addClass('hidden');
                    $('.grommet_options').addClass('hidden');
                    $('.hstake_options').addClass('hidden');
                    $('.lamination_options_02').addClass('hidden');
                    $('.thickness_options').addClass('hidden');
                    $('.thickness_options_02').addClass('hidden');
                    $('.thickness_options_03').addClass('hidden');
                    $('.thickness_options_04').addClass('hidden');
                    $('.standtype_options').addClass('hidden');
                    $('.size_options').addClass('hidden');
                    $('.size_options_02').addClass('hidden');
                    $('.width').removeClass('hidden');
                    $('.width').addClass('active');
                    $('.height').removeClass('hidden');
                    $('.height').addClass('active');
                    $('.carmodel').addClass('hidden');
                    $('.carwrapping').addClass('hidden');
                } else if (id == 3) {
                    $('.material_01').addClass('hidden');
                    $('.material_02').addClass('hidden');
                    $('.material_03').removeClass('hidden');
                    $('.material_03').addClass('active');
                    $('.material_04').addClass('hidden');
                    $('.material_05').addClass('hidden');
                    $('.material_06').addClass('hidden');
                    $('.finishing_options').addClass('hidden');
                    $('.lamination_options').addClass('hidden');
                    $('.round_corners_options').addClass('hidden');
                    $('.color_options').addClass('hidden');
                    $('.diecut_options').addClass('hidden');
                    $('.frame_options').addClass('hidden');
                    $('.grommet_options').addClass('hidden');
                    $('.hstake_options').addClass('hidden');
                    $('.lamination_options_02').addClass('hidden');
                    $('.thickness_options').addClass('hidden');
                    $('.thickness_options_02').addClass('hidden');
                    $('.thickness_options_03').addClass('hidden');
                    $('.thickness_options_04').addClass('hidden');
                    $('.standtype_options').addClass('hidden');
                    $('.size_options').addClass('hidden');
                    $('.size_options_02').addClass('hidden');
                    $('.width').removeClass('hidden');
                    $('.width').addClass('active');
                    $('.height').removeClass('hidden');
                    $('.height').addClass('active');
                    $('.carmodel').addClass('hidden');
                    $('.carwrapping').addClass('hidden');
                } else if (id == 4) {
                    $('.material_01').addClass('hidden');
                    $('.material_02').addClass('hidden');
                    $('.material_03').addClass('hidden');
                    $('.material_04').removeClass('hidden');
                    $('.material_04').addClass('active');
                    $('.material_05').addClass('hidden');
                    $('.material_06').addClass('hidden');
                    $('.round_corners_options').removeClass('hidden');
                    $('.round_corners_options').addClass('active');
                    $('.color_options').removeClass('hidden');
                    $('.color_options').addClass('active');
                    $('.grommet_options').removeClass('hidden');
                    $('.grommet_options').addClass('active');
                    $('.lamination_options').removeClass('hidden');
                    $('.lamination_options').addClass('active');
                    $('.finishing_options').addClass('hidden');
                    $('.diecut_options').addClass('hidden');
                    $('.frame_options').addClass('hidden');
                    $('.hstake_options').addClass('hidden');
                    $('.lamination_options_02').addClass('hidden');
                    $('.thickness_options').addClass('hidden');
                    $('.thickness_options_02').addClass('hidden');
                    $('.thickness_options_03').addClass('hidden');
                    $('.thickness_options_04').addClass('hidden');
                    $('.standtype_options').addClass('hidden');
                    $('.size_options').addClass('hidden');
                    $('.size_options_02').addClass('hidden');
                    $('.width').removeClass('hidden');
                    $('.width').addClass('active');
                    $('.height').removeClass('hidden');
                    $('.height').addClass('active');
                    $('.carmodel').addClass('hidden');
                    $('.carwrapping').addClass('hidden');
                } else if (id == 5) {
                    $('.standtype_options').removeClass('hidden');
                    $('.standtype_options').addClass('active');
                    $('.material_01').addClass('hidden');
                    $('.material_02').addClass('hidden');
                    $('.material_03').addClass('hidden');
                    $('.material_04').addClass('hidden');
                    $('.material_05').removeClass('hidden');
                    $('.material_05').addClass('active');
                    $('.material_06').addClass('hidden');
                    $('.finishing_options').addClass('hidden');
                    $('.lamination_options').addClass('hidden');
                    $('.round_corners_options').addClass('hidden');
                    $('.color_options').addClass('hidden');
                    $('.diecut_options').addClass('hidden');
                    $('.frame_options').addClass('hidden');
                    $('.grommet_options').addClass('hidden');
                    $('.hstake_options').addClass('hidden');
                    $('.lamination_options_02').addClass('hidden');
                    $('.thickness_options').addClass('hidden');
                    $('.thickness_options_02').addClass('hidden');
                    $('.thickness_options_03').addClass('hidden');
                    $('.thickness_options_04').addClass('hidden');
                    $('.size_options').removeClass('hidden');
                    $('.size_options').addClass('active');
                    $('.size_options_02').addClass('hidden');
                    $('.width').addClass('hidden');
                    $('.height').addClass('hidden');
                    $('.carmodel').addClass('hidden');
                    $('.carwrapping').addClass('hidden');
                } else if (id == 6) {
                    $('.standtype_options').addClass('hidden');
                    $('.material_01').addClass('hidden');
                    $('.material_02').addClass('hidden');
                    $('.material_03').addClass('hidden');
                    $('.material_04').addClass('hidden');
                    $('.material_05').addClass('hidden');
                    $('.material_06').addClass('hidden');
                    $('.finishing_options').addClass('hidden');
                    $('.lamination_options').addClass('hidden');
                    $('.round_corners_options').addClass('hidden');
                    $('.color_options').addClass('hidden');
                    $('.diecut_options').addClass('hidden');
                    $('.frame_options').addClass('hidden');
                    $('.grommet_options').addClass('hidden');
                    $('.hstake_options').addClass('hidden');
                    $('.lamination_options_02').addClass('hidden');
                    $('.thickness_options').addClass('hidden');
                    $('.thickness_options_02').addClass('hidden');
                    $('.thickness_options_03').addClass('hidden');
                    $('.thickness_options_04').addClass('hidden');
                    $('.size_options').addClass('hidden');
                    $('.size_options_02').addClass('hidden');
                    $('.width').addClass('hidden');
                    $('.height').addClass('hidden');
                    $('.carmodel').removeClass('hidden');
                    $('.carmodel').addClass('active');
                    $('.carwrapping').removeClass('hidden');
                    $('.carwrapping').addClass('active');
                } else {
                }
            });
            $("#material_01").change(function() {
                var id=$(this).val();
                if(id==21) {
                    $('.color_options').removeClass('hidden');
                    $('.color_options').addClass('active');
                } else {
                    $('.color_options').removeClass('active');
                    $('.color_options').addClass('hidden');
                }
            });
            $("#material_02").change(function() {
                var id=$(this).val();
                if(id==25) {
                    $('.lamination_options').removeClass('active');
                    $('.lamination_options').addClass('hidden');
                } else {
                    $('.lamination_options').removeClass('hidden');
                    $('.lamination_options').addClass('active');
                }
            });
            $("#material_03").change(function() {
                var id=$(this).val();
                if((id==31) || (id==36)) {
                    $('.frame_options').removeClass('active');
                    $('.frame_options').addClass('hidden');
                    $('.lamination_options_02').removeClass('active');
                    $('.lamination_options_02').addClass('hidden');
                    $('.round_corners_options').removeClass('active');
                    $('.round_corners_options').addClass('hidden');
                } else  if (id == 32) {
                    $('.lamination_options_02').removeClass('active');
                    $('.lamination_options_02').addClass('hidden');
                    $('.round_corners_options').removeClass('active');
                    $('.round_corners_options').addClass('hidden');
                    $('.frame_options').removeClass('hidden');
                    $('.frame_options').addClass('active');
                } else  if (id == 33) {
                    $('.lamination_options_02').removeClass('hidden');
                    $('.lamination_options_02').addClass('active');
                    $('.round_corners_options').removeClass('hidden');
                    $('.round_corners_options').addClass('active');
                    $('.frame_options').removeClass('active');
                    $('.frame_options').addClass('hidden');
                } else  if((id==34) || (id==35)) {
                    $('.lamination_options_02').removeClass('hidden');
                    $('.lamination_options_02').addClass('active');
                    $('.round_corners_options').removeClass('active');
                    $('.round_corners_options').addClass('hidden');
                    $('.frame_options').removeClass('active');
                    $('.frame_options').addClass('hidden');
                }
            });
            $("#material_04").change(function() {
                var id=$(this).val();
                if((id==40) || (id==41) || (id==43) || (id==44)) {
                    $('.round_corners_options').removeClass('hidden');
                    $('.round_corners_options').addClass('active');
                    $('.color_options').removeClass('hidden');
                    $('.color_options').addClass('active');
                    $('.grommet_options').removeClass('hidden');
                    $('.grommet_options').addClass('active');
                    $('.lamination_options').removeClass('hidden');
                    $('.lamination_options').addClass('active');
                    $('.diecut_options').removeClass('active');
                    $('.diecut_options').addClass('hidden');
                    $('.thickness_options').removeClass('active');
                    $('.thickness_options').addClass('hidden');
                    $('.thickness_options_02').removeClass('active');
                    $('.thickness_options_02').addClass('hidden');
                    $('.thickness_options_03').removeClass('active');
                    $('.thickness_options_03').addClass('hidden');
                    $('.thickness_options_04').removeClass('active');
                    $('.thickness_options_04').addClass('hidden');
                    $('.hstake_options').removeClass('active');
                    $('.hstake_options').addClass('hidden');
                } else  if (id == 42) {
                    $('.round_corners_options').removeClass('hidden');
                    $('.round_corners_options').addClass('active');
                    $('.color_options').removeClass('hidden');
                    $('.color_options').addClass('active');
                    $('.grommet_options').removeClass('hidden');
                    $('.grommet_options').addClass('active');
                    $('.lamination_options').removeClass('active');
                    $('.lamination_options').addClass('hidden');
                    $('.diecut_options').removeClass('active');
                    $('.diecut_options').addClass('hidden');
                    $('.thickness_options').removeClass('active');
                    $('.thickness_options').addClass('hidden');
                    $('.thickness_options_02').removeClass('active');
                    $('.thickness_options_02').addClass('hidden');
                    $('.thickness_options_03').removeClass('active');
                    $('.thickness_options_03').addClass('hidden');
                    $('.thickness_options_04').removeClass('active');
                    $('.thickness_options_04').addClass('hidden');
                    $('.hstake_options').removeClass('active');
                    $('.hstake_options').addClass('hidden');
                } else  if (id == 45) {
                    $('.round_corners_options').removeClass('hidden');
                    $('.round_corners_options').addClass('active');
                    $('.color_options').removeClass('hidden');
                    $('.color_options').addClass('active');
                    $('.grommet_options').removeClass('hidden');
                    $('.grommet_options').addClass('active');
                    $('.lamination_options').removeClass('hidden');
                    $('.lamination_options').addClass('active');
                    $('.diecut_options').removeClass('hidden');
                    $('.diecut_options').addClass('active');
                    $('.thickness_options').removeClass('hidden');
                    $('.thickness_options').addClass('active');
                    $('.thickness_options_02').removeClass('active');
                    $('.thickness_options_02').addClass('hidden');
                    $('.thickness_options_03').removeClass('active');
                    $('.thickness_options_03').addClass('hidden');
                    $('.thickness_options_04').removeClass('active');
                    $('.thickness_options_04').addClass('hidden');
                    $('.hstake_options').removeClass('active');
                    $('.hstake_options').addClass('hidden');
                } else  if (id == 46) {
                    $('.round_corners_options').removeClass('hidden');
                    $('.round_corners_options').addClass('active');
                    $('.color_options').removeClass('hidden');
                    $('.color_options').addClass('active');
                    $('.grommet_options').removeClass('hidden');
                    $('.grommet_options').addClass('active');
                    $('.lamination_options').removeClass('hidden');
                    $('.lamination_options').addClass('active');
                    $('.diecut_options').removeClass('active');
                    $('.diecut_options').addClass('hidden');
                    $('.thickness_options').removeClass('active');
                    $('.thickness_options').addClass('hidden');
                    $('.thickness_options_02').removeClass('hidden');
                    $('.thickness_options_02').addClass('active');
                    $('.thickness_options_03').removeClass('active');
                    $('.thickness_options_03').addClass('hidden');
                    $('.thickness_options_04').removeClass('active');
                    $('.thickness_options_04').addClass('hidden');
                    $('.hstake_options').removeClass('active');
                    $('.hstake_options').addClass('hidden');
                } else  if (id == 47) {
                    $('.round_corners_options').removeClass('hidden');
                    $('.round_corners_options').addClass('active');
                    $('.color_options').removeClass('hidden');
                    $('.color_options').addClass('active');
                    $('.grommet_options').removeClass('hidden');
                    $('.grommet_options').addClass('active');
                    $('.lamination_options').removeClass('hidden');
                    $('.lamination_options').addClass('active');
                    $('.diecut_options').removeClass('active');
                    $('.diecut_options').addClass('hidden');
                    $('.thickness_options').removeClass('active');
                    $('.thickness_options').addClass('hidden');
                    $('.thickness_options_02').removeClass('active');
                    $('.thickness_options_02').addClass('hidden');
                    $('.thickness_options_03').removeClass('active');
                    $('.thickness_options_03').addClass('hidden');
                    $('.thickness_options_04').removeClass('active');
                    $('.thickness_options_04').addClass('hidden');
                    $('.hstake_options').removeClass('active');
                    $('.hstake_options').addClass('hidden');
                } else  if (id == 48) {
                    $('.round_corners_options').removeClass('hidden');
                    $('.round_corners_options').addClass('active');
                    $('.color_options').removeClass('hidden');
                    $('.color_options').addClass('active');
                    $('.grommet_options').removeClass('hidden');
                    $('.grommet_options').addClass('active');
                    $('.lamination_options').removeClass('hidden');
                    $('.lamination_options').addClass('active');
                    $('.diecut_options').removeClass('active');
                    $('.diecut_options').addClass('hidden');
                    $('.thickness_options').removeClass('active');
                    $('.thickness_options').addClass('hidden');
                    $('.thickness_options_02').removeClass('active');
                    $('.thickness_options_02').addClass('hidden');
                    $('.thickness_options_03').removeClass('hidden');
                    $('.thickness_options_03').addClass('active');
                    $('.thickness_options_04').removeClass('active');
                    $('.thickness_options_04').addClass('hidden');
                    $('.hstake_options').removeClass('active');
                    $('.hstake_options').addClass('hidden');
                } else if (id == 49)  {
                    $('.round_corners_options').removeClass('hidden');
                    $('.round_corners_options').addClass('active');
                    $('.color_options').removeClass('hidden');
                    $('.color_options').addClass('active');
                    $('.grommet_options').removeClass('hidden');
                    $('.grommet_options').addClass('active');
                    $('.lamination_options').removeClass('active');
                    $('.lamination_options').addClass('hidden');
                    $('.diecut_options').removeClass('active');
                    $('.diecut_options').addClass('hidden');
                    $('.thickness_options').removeClass('active');
                    $('.thickness_options').addClass('hidden');
                    $('.thickness_options_02').removeClass('active');
                    $('.thickness_options_02').addClass('hidden');
                    $('.thickness_options_03').removeClass('active');
                    $('.thickness_options_03').addClass('hidden');
                    $('.thickness_options_04').removeClass('hidden');
                    $('.thickness_options_04').addClass('active');
                    $('.hstake_options').removeClass('hidden');
                    $('.hstake_options').addClass('active');
                }
            });
            $("#standtype_options").change(function() {
                var id=$(this).val();
                if(id==101) {
                    $('.standtype_options').removeClass('hidden');
                    $('.standtype_options').addClass('active');
                    $('.material_01').addClass('hidden');
                    $('.material_02').addClass('hidden');
                    $('.material_03').addClass('hidden');
                    $('.material_04').addClass('hidden');
                    $('.material_05').removeClass('hidden');
                    $('.material_05').addClass('active');
                    $('.material_06').addClass('hidden');
                    $('.finishing_options').addClass('hidden');
                    $('.lamination_options').addClass('hidden');
                    $('.round_corners_options').addClass('hidden');
                    $('.color_options').addClass('hidden');
                    $('.diecut_options').addClass('hidden');
                    $('.frame_options').addClass('hidden');
                    $('.grommet_options').addClass('hidden');
                    $('.hstake_options').addClass('hidden');
                    $('.lamination_options_02').addClass('hidden');
                    $('.thickness_options').addClass('hidden');
                    $('.thickness_options_02').addClass('hidden');
                    $('.thickness_options_03').addClass('hidden');
                    $('.thickness_options_04').addClass('hidden');
                    $('.size_options').removeClass('hidden');
                    $('.size_options').addClass('active');
                    $('.size_options_02').addClass('hidden');
                    $('.width').addClass('hidden');
                    $('.height').addClass('hidden');
                } else  if (id == 102) {
                    $('.standtype_options').removeClass('hidden');
                    $('.standtype_options').addClass('active');
                    $('.material_01').addClass('hidden');
                    $('.material_02').addClass('hidden');
                    $('.material_03').addClass('hidden');
                    $('.material_04').addClass('hidden');
                    $('.material_05').addClass('hidden');
                    $('.material_06').removeClass('hidden');
                    $('.material_06').addClass('active');
                    $('.finishing_options').addClass('hidden');
                    $('.lamination_options').addClass('hidden');
                    $('.round_corners_options').addClass('hidden');
                    $('.color_options').addClass('hidden');
                    $('.diecut_options').addClass('hidden');
                    $('.frame_options').addClass('hidden');
                    $('.grommet_options').addClass('hidden');
                    $('.hstake_options').addClass('hidden');
                    $('.lamination_options_02').addClass('hidden');
                    $('.thickness_options').addClass('hidden');
                    $('.thickness_options_02').addClass('hidden');
                    $('.thickness_options_03').addClass('hidden');
                    $('.thickness_options_04').addClass('hidden');
                    $('.size_options_02').removeClass('hidden');
                    $('.size_options_02').addClass('active');
                    $('.size_options').addClass('hidden');
                    $('.width').addClass('hidden');
                    $('.height').addClass('hidden');
                } else  if ((id == 103) || (id==104)) {
                    $('.standtype_options').removeClass('hidden');
                    $('.standtype_options').addClass('active');
                    $('.material_01').addClass('hidden');
                    $('.material_02').addClass('hidden');
                    $('.material_03').addClass('hidden');
                    $('.material_04').addClass('hidden');
                    $('.material_05').addClass('hidden');
                    $('.material_06').addClass('hidden');
                    $('.finishing_options').addClass('hidden');
                    $('.lamination_options').addClass('hidden');
                    $('.round_corners_options').addClass('hidden');
                    $('.color_options').addClass('hidden');
                    $('.diecut_options').addClass('hidden');
                    $('.frame_options').addClass('hidden');
                    $('.grommet_options').addClass('hidden');
                    $('.hstake_options').addClass('hidden');
                    $('.lamination_options_02').addClass('hidden');
                    $('.thickness_options').addClass('hidden');
                    $('.thickness_options_02').addClass('hidden');
                    $('.thickness_options_03').addClass('hidden');
                    $('.thickness_options_04').addClass('hidden');
                    $('.size_options_02').addClass('hidden');
                    $('.size_options').addClass('hidden');
                    $('.width').addClass('hidden');
                    $('.height').addClass('hidden');
                }
            });
            $("#size_options").change(function() {
                var id=$(this).val();
                if(id==0) {
                    $('.width').removeClass('hidden');
                    $('.width').addClass('active');
                    $('.height').removeClass('hidden');
                    $('.height').addClass('active');
                } else {
                    $('.width').removeClass('active');
                    $('.width').addClass('hidden');
                    $('.height').removeClass('active');
                    $('.height').addClass('hidden');
                }
            });
        })
    })
</script>