<?php
/**
 * Copyright © 2015 J2T Design. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<tr class="totals totals-rewards">
    <th colspan="<?php echo $block->getColspan(); ?>" style="<?php echo $block->getTotal()->getStyle() ?>" class="mark minilist" scope="row">
        <?php if ($block->getRenderingArea() == $block->getTotal()->getArea()): ?><strong><?php endif; ?>
            <?php echo $block->escapeHtml($block->getTotal()->getTitle()); ?> <?php echo __("(%1 point(s))", $this->getUsedPoints());?>
            <?php if($this->getShowRemoveLink()):?><a href="javascript:jQuery('.cancelPoints').click();" class="action delete"><span><?php echo __("Remove");?></span></a><?php endif;?>
        <?php if ($block->getRenderingArea() == $block->getTotal()->getArea()): ?></strong><?php endif; ?>
    </th>
    <td style="<?php echo $block->getTotal()->getStyle() ?>" class="amount" data-th="<?php echo $block->escapeHtml($block->getTotal()->getTitle()); ?>">
        <?php if ($block->getRenderingArea() == $block->getTotal()->getArea()): ?><strong><?php endif; ?>
            <span><?php echo $this->helper('Magento\Checkout\Helper\Data')->formatPrice($block->getTotal()->getValue()) ?></span>
        <?php if ($block->getRenderingArea() == $block->getTotal()->getArea()): ?></strong><?php endif; ?>
    </td>
</tr>
