<?php
/**
 * Customer login form template
 * @var \Magento\Customer\Block\Form\Login $block
 * @see \Magento\Customer\Block\Form\Login
 * @var $block \Magento\Customer\Block\Form\Login
 */
?>

<div class="col-xs-12 col-sm-6 col-md-5">
    <div class="block block-customer-login">
        <div class="block-title">
            <div class="login-register-title"><?= __('Log in') ?></div>
            <legend class="legend"><span><?= __('Registered Customers') ?></span></legend><br>
        </div>
        <div class="block-content" aria-labelledby="block-customer-login-heading">
            <form class="form form-login"
                  action="<?= $block->getPostActionUrl() ?>"
                  method="post"
                  id="login-form"
                  data-mage-init='{"validation":{}}'>
                <?= $block->getBlockHtml('formkey'); ?>
                <fieldset class="fieldset login" data-hasrequired="<?= __('* Required Fields') ?>">
                    <div class="field note"><?= __('If you have an account with us, please log in.') ?></div>
                    <div class="field email required">
                        <label class="label" for="email"><span><?= __('Email Address') ?></span></label>
                        <div class="control">
                            <input name="login[username]" value="<?= $block->escapeHtml($block->getUsername()) ?>"
                                <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?>
                                   id="email" type="email" class="input-text" title="<?= __('Email') ?>" data-validate="{required:true, 'validate-email':true}">
                        </div>
                    </div>
                    <div class="field password required">
                        <label for="pass" class="label"><span><?= __('Password') ?></span></label>
                        <div class="control">
                            <input name="login[password]" type="password"
                                <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> class="input-text" id="pass"
                                   title="<?= __('Password') ?>" data-validate="{required:true, 'validate-password':true}">
                        </div>
                    </div>
                    <div class="field note"><?= __('* Required Fields') ?></div>
                    <?= $block->getChildHtml('form_additional_info'); ?>
                    <div class="actions-toolbar">
                        <div class="secondary"><a class="action remind" href="<?= $block->getForgotPasswordUrl() ?>"><span><?= __('Forgot Your Password?') ?></span></a></div>
                        <div class="primary"><button type="submit" class="action login primary" name="send" id="send2"><span><?= __('LOGIN') ?></span></button></div>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</div>