<?php
/**
 * Create account form template
 *
 * @var $block \Magento\Customer\Block\Form\Register
 */
?>

<div class="col-xs-12 col-sm-6 col-md-5">
    <?php $block->setShowAddressFields(true); ?>
    <?php echo $block->getChildHtml('form_fields_before')?>
    <?php /* Extensions placeholder */ ?>
    <?php echo $block->getChildHtml('customer.form.register.extra')?>
    <form class="form create account form-create-account" action="<?= $block->getPostActionUrl() ?>" onsubmit="return validateForm()" method="post" id="form-validate"
          enctype="multipart/form-data" autocomplete="off">
        <fieldset class="fieldset create info">
            <div class="login-register-title"><?= __('Create an Account') ?></div>
            <legend class="legend"><span><?= __('Personal Information') ?></span></legend><br>
            <input type="hidden" name="success_url" value="<?= $block->getSuccessUrl() ?>">
            <input type="hidden" name="error_url" value="<?= $block->getErrorUrl() ?>">

            <div class="field required">
                <label for="email_address" class="label"><span><?= __('Email Address') ?></span></label>
                <div class="control">
                    <input type="email" name="email" id="email_address" value="<?php echo $block->escapeHtml($block->getFormData()->getEmail()) ?>" title="<?= __('Email') ?>"
                           class="input-text" data-validate="{required:true, 'validate-email':true}">
                </div>
            </div>
            <div class="field password required">
                <label for="password" class="label"><span><?= __('Password') ?></span></label>
                <div class="control">
                    <input type="password" name="password" id="password" title="<?= __('Password') ?>" class="input-text"
                           data-validate="{required:true, 'validate-password':true}" autocomplete="off">
                </div>
            </div>
            <div class="field confirmation required">
                <label for="password-confirmation" class="label"><span><?= __('Confirm Password') ?></span></label>
                <div class="control">
                    <input type="password" name="password_confirmation" title="<?= __('Confirm Password') ?>" id="password-confirmation"
                           class="input-text" data-validate="{required:true, equalTo:'#password'}" autocomplete="off">
                </div>
            </div>
            <?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($block->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>

            <?php $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
            <?php if ($_dob->isEnabled()): ?>
                <?php echo $_dob->setDate($block->getFormData()->getDob())->toHtml() ?>
            <?php endif ?>

            <?php $_taxvat = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Taxvat') ?>
            <?php if ($_taxvat->isEnabled()): ?>
                <?php echo $_taxvat->setTaxvat($block->getFormData()->getTaxvat())->toHtml() ?>
            <?php endif ?>

            <?php $_gender = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>
            <?php if ($_gender->isEnabled()): ?>
                <?php echo $_gender->setGender($block->getFormData()->getGender())->toHtml() ?>
            <?php endif ?>
        </fieldset>

        <fieldset class="fieldset address">
            <legend class="legend"><span><?= __('Address Information') ?></span></legend><br>
            <input type="hidden" name="create_address" value="1" />
            <div class="field company required">
                <label for="company" class="label"><span><?= __('Company') ?></span></label>
                <div class="control">
                    <input type="text" name="company" id="company" value="<?php echo $block->escapeHtml($block->getFormData()->getCompany()) ?>"
                           title="<?= __('Company') ?>" class="input-text <?= $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('company') ?>" data-validate="{required:true}">
                </div>
            </div>
            <div class="field telephone required">
                <label for="telephone" class="label"><span><?= __('Phone Number') ?></span></label>
                <div class="control">
                    <input type="text" name="telephone" id="telephone" value="<?php echo $block->escapeHtml($block->getFormData()->getTelephone()) ?>"
                           title="<?= __('Phone Number') ?>" class="input-text <?= $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('telephone') ?>">
                </div>
            </div>

            <?php $_streetValidationClass = $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('street'); ?>

            <div class="field street required">
                <label for="street_1" class="label"><span><?= __('Street Address') ?></span></label>
                <div class="control">
                    <input type="text" name="street[]" value="<?php echo $block->escapeHtml($block->getFormData()->getStreet(0)) ?>"
                           title="<?= __('Street Address') ?>" id="street_1" class="input-text <?= $_streetValidationClass ?>">
                    <div class="nested">
                        <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                        <?php for ($_i = 2, $_n = $this->helper('Magento\Customer\Helper\Address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                            <div class="field additional">
                                <label class="label" for="street_<?= $_i ?>">
                                    <span><?= __('Address') ?></span>
                                </label>
                                <div class="control">
                                    <input type="text" name="street[]" value="<?php echo $block->escapeHtml($block->getFormData()->getStreetLine($_i - 1)) ?>"
                                           title="<?= __('Street Address %1', $_i) ?>" id="street_<?= $_i ?>" class="input-text <?= $_streetValidationClass ?>">
                                </div>
                            </div>
                        <?php endfor; ?>
                    </div>
                </div>
            </div>

            <div class="field required">
                <label for="city" class="label"><span><?= __('City') ?></span></label>
                <div class="control">
                    <input type="text" name="city" value="<?php echo $block->escapeHtml($block->getFormData()->getCity()) ?>" title="<?= __('City') ?>"
                           class="input-text <?= $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city') ?>" id="city">
                </div>
            </div>

            <div class="field region required">
                <label for="region_id" class="label"><span><?= __('State/Province') ?></span></label>
                <div class="control">
                    <select id="region_id" name="region_id" title="<?= __('State/Province') ?>" class="validate-select" style="display:none;">
                        <option value=""><?= __('Please select a region, state or province.') ?></option>
                    </select>
                    <input type="text" id="region" name="region" value="<?php echo $block->escapeHtml($block->getRegion()) ?>" title="<?= __('State/Province') ?>" class="input-text <?= $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region') ?>" style="display:none;">
                </div>
            </div>

            <div class="field zip required">
                <label for="zip" class="label"><span><?= __('Zip/Postal Code') ?></span></label>
                <div class="control">
                    <input type="text" name="postcode" value="<?php echo $block->escapeHtml($block->getFormData()->getPostcode()) ?>"
                           data-validate="{required:true}" title="<?= __('Zip/Postal Code') ?>"
                           id="zip" class="input-text validate-zip-international <?= $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode') ?>">
                </div>
            </div>

            <div class="field country required">
                <label for="country" class="label"><span><?= __('Country') ?></span></label>
                <div class="control">
                    <?php echo $block->getCountryHtmlSelect() ?>
                </div>
            </div>
            <?php $addressAttributes = $block->getChildBlock('customer_form_address_user_attributes');?>
            <?php if ($addressAttributes): ?>
                <?php $addressAttributes->setEntityType('customer_address'); ?>
                <?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]');?>
                <?php $block->restoreSessionData($addressAttributes->getMetadataForm(), 'address');?>
                <?php echo $addressAttributes->setShowContainer(false)->toHtml()?>
            <?php endif;?>
            <input type="hidden" name="default_billing" value="1">
            <input type="hidden" name="default_shipping" value="1">
        </fieldset>

        <fieldset class="fieldset create account" data-hasrequired="<?= __('* Required Fields') ?>">

            <div class="field website_url">
                <label for="website_url" class="label"><span><?= __('Website (URL)') ?></span></label>
                <div class="control">
                    <input type="text" name="website_url" id="website_url" title="<?= __('Website URL') ?>" class="input-text" />
                </div>
            </div>
            <div class="field required">
                <label for="seller_file" class="label"><span><?= __('Seller\'s Permit') ?></span></label>
                <div class="control">
                    <input type="file" name="seller_file" id="seller_permit_upload" data-validate="{required:true}" title="<?= __('Seller\'s Permit') ?>" />
                </div>
            </div>
            <div class="field optional_message">
                <label for="optional_message" class="label"><span><?= __('Optional Message') ?></span></label>
                <div class="control">
                    <textarea name="optional_message" title="<?= __('Optional Message') ?>" id="optional_message"
                              class="input-text" autocomplete="off" rows="5"></textarea>
                </div>
            </div>

            <?php echo $block->getChildHtml('form_additional_info'); ?>
            <!-- dev lam -->
            <script src='https://www.google.com/recaptcha/api.js'></script>
            <div class="g-recaptcha" data-sitekey="6LeWb0sUAAAAADM2RJayBwgBFAvGlCgWwDClJgtl"  data-callback="recaptchaCallback" data-expired-callback="recaptchaExpired"></div>
            <input type="hidden" name="recaptcha" data-rule-recaptcha="true">
        
            <script type="text/javascript">
                function validateForm() {   
                    var recaptcha = document.forms["form-validate"]["g-recaptcha-response"].value;
                    if (recaptcha == "") {
                        alert("Please fill reCAPTCHA");
                        return false;
                    }
                }
            </script>
            <!-- End dev lam -->
            <?php if ($block->isNewsletterEnabled()): ?>
                <div class="field choice newsletter">
                    <input type="checkbox" name="is_subscribed" title="<?= __('Sign Up for Newsletter') ?>"
                           value="1" id="is_subscribed"<?php if ($block->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox">
                    <label for="is_subscribed" class="label"><span><?= __('Sign Up for Newsletter') ?></span></label>
                </div>
                <?php /* Extensions placeholder */ ?>
                <?php echo $block->getChildHtml('customer.form.register.newsletter')?>
            <?php endif ?>
            <div class="field note"><?= __('* Required Fields') ?></div>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action submit primary" title="<?= __('Create an Account') ?>"><span><?= __('REGISTER') ?></span></button>
            </div>
            <div class="secondary">
                <a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?= __('Back') ?></span></a>
            </div>
        </div>
    </form>

    <script>
        require([
            'jquery',
            'mage/mage'
        ], function($){

            var dataForm = $('#form-validate');
            var ignore = <?= $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null'; ?>;

            dataForm.mage('validation', {
                <?php if ($_dob->isEnabled()): ?>
                errorPlacement: function(error, element) {
                    if (element.prop('id').search('full') !== -1) {
                        var dobElement = $(element).parents('.customer-dob'),
                            errorClass = error.prop('class');
                        error.insertAfter(element.parent());
                        dobElement.find('.validate-custom').addClass(errorClass)
                            .after('<div class="' + errorClass + '"></div>');
                    }
                    else {
                        error.insertAfter(element);
                    }
                },
                ignore: ':hidden:not(' + ignore + ')'
                <?php else: ?>
                ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
                <?php endif ?>
            }).find('input:text').attr('autocomplete', 'off');

        });
    </script>

    <?php if ($block->getShowAddressFields()): ?>
        <script type="text/x-magento-init">
        {
            "#country": {
                "regionUpdater": {
                    "optionalRegionAllowed": <?=($block->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
                    "regionListId": "#region_id",
                    "regionInputId": "#region",
                    "postcodeId": "#zip",
                    "form": "#form-validate",
                    "regionJson": <?= $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
                    "defaultRegion": "<?= $block->getFormData()->getRegionId() ?>",
                    "countriesWithOptionalZip": <?= $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
                }
            }
        }
    </script>
    <?php endif; ?>

</div>