<?php
if (!$block->pricecalculatorHelper->isEnabledInFrontend()) {
    return;
}
$helper = $block->pricecalculatorHelper;
$isFrontSecure = $block->storeManager->getStore()
    ->isCurrentlySecure();
$currencySymbol = $block->storeManager->getStore()
    ->getCurrentCurrency()->getCurrencySymbol();

$_product = $block->getProduct();
$productFinalPrice = $_product->getFinalPrice();
$customOptions = $_product->getOptions();
$fieldOptions = $helper->getFieldOptions($_product);
$showBasePrice = $helper->showBasePrice();
$showDiscountPrice = $helper->showDiscountPrice();
$discountTitle = $helper->getDiscountTitle();
$unitPrice = $_product->getPriceUnitArea();
$pricingRule = $block->getProductPricingRule($_product);
$inputUnit = $helper->getInputUnitLabel($_product);
$outputUnit = $helper->getOutputUnitLabel($_product);


$outputUnitLabel = $outputUnit;
if ($pricingRule['by'] == 'volume') {
    $outputUnitLabel = 'Cubic ' . $outputUnit;
    $areaVolLabel = __('Volume');
} else
    if ($pricingRule['by'] == 'area') {
        $outputUnitLabel = 'Square ' . $outputUnit;
        $areaVolLabel = __('Area');
    } else {
        $outputUnitLabel = $outputUnit;
        $areaVolLabel = $pricingRule['by']; //length or width or depth
    }


$unitCoversion = $helper->unitConversion($inputUnit, $outputUnit);


$fields = [];
$totalOp = 0;

foreach ($customOptions as $option):
    if (isset($fieldOptions[$option->getTitle()])) {
        $totalOp++;
    }
endforeach;

?>
<script type="text/javascript">
    require(['jquery',
        'priceBox',
        'mage/translate',
        'Magento_Catalog/js/price-utils',
        'mage/validation',
        'jquery/ui'
    ], function ($, priceBox, $t, priceUtils) {

        priceBox = new priceBox();
        var productFinalPrice = "<?= $this->helper('Magento\Framework\Pricing\Helper\Data')->currency(number_format($productFinalPrice, 2), true, false); ?>";

        var fields = [];
        var nof_options = 0;
        var total_options = "<?= $totalOp; ?>";
        var showBasePrice = "<?= $showBasePrice; ?>";
        var showDiscountPrice = "<?= $showDiscountPrice; ?>";
        var discountTitle = "<?= $discountTitle; ?>";
        var areaVolLabel = "<?= $areaVolLabel; ?>";
        var first_load = 0;
        var current_url = window.location.href;
        var is_edit = current_url.indexOf('checkout/cart/configure/id');


        <?php foreach ($customOptions as $option): ?>
        <?php if (isset($fieldOptions[$option->getTitle()])): ?>

        var opId = "<?= $option->getId() ?>";
        var opIdName = '#options_<?= $option->getId() ?>_text';
        var opJid = $('#options_<?= $option->getId() ?>_text');

        //change field title/label for input/output
        var parent = $('#options_<?= $option->getId() ?>_text').parent().parent();
        var child = parent.find('label span');
        var str = child[0].innerHTML + ' (' + '<?= $inputUnit ?>' + ')';
        child[0].innerHTML = str;

        if ($('#calculations').text() === '') {
            var calculations = '<div id="calculations" style="color:#0000FF">' + areaVolLabel + ': <span></span></div>';
            var discount_price = '<div id="discount_price">' + discountTitle + ': <span></span></div>';
            var base_price = '<div id="base_price">Base Price: ' + productFinalPrice + '</div>';
            var html_insert = calculations;

            if (showDiscountPrice == 1) {
                html_insert = html_insert + discount_price;
            }
            if (showBasePrice == 1) {
                html_insert = html_insert + base_price;
            }
            $('#product-options-wrapper').after(html_insert + '<br>');
        }


        if (opId !== "undefined") {
            fields[opId] = "options[" + opId + "]";
            //fields.push("options[" + opId + "]");
        }

        var min_<?= $option->getId() ?> = <?= $fieldOptions[$option->getTitle()]['min'] ?>;
        var max_<?= $option->getId() ?> = <?= $fieldOptions[$option->getTitle()]['max'] ?>;

        $.validator.addMethod('pricecalculator-minmax-<?= $option->getTitle() ?>', function (value) {
            return !(value < min_<?= $option->getId() ?> || value > max_<?= $option->getId() ?>);
        }, $.mage.__('Please enter between ' + min_<?= $option->getId() ?> + ' and ' + max_<?= $option->getId() ?>));

        var dataId<?= $option->getId() ?> = $('#options_<?= $option->getId() ?>_text').data("validate");

        if (!("pricecalculator-minmax-<?= $option->getTitle() ?>" in dataId<?= $option->getId() ?>)) {
            var newObj = {"pricecalculator-minmax-<?= $option->getTitle() ?>": true};
            $.extend(dataId<?= $option->getId() ?>, newObj);
            var itemStringify = JSON.stringify(dataId<?= $option->getId() ?>)
                .replace(/&quot;/g, '"');
            $('#options_<?= $option->getId() ?>_text').attr("data-validate", itemStringify);
        }

        //check on change
        $('#options_<?= $option->getId() ?>_text').change(function () {
            var value = $(this).val();

            if (value === '') {
                $(this).val(0);
                updatePriceOnChange(0, <?= $option->getId() ?>);
                return;
            }

            if ($.validator.validateElement($('#options_<?= $option->getId() ?>_text'))) {
                disableAddToCartBtn('#product_addtocart_form');
                //calculatePrice($(this));                
                enableAddToCartBtn('#product_addtocart_form');
            }
            showFinalPrice();
        });

        <?php endif; ?>
        <?php endforeach; ?>

        function calculatePrice(elemObj) {
            var elemName = elemObj.attr('name');
            var additionalPriceObj = priceBox.cache.additionalPriceObject;

            var unitPrice = <?= $unitPrice ?>;
            var area = calculateArea(fields); //increment nof_options
            var discount = calculateDiscount(area, unitPrice);
            var price = parseFloat(unitPrice * area) - discount;

            $.each(additionalPriceObj, function (key, val) {

                if ($.inArray(key, fields) > -1) {
                    //if (key === elemName) { 
                    if (nof_options == total_options) {
                        if (additionalPriceObj[key].basePrice) {

                            if (is_edit > -1 && first_load == 0) {
                                additionalPriceObj[key].basePrice.amount = parseFloat(price);
                            } else {
                                additionalPriceObj[key].basePrice.amount = parseFloat(price / nof_options);
                            }
                        }
                        if (additionalPriceObj[key].finalPrice) {

                            if (is_edit > -1 && first_load == 0) {
                                first_load++;
                                additionalPriceObj[key].finalPrice.amount = parseFloat(price);
                            } else {
                                additionalPriceObj[key].finalPrice.amount = parseFloat(price / nof_options);
                            }
                        }
                    }
                    //}
                }
            });

            $("div.price-box .price-final_price").trigger("updatePrice");

        }

        function calculateArea(fields) {
            var area = 1;
            nof_options = 0;
            var outputUnit = "<?= $outputUnitLabel ?>";

            $.each(fields, function (key, val) {

                if (val !== undefined) {
                    if (parseFloat($('#options_' + key + '_text').val()) !== 0) {
                        var option_val = parseFloat($('#options_' + key + '_text').val());
                        area = area * option_val;
                        nof_options++;
                    }
                }
            });

            var unitConv = parseFloat(<?= $unitCoversion ?>);
            area = area * unitConv;

            var Cover = area/144;
            Cover = Number(Math.round(Cover * 100) / 100);
            $('#calculations span').text(Cover + ' (Square Feet)');
            return area;
        }


        function calculateDiscount(area, unitPrice) {
            var rules = <?= json_encode($pricingRule) ?>;
            var discount = 0;
            if (area < parseFloat(rules.size.min_limit)) {
                discount = 0;
            } else if (area >= parseFloat(rules.size.min_limit) && area < parseFloat(rules.size.max_limit)) {
                if (rules.type === 'percent') {
                    discount = parseFloat((area * unitPrice) * (parseFloat(rules.discount.min_limit) / 100));
                } else {
                    discount = parseFloat(rules.discount.min_limit);
                }

            } else if (area >= parseFloat(rules.size.max_limit)) {
                if (rules.type === 'percent') {
                    discount = parseFloat((area * unitPrice) * (parseFloat(rules.discount.max_limit) / 100));
                } else {
                    discount = parseFloat(rules.discount.max_limit);
                }
            }
            var currency_symbol = "<?= $currencySymbol; ?>";

            if (showDiscountPrice == 1) {
                $('#discount_price span').text(currency_symbol + discount.toFixed(2));
            }

            return discount;
        }

        function getDiscountRate(area) {
            var rules = <?= json_encode($pricingRule) ?>;  
            var sizes = rules.size;           
            var discounts = rules.discount; 
            var discount = 0;

            if (sizes && discounts && sizes.length > 0 && discounts.length > 0) {
                var l_sizes = sizes.length;
                var l_discounts = discounts.length;

                for (i = 0; i < l_sizes; i++) {
                    if ( i < (l_sizes - 1) && parseInt(sizes[i]) <= area && area < parseInt(sizes[i+1]) ) {
                        if (typeof discounts[i] !== 'undefined') {
                            discount = discounts[i];
                            break;
                        }                     
                    } else if ( i == (l_sizes - 1) && parseInt(sizes[i]) <= area ) {
                        if (typeof discounts[i] !== 'undefined') {
                            discount = discounts[i];
                            break;
                        }                     
                    }
                }
            }
                // chek 13oz Vinyl Banner
                var Material_296 = $('#select_296').find(":selected").attr('value');
                Material_296 = (isNaN(Material_296)) ? 0 : parseFloat(Material_296); 
                if(Material_296 == 543){
                    discount =0;
                }
                // check Canvas Roll
                var Material_430 = $('#select_430').find(":selected").attr('value');
                Material_430 = (isNaN(Material_430)) ? 0 : parseFloat(Material_430); 
                if(Material_430 == 798){
                    discount =0;
                }
                // chek 14oz Vinyl Banner
                var Material_305 = $('#select_305').find(":selected").attr('value');
                Material_305 = (isNaN(Material_305)) ? 0 : parseFloat(Material_305); 
                if(Material_305 == 569){
                    discount =0;
                }

            return parseFloat(discount);
        }


        function updatePriceOnChange(fp = 0, opid) {
            var additionalPriceObj = priceBox.cache.additionalPriceObject;
            var rowOpKey = "options[" + opid + "]";

            var rowPriceOp = additionalPriceObj[rowOpKey];
            // console.log(additionalPriceObj.toSource());

            if (!$.isEmptyObject(rowPriceOp)) {
                rowPriceOp.basePrice.amount = fp;
                rowPriceOp.finalPrice.amount = fp;
            }

            $("div.price-box .price-final_price").trigger("updatePrice");
        }

        function disableAddToCartBtn(form) {
            var addToCartButton = $(form).find('.action.tocart');
            addToCartButton.addClass('disabled');
            addToCartButton.attr('title', $t('Checking...'));
            addToCartButton.find('span').text($t('Checking...'));
        }

        function enableAddToCartBtn(form) {
            var addToCartButton = $(form).find('.action.tocart');
            addToCartButton.attr('title', $t('Checking...'));
            addToCartButton.find('span').text($t('Checking...'));
            setTimeout(function () {
                addToCartButton.removeClass('disabled');

                if (is_edit > -1) {
                    addToCartButton.find('span').text($t('Update Cart'));
                    addToCartButton.attr('title', $t('Update Cart'));
                } else {
                    addToCartButton.find('span').text($t('Add to Cart'));
                    addToCartButton.attr('title', $t('Add to Cart'));
                }

            }, 1000);
        }

        /**
         * Display total price per unit product
         */
        function showFinalPrice() {
            // Call area price
            var total = 0;
            var unitAreaPrice = 0;
            <?php if (isset($unitPrice) && $unitPrice != '') echo 'unitAreaPrice = ' . $unitPrice . ';' ?>
            var area = calculateArea(fields);
            area = (isNaN(area)) ? 0 : area;
            var pricePerUnit = area * unitAreaPrice;

            // pricePerUnit = Number(Math.round(pricePerUnit * 100) / 100); // Lam tron 2 chu so

         

            // Get id product
            var price = 0;
            var Allprice = 0;
            var id = parseInt($('#banner_product').attr('data-id'));
            var isDefault = true;
            var Reinforced_333 =0; 
            var pocket = 0;
            var tich = 0;
            var areaPrice = 0;
            var heso = area / 144;
            var Lamination_price = 0;
            var value_qty = 0;
            var discountCustom = 0;
            var Ptram = 0;
            var isTurnaround = 1;
            // area: dien tich, unitAreaPrice: gia cho 1 don vi dien tich


           
            if (id == 93) { // Backlit Banner
                var Reinforced_333 = $('#select_333').find(":selected").attr('price');
                Reinforced_333 = (isNaN(Reinforced_333)) ? 0 : parseFloat(Reinforced_333);
                var pocket = $('#select_334').find(":selected").attr('value');
                pocket = (isNaN(pocket)) ? 0 : parseFloat(pocket);
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_1012').addClass('Addactive');
                }else{
                     $('.Art_1012').removeClass('Addactive');
                     $('.Artworks_1013').hide();
                     $("#select_1012 option:selected").removeAttr("selected");
                }
                if(pocket ==633){
                    isTurnaround = 1.7;
                } else{
                    isTurnaround = 1;
                }
                isDefault = false;
                total = (pricePerUnit + Reinforced_333) * isTurnaround;

            } else if (id == 92) { // 16 oz Blockout Banner
                var Wind_321 = $('#select_321').find(":selected").attr('price');
                Wind_321 = (isNaN(Wind_321)) ? 0 : parseFloat(Wind_321);
                var Reinforced_324 = $('#select_324').find(":selected").attr('price');
                Reinforced_324 = (isNaN(Reinforced_324)) ? 0 : parseFloat(Reinforced_324);
                var Pole_320 = $('#select_320').find(":selected").attr('price');
                Pole_320 = (isNaN(Pole_320)) ? 0 : parseFloat(Pole_320);
                var PocketSize_680 = $('#select_680').find(":selected").attr('price');
                PocketSize_680 = (isNaN(PocketSize_680)) ? 0 : parseFloat(PocketSize_680);
                var Turnaround_325 = $('#select_325').find(":selected").attr('value');
                Turnaround_325 = (isNaN(Turnaround_325)) ? 0 : parseFloat(Turnaround_325);
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_1010').addClass('Addactive');
                }else{
                     $('.Art_1010').removeClass('Addactive');
                     $('.Artworks_1011').hide();
                     $("#select_1010 option:selected").removeAttr("selected");
                }
                if(Turnaround_325 ==618){
                    isTurnaround = 1.7;
                    
                } else{
                    isTurnaround = 1;
                }
                isDefault = false;
                total = (pricePerUnit + Wind_321 + Reinforced_324 + Pole_320 + PocketSize_680) * isTurnaround;

            } else if (id == 94) { // Double Sided Banner (Super Smooth)
                var Material_336 = $('#select_336').find(":selected").attr('price');
                Material_336 = (isNaN(Material_336)) ? 0 : parseFloat(Material_336);
                var Wind_342 = $('#select_342').find(":selected").attr('price');
                Wind_342 = (isNaN(Wind_342)) ? 0 : parseFloat(Wind_342);
                var Pole_340 = $('#select_340').find(":selected").attr('price');
                Pole_340 = (isNaN(Pole_340)) ? 0 : parseFloat(Pole_340);
                var PocketSize_834 = $('#select_834').find(":selected").attr('price');
                PocketSize_834 = (isNaN(PocketSize_834)) ? 0 : parseFloat(PocketSize_834);
                var Turnaround_343 = $('#select_343').find(":selected").attr('value');
                Turnaround_343 = (isNaN(Turnaround_343)) ? 0 : parseFloat(Turnaround_343);
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_345').addClass('Addactive');
                }else{
                     $('.Art_345').removeClass('Addactive');
                     $('.Artworks_836').hide();
                     $("#select_345 option:selected").removeAttr("selected");
                }
                if(Turnaround_343 == 654){
                    isTurnaround = 1.7;      
                } else{
                    isTurnaround = 1;
                }
                isDefault = false;
                total = (pricePerUnit * Material_336 + (Wind_342 + Pole_340 + PocketSize_834)) * isTurnaround;  

            } else if (id == 95) { // Fabric Banner- Premium 
                var Pole_351 = $('#select_351').find(":selected").attr('price');
                Pole_351 = (isNaN(Pole_351)) ? 0 : parseFloat(Pole_351);
                var PocketSize_837 = $('#select_837').find(":selected").attr('price');
                PocketSize_837 = (isNaN(PocketSize_837)) ? 0 : parseFloat(PocketSize_837);
                var Turnaround_353 = $('#select_353').find(":selected").attr('value');
                Turnaround_353 = (isNaN(Turnaround_353)) ? 0 : parseFloat(Turnaround_353);
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_1014').addClass('Addactive');
                }else{
                     $('.Art_1014').removeClass('Addactive');
                     $("#select_1014 option:selected").removeAttr("selected");
                     $('.Artworks_1015').hide();
                     
                }
                if(Turnaround_353 ==675){
                    isTurnaround = 1.7;   
                } else{
                    isTurnaround = 1;
                }
                isDefault = false;
                total = (heso* 1.49 + Pole_351 + PocketSize_837) * isTurnaround; 

            }  else if (id == 96) { // Mesh Banner 
                var Pole_392 = $('#select_392').find(":selected").attr('price');
                Pole_392 = (isNaN(Pole_392)) ? 0 : parseFloat(Pole_392);
                var PocketSize_839 = $('#select_839').find(":selected").attr('price');
                PocketSize_839 = (isNaN(PocketSize_839)) ? 0 : parseFloat(PocketSize_839);
                var Turnaround_395 = $('#select_395').find(":selected").attr('value');
                Turnaround_395 = (isNaN(Turnaround_395)) ? 0 : parseFloat(Turnaround_395);
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_1016').addClass('Addactive');
                }else{
                     $('.Art_1016').removeClass('Addactive');
                     $('.Artworks_1017').hide();
                     $("#select_1016 option:selected").removeAttr("selected");
                }
                if(Turnaround_395 == 764){
                    isTurnaround =  1.7;
                } else{
                    isTurnaround = 1;
                }
                isDefault = false;
                total = (pricePerUnit + Pole_392 + PocketSize_839) * isTurnaround;

            } else if (id == 97) { // Premium Coated Banner
                var Pole_380 = $('#select_380').find(":selected").attr('price');
                Pole_380 = (isNaN(Pole_380)) ? 0 : parseFloat(Pole_380);
                var Wind_381 = $('#select_381').find(":selected").attr('price');
                Wind_381 = (isNaN(Wind_381)) ? 0 : parseFloat(Wind_381);
                var PocketSize_842 = $('#select_842').find(":selected").attr('price');
                PocketSize_842 = (isNaN(PocketSize_842)) ? 0 : parseFloat(PocketSize_842);
                var Reinforced_384  = $('#select_384').find(":selected").attr('price');
                Reinforced_384 = (isNaN(Reinforced_384)) ? 0 : parseFloat(Reinforced_384);
                var Turnaround_385 = $('#select_385').find(":selected").attr('value');
                Turnaround_385 = (isNaN(Turnaround_385)) ? 0 : parseFloat(Turnaround_385);
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_1018').addClass('Addactive');
                }else{
                     $('.Art_1018').removeClass('Addactive');
                     $('.Artworks_1019').hide();
                     $("#select_1018 option:selected").removeAttr("selected");
                }
                if(Turnaround_385 ==744){
                    isTurnaround =  1.7;
                    
                } else{
                    isTurnaround = 1;
                }
                isDefault = false;
                total = (pricePerUnit + Pole_380 + Wind_381 + PocketSize_842 + Reinforced_384) * isTurnaround;

            } else if (id == 90) { // 13oz Vinyl Banner
                var Material_296 = $('#select_296').find(":selected").attr('value');
                Material_296 = (isNaN(Material_296)) ? 0 : parseFloat(Material_296); 
                if(Material_296 == 543){
                    rateDiscount =0;

                }
                var Pole_298 = $('#select_298').find(":selected").attr('price');
                Pole_298 = (isNaN(Pole_298)) ? 0 : parseFloat(Pole_298);
                var Wind_299 = $('#select_299').find(":selected").attr('price');
                Wind_299 = (isNaN(Wind_299)) ? 0 : parseFloat(Wind_299);
                var PocketSize_829 = $('#select_829').find(":selected").attr('price');
                PocketSize_829 = (isNaN(PocketSize_829)) ? 0 : parseFloat(PocketSize_829);
                var Reinforced_302  = $('#select_302').find(":selected").attr('price');
                Reinforced_302 = (isNaN(Reinforced_302)) ? 0 : parseFloat(Reinforced_302);
                var Turnaround_303 = $('#select_303').find(":selected").attr('value');
                Turnaround_303 = (isNaN(Turnaround_303)) ? 0 : parseFloat(Turnaround_303);
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_1006').addClass('Addactive');
                }else{
                     $('.Art_1006').removeClass('Addactive');
                     $('.Artworks_1007').hide();
                     $("#select_1006 option:selected").removeAttr("selected");
                }
                if(Turnaround_303 ==1314){
                    isTurnaround = 1.7;
                }else{
                    isTurnaround = 1;
                }
                isDefault = false;
                total = (pricePerUnit + Pole_298 + Wind_299 + PocketSize_829 + Reinforced_302) * isTurnaround;

            } else if (id == 91) { // 14oz Vinyl Banner
                var Pole_309 = $('#select_309').find(":selected").attr('price');
                Pole_309 = (isNaN(Pole_309)) ? 0 : parseFloat(Pole_309);
                var Wind_310 = $('#select_310').find(":selected").attr('price');
                Wind_310 = (isNaN(Wind_310)) ? 0 : parseFloat(Wind_310);
                var PocketSize_845 = $('#select_845').find(":selected").attr('price');
                PocketSize_845 = (isNaN(PocketSize_845)) ? 0 : parseFloat(PocketSize_845);
                var Reinforced_850  = $('#select_850').find(":selected").attr('price');
                Reinforced_850 = (isNaN(Reinforced_850)) ? 0 : parseFloat(Reinforced_850);
                var Turnaround_314 = $('#select_314').find(":selected").attr('value');
                Turnaround_314 = (isNaN(Turnaround_314)) ? 0 : parseFloat(Turnaround_314);
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_1008').addClass('Addactive');
                }else{
                     $('.Art_1008').removeClass('Addactive');
                    $('.Artworks_1009').hide();
                    $("#select_1008 option:selected").removeAttr("selected");
                }
                if(Turnaround_314 ==593){
                    isTurnaround = 1.7;
                }else if(Turnaround_314 ==592){
                    isTurnaround = 1;
                }
                isDefault = false;
                total = (pricePerUnit + Pole_309 + Wind_310 + PocketSize_845 + Reinforced_850) * isTurnaround;

            } else if (id == 98) { // Super Smooth Banner
                var Material_365 = $('#select_365').find(":selected").attr('price');
                Material_365 = (isNaN(Material_365)) ? 0 : parseFloat(Material_365);
                var Wind_370 = $('#select_370').find(":selected").attr('price');
                Wind_370 = (isNaN(Wind_370)) ? 0 : parseFloat(Wind_370);
                var Pole_369 = $('#select_369').find(":selected").attr('price');
                Pole_369 = (isNaN(Pole_369)) ? 0 : parseFloat(Pole_369);
                var PocketSize_848 = $('#select_848').find(":selected").attr('price');
                PocketSize_848 = (isNaN(PocketSize_848)) ? 0 : parseFloat(PocketSize_848);
                var Turnaround_374 = $('#select_374').find(":selected").attr('value');
                Turnaround_374 = (isNaN(Turnaround_374)) ? 0 : parseFloat(Turnaround_374);
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_1020').addClass('Addactive');
                }else{
                     $('.Art_1020').removeClass('Addactive');
                     $('.Artworks_1021').hide();
                     $("#select_1020 option:selected").removeAttr("selected");
                }
                if(Turnaround_374 ==720){
                    isTurnaround = 1.7;       
                }
                else{
                    isTurnaround = 1;
                }
                isDefault = false;
                total = (pricePerUnit * Material_365 + (Wind_370 + Pole_369 + PocketSize_848)) * isTurnaround; 
            } else if (id == 99) { // Fabric Banner- Deluxe
                var Pole_360 = $('#select_360').find(":selected").attr('price');
                Pole_360 = (isNaN(Pole_360)) ? 0 : parseFloat(Pole_360);
                var PocketSize_851 = $('#select_851').find(":selected").attr('price');
                PocketSize_851 = (isNaN(PocketSize_851)) ? 0 : parseFloat(PocketSize_851);
                var Turnaround_362 = $('#select_362').find(":selected").attr('value');
                Turnaround_362 = (isNaN(Turnaround_362)) ? 0 : parseFloat(Turnaround_362);
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_1022').addClass('Addactive');
                }else{
                     $('.Art_1022').removeClass('Addactive');
                     $('.Artworks_1023').hide();
                     $("#select_1022 option:selected").removeAttr("selected");
                }
                if(Turnaround_362 == 694){
                    isTurnaround =  1.7;
                } else{
                    isTurnaround = 1;
                }
                isDefault = false;
                total = (pricePerUnit + Pole_360 + PocketSize_851) * isTurnaround;

            } else if (id == 100) { // 3M Controltac (IJ 180C)
                var Lamination_402 = $('#select_402').find(":selected").attr('price');
                Lamination_402 = (isNaN(Lamination_402)) ? 0 : parseFloat(Lamination_402);
                var Turnaround_403 = $('#select_403').find(":selected").attr('value');
                Turnaround_403 = (isNaN(Turnaround_403)) ? 0 : parseFloat(Turnaround_403);
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_1024').addClass('Addactive');
                }else{
                     $('.Art_1024').removeClass('Addactive');
                     $('.Artworks_1025').hide();
                     $("#select_1024 option:selected").removeAttr("selected");
                }
                if(Turnaround_403 ==770){
                    isTurnaround =  1.7;
                } else{
                    isTurnaround = 1;
                }
                isDefault = false;
                total = heso * (2.5 + Lamination_402) * isTurnaround;

            } else if (id == 101) { // 3M IJ35 Adhesive Vinyl
                var Material_408 = $('#select_408').find(":selected").attr('price');
                Material_408 = (isNaN(Material_408)) ? 0 : parseFloat(Material_408);
                var Lamination_410 = $('#select_410').find(":selected").attr('price');
                Lamination_410 = (isNaN(Lamination_410)) ? 0 : parseFloat(Lamination_410);
                var Turnaround_411 = $('#select_411').find(":selected").attr('value');
                Turnaround_411 = (isNaN(Turnaround_411)) ? 0 : parseFloat(Turnaround_411);
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_1026').addClass('Addactive');
                }else{
                     $('.Art_1026').removeClass('Addactive');
                     $('.Artworks_1027').hide();
                     $("#select_1026 option:selected").removeAttr("selected");
                }
                if(Turnaround_411 ==778){
                    isTurnaround =  1.7;                
                } else{
                    isTurnaround = 1;
                }
                isDefault = false;
                total = (heso * (Material_408 + Lamination_410)) * isTurnaround; 

            } else if (id == 102) { // Bumper Stickers
                var Size_416 = $('#select_416').find(":selected").attr('price');
                Size_416 = (isNaN(Size_416)) ? 0 : parseFloat(Size_416);
                var Rounded_417 = $('#select_417').find(":selected").attr('price');
                Rounded_417 = (isNaN(Rounded_417)) ? 0 : parseFloat(Rounded_417);
                var Turnaround_418 = $('#select_418').find(":selected").attr('value');
                Turnaround_418 = (isNaN(Turnaround_418)) ? 0 : parseFloat(Turnaround_418);
                if(Turnaround_418 ==788){
                    total = (Size_416 + Rounded_417 ) * 1.7;
                }
                else{
                    total = Size_416 + Rounded_417;
                }
                isDefault = false;

            } else if (id == 123) { // Floor Graphics
                var Material_505 = $('#select_505').find(":selected").attr('price');
                Material_505 = (isNaN(Material_505)) ? 0 : parseFloat(Material_505);
                var Lamination_507 = $('#select_507').find(":selected").attr('value');
                Lamination_507 = (isNaN(Lamination_507)) ? 0 : parseFloat(Lamination_507);
                var Turnaround_508 = $('#select_508').find(":selected").attr('value');
                Turnaround_508 = (isNaN(Turnaround_508)) ? 0 : parseFloat(Turnaround_508);
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_1028').addClass('Addactive');
                }else{
                     $('.Art_1028').removeClass('Addactive');
                     $('.Artworks_1029').hide();
                     $("#select_1028 option:selected").removeAttr("selected");
                }
                if(Turnaround_508 ==901){
                    isTurnaround = 1.7;
                } else{
                    isTurnaround = 1;
                }
                isDefault = false;
                total = heso * Material_505 * isTurnaround;

            } else if (id == 126) { // Perforated Stickers (One-Way Vision)
                var Material_498 = $('#select_498').find(":selected").attr('price');
                Material_498 = (isNaN(Material_498)) ? 0 : parseFloat(Material_498);
                var Turnaround_500 = $('#select_500').find(":selected").attr('value');
                Turnaround_500 = (isNaN(Turnaround_500)) ? 0 : parseFloat(Turnaround_500);
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_1030').addClass('Addactive');
                }else{
                     $('.Art_1030').removeClass('Addactive');
                     $('.Artworks_1031').hide();
                     $("#select_1030 option:selected").removeAttr("selected");
                }
                if(Turnaround_500 == 896){
                    isTurnaround = 1.7;
                } else{
                    isTurnaround = 1;
                }
                isDefault = false;
                total = heso * Material_498 * isTurnaround;

            } else if (id == 127) { // Static Clings (Window Clings)
                var Material_491 = $('#select_491').find(":selected").attr('price');
                Material_491 = (isNaN(Material_491)) ? 0 : parseFloat(Material_491);
                var Turnaround_493 = $('#select_493').find(":selected").attr('value');
                Turnaround_493 = (isNaN(Turnaround_493)) ? 0 : parseFloat(Turnaround_493);
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_1032').addClass('Addactive');
                }else{
                     $('.Art_1032').removeClass('Addactive');
                     $('.Artworks_1033').hide();
                     $("#select_1032 option:selected").removeAttr("selected");
                }
                if(Turnaround_493 ==892){
                    isTurnaround = 1.7;
                } else{
                    isTurnaround = 1;
                }
                isDefault = false;
                total = heso * Material_491 * isTurnaround;

            } else if (id == 128) { // Vinyl Stickers (Window Decal)
                var Material_483 = $('#select_483').find(":selected").attr('price');
                Material_483 = (isNaN(Material_483)) ? 0 : parseFloat(Material_483);
                var Lamination_485 = $('#select_485').find(":selected").attr('price');
                Lamination_485 = (isNaN(Lamination_485)) ? 0 : parseFloat(Lamination_485);
                var Turnaround_486 = $('#select_486').find(":selected").attr('value');
                Turnaround_486 = (isNaN(Turnaround_486)) ? 0 : parseFloat(Turnaround_486);
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_1034').addClass('Addactive');
                }else{
                     $('.Art_1034').removeClass('Addactive');
                     $('.Artworks_1035').hide();
                     $("#select_1034 option:selected").removeAttr("selected");
                }
                if(Turnaround_486 ==887){
                    isTurnaround = 1.7;
                } else{
                    isTurnaround = 1;
                }
                isDefault = false;
                total = heso * (Material_483 + Lamination_485) * isTurnaround;

            } else if (id == 129) { // Wall Vinyl Decals
                var Material_475 = $('#select_475').find(":selected").attr('price');
                Material_475 = (isNaN(Material_475)) ? 0 : parseFloat(Material_475);
                var Lamination_477 = $('#select_477').find(":selected").attr('price');
                Lamination_477 = (isNaN(Lamination_477)) ? 0 : parseFloat(Lamination_477);
                var Turnaround_478 = $('#select_478').find(":selected").attr('value');
                Turnaround_478 = (isNaN(Turnaround_478)) ? 0 : parseFloat(Turnaround_478);
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_1036').addClass('Addactive');
                }else{
                     $('.Art_1036').removeClass('Addactive');
                     $('.Artworks_1037').hide();
                     $("#select_1036 option:selected").removeAttr("selected");
                }
                if(Turnaround_478 ==877){
                    isTurnaround =  2;
                } else{
                    isTurnaround = 1;
                }
                isDefault = false;
                total = heso * (Material_475 + Lamination_477) * isTurnaround;

            } else if (id == 103) { // Backlit Film 
                var Lamination_426 = $('#select_426').find(":selected").attr('price');
                Lamination_426 = (isNaN(Lamination_426)) ? 0 : parseFloat(Lamination_426);
                var Turnaround_427 = $('#select_427').find(":selected").attr('value');
                Turnaround_427 = (isNaN(Turnaround_427)) ? 0 : parseFloat(Turnaround_427);
                pricePerUnit = Number(Math.round(pricePerUnit * 100) / 100); // Lam tron 2 chu so
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_1038').addClass('Addactive');
                }else{
                     $('.Art_1038').removeClass('Addactive');
                     $('.Artworks_1039').hide();
                     $("#select_1038 option:selected").removeAttr("selected");
                }
                if(Turnaround_427 == 796){
                    isTurnaround = 1.7;
                } else{
                    isTurnaround = 1;
                }
                isDefault = false;
                total = heso * (3.5 + Lamination_426) * isTurnaround;

            } else if (id == 104) { // Canvas Roll
                var Material_430 = $('#select_430').find(":selected").attr('price');
                Material_430 = (isNaN(Material_430)) ? 0 : parseFloat(Material_430);
                var Turnaround_434 = $('#select_434').find(":selected").attr('value');
                Turnaround_434 = (isNaN(Turnaround_434)) ? 0 : parseFloat(Turnaround_434);
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_1040').addClass('Addactive');
                }else{
                     $('.Art_1040').removeClass('Addactive');
                     $('.Artworks_1041').hide();
                     $("#select_1040 option:selected").removeAttr("selected");
                }
                if(Turnaround_434 == 801){
                    isTurnaround = 1.7;
                } else{
                    isTurnaround = 1;
                }
                isDefault = false;
                total = heso * Material_430 * isTurnaround;

            } else if (id == 132) { // Car Magnets
                var Lamination_532 = $('#select_532').find(":selected").attr('price');
                Lamination_532 = (isNaN(Lamination_532)) ? 0 : parseFloat(Lamination_532);
                var Round_533 = $('#select_533').find(":selected").attr('price');
                Round_533 = (isNaN(Round_533)) ? 0 : parseFloat(Round_533);
                var Turnaround_534 = $('#select_534').find(":selected").attr('value');
                Turnaround_534 = (isNaN(Turnaround_534)) ? 0 : parseFloat(Turnaround_534);
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_1048').addClass('Addactive');
                }else{
                     $('.Art_1048').removeClass('Addactive');
                     $('.Artworks_1049').hide();
                     $("#select_1048 option:selected").removeAttr("selected");
                }
                if(Turnaround_534 ==931){
                    isTurnaround = 1.7;
                } else{
                    isTurnaround = 1;
                }
                isDefault = false;
                total = ((heso * Lamination_532)  + Round_533) * isTurnaround;

            } else if (id == 155) { // Framed Canvas

                var widthVal_811 = $('#options_811_text').attr('value');
                widthVal_811 = (isNaN(widthVal_811)) ? 0 : parseFloat(widthVal_811);
                var HeightVal_812 = $('#options_812_text').attr('value');
                HeightVal_812 = (isNaN(HeightVal_812)) ? 0 : parseFloat(HeightVal_812);

                var Lamination_524 = $('#select_524').find(":selected").attr('price');
                Lamination_524 = (isNaN(Lamination_524)) ? 0 : parseFloat(Lamination_524);
                var Turnaround_815 = $('#select_815').find(":selected").attr('value');
                Turnaround_815 = (isNaN(Turnaround_815)) ? 0 : parseFloat(Turnaround_815);
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_1044').addClass('Addactive');
                }else{
                     $('.Art_1044').removeClass('Addactive');
                     $('.Artworks_1045').hide();
                     $("#select_1044 option:selected").removeAttr("selected");
                }
                if((widthVal_811 == 12 || widthVal_811 == 18 || widthVal_811 == 24 || widthVal_811 == 30 || widthVal_811 == 36  || widthVal_811 == 48) && (HeightVal_812 == 12 || HeightVal_812 == 18 || HeightVal_812 == 24 || HeightVal_812 == 30 || HeightVal_812 == 36  || HeightVal_812 == 48)){

                    if(Turnaround_815 ==1305){
                        areaPrice = area * 8 / 144;
                        total = areaPrice * 2 * 1.7;
                    }
                    else if(Turnaround_815 == 1303){
                        areaPrice = area * 8 / 144;
                        total = areaPrice * 1.5;
                    }else{
                        total = area * 8 / 144;
                    }

                }else{
                    if(Turnaround_815 ==1305){
                        areaPrice = area * 9 / 144;
                        total = areaPrice * 1.7;
                    }
                    else if(Turnaround_815 == 1303){
                        areaPrice = area * 9 / 144;
                        total = areaPrice * 1.5;
                    }else{
                        total = area * 9 / 144;
                    }
                }
                isDefault = false;

            } else if (id == 131) { // Digital Poster
                var Lamination_524 = $('#select_524').find(":selected").attr('price');
                Lamination_524 = (isNaN(Lamination_524)) ? 0 : parseFloat(Lamination_524);
                var Turnaround_525 = $('#select_525').find(":selected").attr('value');
                Turnaround_525 = (isNaN(Turnaround_525)) ? 0 : parseFloat(Turnaround_525);
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_1046').addClass('Addactive');
                }else{
                     $('.Art_1046').removeClass('Addactive');
                     $('.Artworks_1047').hide();
                     $("#select_1046 option:selected").removeAttr("selected");
                }
                if(Turnaround_525 ==921){
                    total = heso * Lamination_524 * 1.7;
                } else if(Turnaround_525 == 920){
                    total = heso * Lamination_524;
                } else{
                    total = 0;
                }
                isDefault = false;

            } else if (id == 130) { // Polypropylene (PET) 
                var Lamination_516 = $('#select_516').find(":selected").attr('price');
                Lamination_516 = (isNaN(Lamination_516)) ? 0 : parseFloat(Lamination_516);
                var Turnaround_515 = $('#select_515').find(":selected").attr('value');
                Turnaround_515 = (isNaN(Turnaround_515)) ? 0 : parseFloat(Turnaround_515);
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_1042').addClass('Addactive');
                }else{
                     $('.Art_1042').removeClass('Addactive');
                     $('.Artworks_1043').hide();
                     $("#select_1042 option:selected").removeAttr("selected");
                }
                if(Turnaround_515 ==905){
                    total = (heso * (Lamination_516 + 2.5)) * 1.7;
                } else if(Turnaround_515 == 904){
                    total = heso * (Lamination_516 + 2.5);
                } else{
                    total = 0;
                }
                isDefault = false;

            } else if (id == 106) { // Acrylic Boards
                var Lamination_448 = $('#select_448').find(":selected").attr('price');
                Lamination_448 = (isNaN(Lamination_448)) ? 0 : parseFloat(Lamination_448);
                var Material_447 = $('#select_447').find(":selected").attr('price');
                Material_447 = (isNaN(Material_447)) ? 0 : parseFloat(Material_447);
                var Drill_449 = $('#select_449').find(":selected").attr('price');
                Drill_449 = (isNaN(Drill_449)) ? 0 : parseFloat(Drill_449);
                var Rounded_450 = $('#select_450').find(":selected").attr('price');
                Rounded_450 = (isNaN(Rounded_450)) ? 0 : parseFloat(Rounded_450);
                var Turnaround_451 = $('#select_451').find(":selected").attr('value');
                Turnaround_451 = (isNaN(Turnaround_451)) ? 0 : parseFloat(Turnaround_451);
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_1050').addClass('Addactive');
                }else{
                     $('.Art_1050').removeClass('Addactive');
                     $('.Artworks_1051').hide();
                     $("#select_1050 option:selected").removeAttr("selected");
                }
                if(Turnaround_451 ==834){
                    isTurnaround = 1.7 ;
                } else{
                    isTurnaround = 1;
                }
                isDefault = false;
                total = (heso * (Lamination_448 + Material_447 ) + Drill_449) * isTurnaround  + Rounded_450;

            } else if (id == 107) { //  Aluminum Sandwich Board “Dibond”
                var Lamination_458 = $('#select_458').find(":selected").attr('price');
                Lamination_458 = (isNaN(Lamination_458)) ? 0 : parseFloat(Lamination_458);
                var Material_457 = $('#select_457').find(":selected").attr('price');
                Material_457 = (isNaN(Material_457)) ? 0 : parseFloat(Material_457);
                var Material_870 = $('#select_870').find(":selected").attr('price');
                Material_870 = (isNaN(Material_870)) ? 0 : parseFloat(Material_870);
                var Holes_459 = $('#select_459').find(":selected").attr('price');
                Holes_459 = (isNaN(Holes_459)) ? 0 : parseFloat(Holes_459);
                var Turnaround_460 = $('#select_460').find(":selected").attr('value');
                Turnaround_460 = (isNaN(Turnaround_460)) ? 0 : parseFloat(Turnaround_460);
                var Color_456 = $('#select_456').find(":selected").attr('value');
                Color_456 = (isNaN(Color_456)) ? 0 : parseFloat(Color_456);
                value_qty = $('#qty').attr('value');
                if((value_qty > 1) || (Color_456 == 836)){
                    $('.Art_1052').addClass('Addactive');
                }else{
                     $('.Art_1052').removeClass('Addactive');
                     $('.Artworks_1053').hide();
                     $("#select_1052 option:selected").removeAttr("selected");
                }
                if(Color_456 == 835){
                    $('.Material-_870').removeClass('Addactive');
                    $('.Material_457').addClass('Addactive');
                }
                if((Turnaround_460 ==848) && (Color_456 == 836)){
                    isTurnaround = 1.7;
                    var isNumber = 2;
                    var isMaterial = Material_870;
                } else if((Turnaround_460 ==848) && (Color_456 == 835)){
                    isTurnaround = 1.7;
                    var isNumber = 1;
                    var isMaterial = Material_457;
                } else if((Turnaround_460 ==847) && (Color_456 == 836)){
                    isTurnaround = 1;
                    var isNumber = 2;
                    var isMaterial = Material_870;
                } else if((Turnaround_460 ==847) && (Color_456 == 835)){
                    isTurnaround = 1;
                    var isNumber = 1;
                    var isMaterial = Material_457;
                } else if((Turnaround_460 ==846) && (Color_456 == 836)){
                    isTurnaround = 1.5;
                    var isNumber = 2;
                    var isMaterial = Material_870;
                } else if((Turnaround_460 ==846) && (Color_456 == 835)){
                    isTurnaround = 1.5;
                    var isNumber = 1;
                    var isMaterial = Material_457;

                } else{
                    isTurnaround = 1;
                    var isNumber = 1;
                    var isMaterial = 0;
                }
                isDefault = false;
                total = ((heso * ((Lamination_458 * isNumber) + isMaterial)) + Holes_459) * isTurnaround;

            }  else if (id == 108) { // Aluminum Sheets
                var Lamination_468 = $('#select_468').find(":selected").attr('value');
                Lamination_468 = (isNaN(Lamination_468)) ? 0 : parseFloat(Lamination_468);

                var Grommets_466 = $('#select_466').find(":selected").attr('price');
                Grommets_466 = (isNaN(Grommets_466)) ? 0 : parseFloat(Grommets_466);
                var Rounded_467  = $('#select_467').find(":selected").attr('price');
                Rounded_467 = (isNaN(Rounded_467)) ? 0 : parseFloat(Rounded_467);

                // var widthVal_969 = $('#options_969_text').attr('value');
                // widthVal_969 = (isNaN(widthVal_969)) ? 0 : parseFloat(widthVal_969);
                // get width

                var widthVal_1140 = $('#options_1140_text').attr('value');
                widthVal_1140 = (isNaN(widthVal_1140)) ? 0 : parseFloat(widthVal_1140);
                console.log(widthVal_1140);
                // get height
                var HeightVal_1141 = $('#options_1141_text').attr('value');
                HeightVal_1141 = (isNaN(HeightVal_1141)) ? 0 : parseFloat(HeightVal_1141);

                // get value size
                var size_1139 = $('#select_1139').find(":selected").attr('value');
                size_1139 = (isNaN(size_1139)) ? 0 : parseFloat(size_1139);

                var Turnaround_469 = $('#select_469').find(":selected").attr('value');
                Turnaround_469 = (isNaN(Turnaround_469)) ? 0 : parseFloat(Turnaround_469);
                var Color_464 = $('#select_464').find(":selected").attr('value');
                Color_464 = (isNaN(Color_464)) ? 0 : parseFloat(Color_464); 
                value_qty = $('#qty').attr('value');
                if((value_qty > 1) || (Color_464 == 851)){
                    $('.Art_919').addClass('Addactive');
                }else{
                     $('.Art_919').removeClass('Addactive');
                     $('.Artworks_920').hide();
                     $("#select_919 option:selected").removeAttr("selected");
                }
                var sizeC = 0;
                var TurnaroundC = 1;
                var addC = 0;
                var hesoC = 1;
                var Lamination_price = 0;
                if(Color_464 == 850){
                    if(size_1139 == 1779){
                        sizeC = 7.50; addC = 0;
                        if(Lamination_468 == 862 ){
                             Lamination_price = 0;  

                        } else if(Lamination_468 == 863){
                            Lamination_price = 1.20; 
                        } else if(Lamination_468 == 864){
                            Lamination_price = 1.21; 
                        } else{
                            Lamination_price = 3.75; 
                        }
                    } else if(size_1139 == 1780){
                        sizeC = 15; addC = 0;
                        if(Lamination_468 == 862 ){
                             Lamination_price = 0;  

                        } else if(Lamination_468 == 863){
                            Lamination_price = 2.40; 
                        } else if(Lamination_468 == 864){
                            Lamination_price = 2.41; 
                        } else{
                            Lamination_price = 7.50; 
                        }
                    } else if(size_1139 == 1781){
                        sizeC = 30; addC = 0;
                        if(Lamination_468 == 862 ){
                             Lamination_price = 0;  

                        } else if(Lamination_468 == 863){
                            Lamination_price = 4.80; 
                        } else if(Lamination_468 == 864){
                            Lamination_price = 4.81; 
                        } else{
                            Lamination_price = 15.00; 
                        }
                    } else{
                        if ((widthVal_1140 < 12) || (widthVal_1140 > 48)) { alert("Please enter a value Width: between 12 and 48."); }
                        if ((HeightVal_1141 < 12) || (HeightVal_1141 > 96)) { alert("Please enter a value Height:  between 12 and 96."); }
                        if(Lamination_468 == 862 ){
                             Lamination_price = 0;  

                        } else if(Lamination_468 == 863){
                            Lamination_price = 0.80; 
                        } else if(Lamination_468 == 864){
                            Lamination_price = 0.81; 
                        } else{
                            Lamination_price = 2.50; 
                        }
                        // tinh custom gia
                        hesoC = (widthVal_1140 * HeightVal_1141)/144; addC = 6;
                        hesoC = (isNaN(hesoC)) ? 0 : parseFloat(hesoC);
      
                        
                    }

                } else if(Color_464 == 851){
                    if(size_1139 == 1779){
                        sizeC = 11.25; addC = 0;
                        if(Lamination_468 == 862 ){
                             Lamination_price = 0;  
                        } else if(Lamination_468 == 863){
                            Lamination_price = 2.40; 
                        } else if(Lamination_468 == 864){
                            Lamination_price = 2.41; 
                        } else{
                            Lamination_price = 7.50; 
                        }
                    } else if(size_1139 == 1780){
                        console.log('dd');
                        sizeC = 22.5; addC = 0;

                        if(Lamination_468 == 862 ){
                             Lamination_price = 0;  

                        } else if(Lamination_468 == 863){
                            Lamination_price = 4.80; 
                        } else if(Lamination_468 == 864){
                            Lamination_price = 4.81; 
                        } else{
                            Lamination_price = 15; 
                        }
                    } else if(size_1139 == 1781){
                        sizeC = 45; addC = 0;
                        if(Lamination_468 == 862 ){
                             Lamination_price = 0;  

                        } else if(Lamination_468 == 863){
                            Lamination_price = 9.60; 
                        } else if(Lamination_468 == 864){
                            Lamination_price = 9.61; 
                        } else{
                            Lamination_price = 30; 
                        }
                    } else{
                        if ((widthVal_1140 < 12) || (widthVal_1140 > 48)) { alert("Please enter a value Width: between 12 and 48."); }
                        if ((HeightVal_1141 < 12) || (HeightVal_1141 > 96)) { alert("Please enter a value Height:  between 12 and 96."); }
                        if(Lamination_468 == 862 ){
                             Lamination_price = 0;  

                        } else if(Lamination_468 == 863){
                            Lamination_price = 0.80 * 2; 
                        } else if(Lamination_468 == 864){
                            Lamination_price = 0.81 * 2; 
                        } else{
                            Lamination_price = 2.50 * 2; 
                        }
                        // tinh custom gia

                        hesoC = (widthVal_1140 * HeightVal_1141)/144; addC = 10;
                         hesoC = (isNaN(hesoC)) ? 0 : parseFloat(hesoC);
                        
                    }
                }
                if(Turnaround_469 == 866){
                    TurnaroundC = 1;
                    
                } else if(Turnaround_469 == 867){
                    TurnaroundC = 1.5;
                } else if(Turnaround_469 == 868){
                    TurnaroundC = 1.75;
                }
                isDefault = false;
                total = hesoC * (sizeC + (addC + Lamination_price) + Grommets_466 + Rounded_467) * TurnaroundC;
                // total = (heso * (6 + Lamination_price) + Grommets_466 + Rounded_467) * 1.75;
                // if((widthVal_818 ==18) && (HeightVal_819 == 12)){
                //     if(Color_464 == 850){
                //         if(Lamination_468 == 865){
                //             Lamination_price = 3.75;
                //         } else if(Lamination_468 == 864){
                //             Lamination_price = 1.21;
                //         } else if(Lamination_468 == 863){
                //             Lamination_price = 1.2;
                //         } else{
                //             Lamination_price = 0;
                //         } 
                //         if(Turnaround_469 == 868){
                //             total = (7.5 + Lamination_price + Grommets_466 + Rounded_467) * 1.75;
                //         }else if(Turnaround_469 == 867){
                //             total = (7.5 + Lamination_price + Grommets_466 + Rounded_467) * 1.5;
                //         }else{
                //             total = 7.5 + Lamination_price + Grommets_466 + Rounded_467;
                //         }    
                //     } else{
                //         if(Lamination_468 == 865){
                //             Lamination_price = 7.5;
                //         } else if(Lamination_468 == 864){
                //             Lamination_price = 2.41;
                //         } else if(Lamination_468 == 863){
                //             Lamination_price = 2.4;
                //         } else{
                //             Lamination_price = 0;
                //         }
                //         if(Turnaround_469 == 868){
                //             total = (11.25 + Lamination_price + Grommets_466 + Rounded_467) * 1.75;
                //         }else if(Turnaround_469 == 867){
                //             total = (11.25 + Lamination_price + Grommets_466 + Rounded_467) * 1.5;
                //         }else{
                //             total = 11.25 + Lamination_price + Grommets_466 + Rounded_467;
                //         } 
                //     }
                    
                // } else if((widthVal_818 ==18) && (HeightVal_819 == 24)){
                //     if(Color_464 == 850){
                //         if(Lamination_468 == 865){
                //             Lamination_price = 7.5;
                //         } else if(Lamination_468 == 864){
                //             Lamination_price = 2.41;
                //         } else if(Lamination_468 == 863){
                //             Lamination_price = 2.4;
                //         } else{
                //             Lamination_price = 0;
                //         } 
                //         if(Turnaround_469 == 868){
                //             total = (15 + Lamination_price + Grommets_466 + Rounded_467) * 1.75;
                //         }else if(Turnaround_469 == 867){
                //             total = (15 + Lamination_price + Grommets_466 + Rounded_467) * 1.5;
                //         }else{
                //             total = 15 + Lamination_price + Grommets_466 + Rounded_467;
                //         }    
                //     } else{
                //         if(Lamination_468 == 865){
                //             Lamination_price = 15;
                //         } else if(Lamination_468 == 864){
                //             Lamination_price = 4.81;
                //         } else if(Lamination_468 == 863){
                //             Lamination_price = 4.8;
                //         } else{
                //             Lamination_price = 0;
                //         }
                //         if(Turnaround_469 == 868){
                //             total = (22.5 + Lamination_price + Grommets_466 + Rounded_467) * 1.75;
                //         }else if(Turnaround_469 == 867){
                //             total = (22.5 + Lamination_price + Grommets_466 + Rounded_467) * 1.5;
                //         }else{
                //             total = 22.5 + Lamination_price + Grommets_466 + Rounded_467;
                //         } 
                //     }
                // } else if((widthVal_818 ==24) && (HeightVal_819 == 36)){
                //     if(Color_464 == 850){
                //         if(Lamination_468 == 865){
                //             Lamination_price = 15;
                //         } else if(Lamination_468 == 864){
                //             Lamination_price = 4.81;
                //         } else if(Lamination_468 == 863){
                //             Lamination_price = 4.8;
                //         } else{
                //             Lamination_price = 0;
                //         } 
                //         if(Turnaround_469 == 868){
                //             total = (30 + Lamination_price + Grommets_466 + Rounded_467) * 1.75;
                //         }else if(Turnaround_469 == 867){
                //             total = (30 + Lamination_price + Grommets_466 + Rounded_467) * 1.5;
                //         }else{
                //             total = 30 + Lamination_price + Grommets_466 + Rounded_467;
                //         }    
                //     } else{
                //         if(Lamination_468 == 865){
                //             Lamination_price = 30;
                //         } else if(Lamination_468 == 864){
                //             Lamination_price = 9.61;
                //         } else if(Lamination_468 == 863){
                //             Lamination_price = 9.6;
                //         } else{
                //             Lamination_price = 0;
                //         }
                //         if(Turnaround_469 == 868){
                //             total = (45 + Lamination_price + Grommets_466 + Rounded_467) * 1.75;
                //         }else if(Turnaround_469 == 867){
                //             total = (45 + Lamination_price + Grommets_466 + Rounded_467) * 1.5;
                //         }else{
                //             total = 45+ Lamination_price + Grommets_466 + Rounded_467;
                //         } 
                //     }
                // } else {  
                //     if(Lamination_468 == 865){
                //             Lamination_price = 2.5;
                //         } else if(Lamination_468 == 864){
                //             Lamination_price = 0.81;
                //         } else if(Lamination_468 == 863){
                //             Lamination_price = 0.8;
                //         } else{
                //             Lamination_price = 0;
                //         }    
                //      if(Turnaround_469 == 868){
                //             total = (heso * (6 + Lamination_price) + Grommets_466 + Rounded_467) * 1.75;
                //         }else if(Turnaround_469 == 867){
                //             total = (heso * (6 + Lamination_price) + Grommets_466 + Rounded_467) * 1.5;
                //         }else{
                //             total = heso * (6 + Lamination_price) + Grommets_466 + Rounded_467;
                //         } 
                // }


            } else if (id == 146) { //  Arrow Spinner Signs
                var Size_973 = $('#select_973').find(":selected").attr('value');
                Size_973 = (isNaN(Size_973)) ? 0 : parseFloat(Size_973);
                var Lamination_974 = $('#select_974').find(":selected").attr('value');
                Lamination_974 = (isNaN(Lamination_974)) ? 0 : parseFloat(Lamination_974);
                var Turnaround_747 = $('#select_747').find(":selected").attr('value');
                Turnaround_747 = (isNaN(Turnaround_747)) ? 0 : parseFloat(Turnaround_747);
                var Color_744 = $('#select_744').find(":selected").attr('value');
                Color_744 = (isNaN(Color_744)) ? 0 : parseFloat(Color_744);
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_1054').addClass('Addactive');
                }else{
                     $('.Art_1054').removeClass('Addactive');
                     $('.Artworks_1055').hide();
                     $("#select_1054 option:selected").removeAttr("selected");
                }
                var coso = 0;
                var cosoL = 0;
                if(Color_744 == 1216){
                    if(Size_973 == 1579){
                        if(Lamination_974 == 1582){
                            if(Turnaround_747 ==  1225){
                                isTurnaround = 1;
                            }else if(Turnaround_747 ==  1226){
                                isTurnaround = 1.7;
                            }else{
                                isTurnaround = 1;
                            }
                            coso =0;
                        }else if(Lamination_974 == 1583){
                            if(Turnaround_747 ==  1225){
                                coso = 4.80; isTurnaround = 1;

                            }else if(Turnaround_747 ==  1226){
                                coso = 4.80; isTurnaround = 1.7;
                            }else{
                                isTurnaround = 1;
                            }

                        }else if(Lamination_974 == 1584){
                            if(Turnaround_747 ==  1225){
                                coso = 4.81; isTurnaround = 1;
                            }else if(Turnaround_747 ==  1226){
                                coso = 4.81; isTurnaround = 1.7;
                            } else{
                                isTurnaround = 1;
                            }
                        }else{
                            if(Turnaround_747 ==  1225){
                                coso = 15; isTurnaround = 1;
                            }else if(Turnaround_747 ==  1226){
                                coso = 18.50; isTurnaround = 1.7;
                            } else{
                                isTurnaround = 1;
                            }
                        }
                        cosoL = 18.50;
                    } else if(Size_973 == 1580){
                        if(Lamination_974 == 1582){
                            if(Turnaround_747 ==  1225){
                                isTurnaround = 1;
                            }else if(Turnaround_747 ==  1226){
                                isTurnaround = 1.7;
                            } else{
                                isTurnaround = 1;
                            }
                            coso = 0; 
                        }else if(Lamination_974 == 1583){
                            if(Turnaround_747 ==  1225){
                                coso = 6.67; isTurnaround = 1;
                            }else if(Turnaround_747 ==  1226){
                                coso = 6.67; isTurnaround = 1.7;
                            } else{
                                isTurnaround = 1;
                            }
                        }else if(Lamination_974 == 1584){
                            if(Turnaround_747 ==  1225){
                                coso = 6.68; isTurnaround = 1;

                            }else if(Turnaround_747 ==  1226){
                                coso = 6.68; isTurnaround = 1.7;
                            }
                        }else{
                            if(Turnaround_747 ==  1225){
                                total =23.75 + 20.83;
                                coso = 20.83; isTurnaround = 1;
                            }else if(Turnaround_747 ==  1226){
                                coso = 20.83; isTurnaround = 1.75;
                            }
                        }
                        cosoL = 23.75;
                    } else if(Size_973 == 1581){
                        if(Lamination_974 == 1582){
                            if(Turnaround_747 ==  1225){
                                isTurnaround = 1;
                            }else if(Turnaround_747 ==  1226){
                                isTurnaround = 1.7;
                            } else{
                                isTurnaround = 1; 
                            }
                            coso = 0;
                        }else if(Lamination_974 == 1583){
                            if(Turnaround_747 ==  1225){
                                coso = 9.60; isTurnaround = 1;

                            }else if(Turnaround_747 ==  1226){
                                coso = 9.60; isTurnaround = 1.7;
                            } else{
                                isTurnaround = 1; coso = 9.60;
                            }
                        }else if(Lamination_974 == 1584){
                            if(Turnaround_747 ==  1225){
                                coso = 9.61; isTurnaround = 1;
                            }else if(Turnaround_747 ==  1226){
                                coso = 9.61; isTurnaround = 1.7;
                            } else{
                                isTurnaround = 1; coso = 9.61;
                            }
                        }else{
                            if(Turnaround_747 ==  1225){
                                coso = 30; isTurnaround = 1;
                            }else if(Turnaround_747 ==  1226){
                                coso = 30; isTurnaround = 1.7;
                            } else{
                                isTurnaround = 1; coso = 30;
                            }
                        }
                        cosoL = 32;
                    } else{
                        total = 0;
                    }
                    total =(cosoL + coso) * isTurnaround;
                } 
                else if(Color_744 == 1217){
                    if(Size_973 == 1579){
                        if(Lamination_974 == 1582){
                            if(Turnaround_747 ==  1225){
                                isTurnaround = 1;
                            }else if(Turnaround_747 ==  1226){
                               isTurnaround = 1.7;
                            } else{
                                isTurnaround = 1;
                            }
                            coso = 0;
                        }else if(Lamination_974 == 1583){
                            if(Turnaround_747 ==  1225){
                                coso = 9.60; isTurnaround = 1;

                            }else if(Turnaround_747 ==  1226){
                                coso = 9.60; isTurnaround = 1.7;
                            } else{
                                isTurnaround = 1; coso = 9.60;
                            }
                        }else if(Lamination_974 == 1584){
                            if(Turnaround_747 ==  1225){
                                total =28+ 9.61;
                                coso = 9.61; isTurnaround = 1;

                            }else if(Turnaround_747 ==  1226){
                                coso = 9.61; isTurnaround = 1.7;
                            } else{
                                isTurnaround = 1; coso = 9.61;
                            }
                        }else{
                            if(Turnaround_747 ==  1225){
                                 isTurnaround = 1; coso = 30;
                            }else if(Turnaround_747 ==  1226){
                                 isTurnaround = 1.7; coso = 30;
                            } else{
                                isTurnaround = 1; coso = 30;
                            }
                        }
                        total =(28 + coso) * isTurnaround;

                    } else if(Size_973 == 1580){
                        if(Lamination_974 == 1582){
                            if(Turnaround_747 ==  1225){
                                isTurnaround = 1;
                            }else if(Turnaround_747 ==  1226){
                                isTurnaround = 1.7;
                            } else{
                                isTurnaround = 1;
                            }
                            coso = 0;
                        }else if(Lamination_974 == 1583){
                            if(Turnaround_747 ==  1225){
                                coso = 13.34; isTurnaround = 1;

                            }else if(Turnaround_747 ==  1226){
                                coso = 13.34; isTurnaround = 1.7;
                            }
                        }else if(Lamination_974 == 1584){
                            if(Turnaround_747 ==  1225){
                                coso = 13.35; isTurnaround = 1;
                            }else if(Turnaround_747 ==  1226){
                                coso = 13.35; isTurnaround = 1.7;
                            } else{
                                coso = 13.34; isTurnaround = 1;
                            }
                        }else{
                            if(Turnaround_747 ==  1225){
                                coso = 41.66; isTurnaround = 1;
                            }else if(Turnaround_747 ==  1226){
                                coso = 41.66; isTurnaround = 1.7;
                            } else{
                                coso = 41.66; isTurnaround = 1;
                            }
                        }
                        total =(37 + coso) * isTurnaround;
                    } else if(Size_973 == 1581){
                        if(Lamination_974 == 1582){
                            if(Turnaround_747 ==  1225){
                                isTurnaround = 1;
                            }else if(Turnaround_747 ==  1226){
                                isTurnaround = 1.7;
                            }
                            coso = 0;
                        }else if(Lamination_974 == 1583){
                            if(Turnaround_747 ==  1225){
                                coso = 19.20; isTurnaround = 1;
                            }else if(Turnaround_747 ==  1226){
                                coso = 19.20; isTurnaround = 1.7;
                            }
                        }else if(Lamination_974 == 1584){
                            if(Turnaround_747 ==  1225){
                                coso = 19.21; isTurnaround = 1;
                            }else if(Turnaround_747 ==  1226){
                                coso = 19.21; isTurnaround = 1.7;
                            }else{
                                coso = 19.21; isTurnaround = 1;
                            }
                        }else{
                            if(Turnaround_747 ==  1225){
                                coso = 60; isTurnaround = 1;
                            }else if(Turnaround_747 ==  1226){
                                coso = 60; isTurnaround = 1.7;
                            }
                        }
                         total =(50 + coso) * isTurnaround;
                    } else{
                        total = 0;
                    }
                }
                else{
                    total =0 ;
                }
                isDefault = false;

            } else if (id == 147) { //  Yard Signs (Coroplast)
                var Stakes_617 = $('#select_617').find(":selected").attr('price');
                Stakes_617 = (isNaN(Stakes_617)) ? 0 : parseFloat(Stakes_617);
                var Grommets_618 = $('#select_618').find(":selected").attr('price');
                Grommets_618 = (isNaN(Grommets_618)) ? 0 : parseFloat(Grommets_618);
                var Turnaround_619 = $('#select_619').find(":selected").attr('value');
                Turnaround_619 = (isNaN(Turnaround_619)) ? 0 : parseFloat(Turnaround_619);
                var Material_615 = $('#select_615').find(":selected").attr('value');
                Material_615 = (isNaN(Material_615)) ? 0 : parseFloat(Material_615);
                var Color_616 = $('#select_616').find(":selected").attr('price');
                Color_616 = (isNaN(Color_616)) ? 0 : parseFloat(Color_616);
                var Color_891 = $('#select_891').find(":selected").attr('price');
                Color_891 = (isNaN(Color_891)) ? 0 : parseFloat(Color_891);
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_927').addClass('Addactive');
                }else{
                     $('.Art_927').removeClass('Addactive');
                     $('.Artworks_928').hide();
                     $("#select_927 option:selected").removeAttr("selected");
                }
                if((Turnaround_619 ==1048) && (Material_615 == 1037)){
                    total = (( heso * Color_891 ) + Stakes_617 + Grommets_618 ) * 1.7;
                } else if((Turnaround_619 ==1048) && (Material_615 == 1036)){
                    total = (( heso * Color_616 ) + Stakes_617 + Grommets_618 ) * 1.7;
                } else if((Turnaround_619 ==1047) && (Material_615 == 1037)){
                    total = ( heso * Color_891 ) + Stakes_617 + Grommets_618 ;
                } 
                else{
                    total = ( heso * Color_616 ) + Stakes_617 + Grommets_618 ;
                }
                isDefault = false;

            } else if (id == 148) { //  Ultra(Gator) Board
                var Lamination_626 = $('#select_626').find(":selected").attr('price');
                Lamination_626 = (isNaN(Lamination_626)) ? 0 : parseFloat(Lamination_626);
                var Grommets_627 = $('#select_627').find(":selected").attr('price');
                Grommets_627 = (isNaN(Grommets_627)) ? 0 : parseFloat(Grommets_627);
                var Material_Single_625 = $('#select_625').find(":selected").attr('price');
                Material_Single_625 = (isNaN(Material_Single_625)) ? 0 : parseFloat(Material_Single_625);
                var Material_Single_value = $('#select_625').find(":selected").attr('value');
                Material_Single_value = (isNaN(Material_Single_value)) ? 0 : parseFloat(Material_Single_value);
                var Material_Double_888 = $('#select_888').find(":selected").attr('price');
                Material_Double_888 = (isNaN(Material_Double_888)) ? 0 : parseFloat(Material_Double_888);
                var Material_Double_value = $('#select_888').find(":selected").attr('value');
                Material_Double_value = (isNaN(Material_Double_value)) ? 0 : parseFloat(Material_Double_value);
                var Color_624 = $('#select_624').find(":selected").attr('value');
                Color_624 = (isNaN(Color_624)) ? 0 : parseFloat(Color_624);
                var Turnaround_628 = $('#select_628').find(":selected").attr('value');
                Turnaround_628 = (isNaN(Turnaround_628)) ? 0 : parseFloat(Turnaround_628);
                value_qty = $('#qty').attr('value');
                if((value_qty > 1) || (Color_624 == 1050)){
                    $('.Art_904').addClass('Addactive');
                }else{
                     $('.Art_904').removeClass('Addactive');
                     $('.Artworks_905').hide();
                     $("#select_904 option:selected").removeAttr("selected");
                }
                if(Color_624 == 1049){
                    $('.Side_625').addClass('Addactive');
                    $('.Side_888').removeClass('Addactive');
                }
                if((Turnaround_628 ==1064) && (Color_624 == 1050)){
                    if(Material_Double_value == 1452){
                        total = heso * ((Lamination_626 * 2) + Material_Double_888)  * 1.7;
                    } else{
                        total = (heso * ((Lamination_626 * 2) + Material_Double_888) + Grommets_627) * 1.7;
                    }

                } else if((Turnaround_628 ==1064) && (Color_624 == 1049)){
                    if(Material_Single_value == 1053){
                        total = heso * (Lamination_626 + Material_Single_625) * 1.7;
                    } else{
                        total = (heso * (Lamination_626 + Material_Single_625) + Grommets_627) * 1.7;
                    }

                } else if((Turnaround_628 ==1063) && (Color_624 == 1050)){
                    if(Material_Double_value == 1452){
                        total = heso * ((Lamination_626 * 2) + Material_Double_888);
                    } else{
                        total = heso * ((Lamination_626 * 2) + Material_Double_888) + Grommets_627;
                    }
                } 
                else{
                    if(Material_Single_value == 1053){
                        total = heso * (Lamination_626 + Material_Single_625);
                    } else{
                        total = heso * (Lamination_626 + Material_Single_625) + Grommets_627;
                    }
                }
                isDefault = false;

            } else if (id == 149) { // Styrene Boards
                var Material_634 = $('#select_634').find(":selected").attr('price');
                Material_634 = (isNaN(Material_634)) ? 0 : parseFloat(Material_634);
                var Lamination_635 = $('#select_635').find(":selected").attr('price');
                Lamination_635 = (isNaN(Lamination_635)) ? 0 : parseFloat(Lamination_635);
                var Grommets_636 = $('#select_636').find(":selected").attr('price');
                Grommets_636 = (isNaN(Grommets_636)) ? 0 : parseFloat(Grommets_636);
                var Rounded_637 = $('#select_637').find(":selected").attr('price');
                Rounded_637 = (isNaN(Rounded_637)) ? 0 : parseFloat(Rounded_637);
                var Turnaround_638 = $('#select_638').find(":selected").attr('value');
                Turnaround_638 = (isNaN(Turnaround_638)) ? 0 : parseFloat(Turnaround_638);
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_1058').addClass('Addactive');
                }else{
                     $('.Art_1058').removeClass('Addactive');
                     $('.Artworks_1059').hide();
                     $("#select_1058 option:selected").removeAttr("selected");
                }
                if(Turnaround_638 ==1079){
                    total = (( heso * (Lamination_635 + Material_634) + Grommets_636) * 1.7) + Rounded_637;
                  
                }
                else{
                    total = heso * (Lamination_635 + Material_634) + Grommets_636 + Rounded_637;
                }
                isDefault = false;

            } else if (id == 150) { //  PVC Sintra Board 
                var Lamination_645 = $('#select_645').find(":selected").attr('price');
                Lamination_645 = (isNaN(Lamination_645)) ? 0 : parseFloat(Lamination_645);
                var Grommets_646 = $('#select_646').find(":selected").attr('price');
                Grommets_646 = (isNaN(Grommets_646)) ? 0 : parseFloat(Grommets_646);
                var Material_Single_644 = $('#select_644').find(":selected").attr('price');
                Material_Single_644 = (isNaN(Material_Single_644)) ? 0 : parseFloat(Material_Single_644);
                var Rounded_647 = $('#select_647').find(":selected").attr('price');
                Rounded_647 = (isNaN(Rounded_647)) ? 0 : parseFloat(Rounded_647);
                var Material_Double_885 = $('#select_885').find(":selected").attr('price');
                Material_Double_885 = (isNaN(Material_Double_885)) ? 0 : parseFloat(Material_Double_885);
                var Color_643 = $('#select_643').find(":selected").attr('value');
                Color_643 = (isNaN(Color_643)) ? 0 : parseFloat(Color_643);
                var Turnaround_648 = $('#select_648').find(":selected").attr('value');
                Turnaround_648 = (isNaN(Turnaround_648)) ? 0 : parseFloat(Turnaround_648);
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_925').addClass('Addactive');
                }else{
                     $('.Art_925').removeClass('Addactive');
                     $('.Artworks_926').hide();
                     $("#select_925 option:selected").removeAttr("selected");
                }
                // get Material- Single Side first
                if(Color_643 == 1080){
                    $('.Side_644').addClass('Addactive');
                    $('.Side_885').removeClass('Addactive');
                }
                if((Turnaround_648 ==1097) && (Color_643 == 1081)){
                    total = ((heso * ((Lamination_645 * 2) + Material_Double_885) + Grommets_646) * 1.7) + Rounded_647;

                } else if((Turnaround_648 ==1097) && (Color_643 == 1080)){
                    total = ((heso * (Lamination_645 + Material_Single_644) + Grommets_646) * 1.7) + Rounded_647;

                } else if((Turnaround_648 ==1096) && (Color_643 == 1081)){
                    total = heso * ((Lamination_645 * 2) + Material_Double_885) + Grommets_646 + Rounded_647;
                } 
                else{
                    total = heso * (Lamination_645 + Material_Single_644) + Grommets_646 + Rounded_647;
                }
                isDefault = false;

            } else if (id == 151) { //  Foam Boards
                var Lamination_655 = $('#select_655').find(":selected").attr('price');
                Lamination_655 = (isNaN(Lamination_655)) ? 0 : parseFloat(Lamination_655);
                var Grommets_656 = $('#select_656').find(":selected").attr('price');
                Grommets_656 = (isNaN(Grommets_656)) ? 0 : parseFloat(Grommets_656);
                var Material_Single_654 = $('#select_654').find(":selected").attr('price');
                Material_Single_654 = (isNaN(Material_Single_654)) ? 0 : parseFloat(Material_Single_654);
                var Material_Double_883 = $('#select_883').find(":selected").attr('price');
                Material_Double_883 = (isNaN(Material_Double_883)) ? 0 : parseFloat(Material_Double_883);
                var Color_653 = $('#select_653').find(":selected").attr('value');
                Color_653 = (isNaN(Color_653)) ? 0 : parseFloat(Color_653);
                var Turnaround_657 = $('#select_657').find(":selected").attr('value');
                Turnaround_657 = (isNaN(Turnaround_657)) ? 0 : parseFloat(Turnaround_657);
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_923').addClass('Addactive');
                }else{
                     $('.Art_923').removeClass('Addactive');
                     $('.Artworks_924').hide();
                     $("#select_923 option:selected").removeAttr("selected");
                }
                if(Color_653 == 1098){
                    $('.Side_654').addClass('Addactive');
                    $('.Side_883').removeClass('Addactive');
                }
                if((Turnaround_657 ==1112) && (Color_653 == 1099)){
                    total = (heso * ((Lamination_655 * 2) + Material_Double_883) + Grommets_656) * 1.7;

                } else if((Turnaround_657 ==1112) && (Color_653 == 1098)){
                    total = (heso * (Lamination_655 + Material_Single_654) + Grommets_656) * 1.7;

                } else if((Turnaround_657 ==1111) && (Color_653 == 1099)){
                    total = heso * ((Lamination_655 * 2) + Material_Double_883) + Grommets_656;
                } 
                else{
                    total = heso * (Lamination_655 + Material_Single_654) + Grommets_656;
                }
                isDefault = false;

            } else if (id == 152) { //  Eagle Board (Eco Board)
                var Lamination_664 = $('#select_664').find(":selected").attr('price');
                Lamination_664 = (isNaN(Lamination_664)) ? 0 : parseFloat(Lamination_664);
                var Material_Single_663 = $('#select_663').find(":selected").attr('price');
                Material_Single_663 = (isNaN(Material_Single_663)) ? 0 : parseFloat(Material_Single_663);
                var Material_Double_881 = $('#select_881').find(":selected").attr('price');
                Material_Double_881 = (isNaN(Material_Double_881)) ? 0 : parseFloat(Material_Double_881);
                var Color_662 = $('#select_662').find(":selected").attr('value');
                Color_662 = (isNaN(Color_662)) ? 0 : parseFloat(Color_662);
                var Turnaround_665 = $('#select_665').find(":selected").attr('value');
                Turnaround_665 = (isNaN(Turnaround_665)) ? 0 : parseFloat(Turnaround_665);
                value_qty = $('#qty').attr('value');
                if((value_qty > 1) || (Color_662 == 1114)){
                    $('.Art_921').addClass('Addactive');
                }else{
                     $('.Art_921').removeClass('Addactive');
                     $('.Artworks_922').hide();
                     $("#select_921 option:selected").removeAttr("selected");
                }
                if(Color_662 == 1113){
                    $('.Side_663').addClass('Addactive');
                    $('.Side_881').removeClass('Addactive');
                }
                if((Turnaround_665 ==1121) && (Color_662 == 1114)){
                    total = (heso * ((Lamination_664 * 2) + Material_Double_881)) * 1.7;

                } else if((Turnaround_665 ==1121) && (Color_662 == 1113)){
                    total = heso * (Lamination_664 + Material_Single_663) * 1.7;

                } else if((Turnaround_665 ==1120) && (Color_662 == 1114)){
                    total = heso * ((Lamination_664 * 2) + Material_Double_881);
                } 
                else if((Turnaround_665 ==1120) && (Color_662 == 1113)){
                    total = heso * (Lamination_664 + Material_Single_663);
                }
                isDefault = false;

            } else if (id == 153) { //  Converd Coated Board
                var Lamination_672 = $('#select_672').find(":selected").attr('price');
                Lamination_672 = (isNaN(Lamination_672)) ? 0 : parseFloat(Lamination_672);
                var Grommets_673 = $('#select_673').find(":selected").attr('price');
                Grommets_673 = (isNaN(Grommets_673)) ? 0 : parseFloat(Grommets_673);

                var Material_671 = $('#select_671').find(":selected").attr('price');
                Material_671 = (isNaN(Material_671)) ? 0 : parseFloat(Material_671);

                var Material_879 = $('#select_879').find(":selected").attr('price');
                Material_879 = (isNaN(Material_879)) ? 0 : parseFloat(Material_879);

                var Color_670 = $('#select_670').find(":selected").attr('value');
                Color_670 = (isNaN(Color_670)) ? 0 : parseFloat(Color_670);
                var Turnaround_674 = $('#select_674').find(":selected").attr('value');
                Turnaround_674 = (isNaN(Turnaround_674)) ? 0 : parseFloat(Turnaround_674);
                value_qty = $('#qty').attr('value');
                if((value_qty > 1) || (Color_670 == 1494)){
                    $('.Art_916').addClass('Addactive');
                }else{
                     $('.Art_916').removeClass('Addactive');
                     $('.Artworks_917').hide();
                     $("#select_916 option:selected").removeAttr("selected");
                }
                if((Turnaround_674 ==1134) && (Color_670 == 1123)){
                    total = (((heso * ((Lamination_672 * 2) + Material_879)) + Grommets_673) * 1.7);

                } else if((Turnaround_674 ==1134) && (Color_670 == 1122)){
                    total = (((heso * (Lamination_672 + Material_671)) + Grommets_673) * 1.7);

                } else if((Turnaround_674 ==1133) && (Color_670 == 1123)){
                    total = (heso * ((Lamination_672 * 2) + Material_879)) + Grommets_673;
                } 
                else{
                    total = (heso * (Lamination_672 + Material_671)) + Grommets_673;
                }
                isDefault = false;

            } else if (id == 110) { //  Mini Banner Stands
                var Material_754 = $('#select_754').find(":selected").attr('price');
                Material_754 = (isNaN(Material_754)) ? 0 : parseFloat(Material_754);

                var Material_892 = $('#select_892').find(":selected").attr('price');
                Material_892 = (isNaN(Material_892)) ? 0 : parseFloat(Material_892);

                var Stand_753 = $('#select_753').find(":selected").attr('value');
                Stand_753 = (isNaN(Stand_753)) ? 0 : parseFloat(Stand_753);
                var Turnaround_756 = $('#select_756').find(":selected").attr('value');
                Turnaround_756 = (isNaN(Turnaround_756)) ? 0 : parseFloat(Turnaround_756);
                if(Stand_753 == 1230){
                    $('.Material_754').addClass('Addactive');
                }else{
                    $('.Material_892').addClass('Addactive');
                }
                if((Turnaround_756 ==1237) && (Stand_753 == 1231)){
                    total = Material_892 * 1.7;

                } else if((Turnaround_756 ==1237) && (Stand_753 == 1230)){
                    total = Material_754 * 1.7;

                } else if((Turnaround_756 ==1236) && (Stand_753 == 1231)){
                    total = Material_892;
                } 
                else{
                    total = Material_754;
                }
                isDefault = false;

            } else if (id == 111) { // Outdoor Banner Stand 
                var Material_price = $('#select_761').find(":selected").attr('price');
                Material_price = (isNaN(Material_price)) ? 0 : parseFloat(Material_price);
                var Material_761 = $('#select_761').find(":selected").attr('value');
                Material_761 = (isNaN(Material_761)) ? 0 : parseFloat(Material_761);
                var Turnaround_765 = $('#select_765').find(":selected").attr('value');
                Turnaround_765 = (isNaN(Turnaround_765)) ? 0 : parseFloat(Turnaround_765);
                if(Material_761 == 1241){
                    $('.Grommets_764').addClass('Addactive');
                    $('.Hemming_763').addClass('Addactive');
                }
                if(Material_761 == 1242){
                    if(Turnaround_765 == 1247){
                        total = Material_price * 1.7;
                    }else{
                        total = Material_price;
                    }
                }  
                else{
                    if(Turnaround_765 == 1247){
                        total = Material_price * 1.7;
                    }else{
                        total = Material_price;
                    }
                }
                isDefault = false;

            }

            else if (id == 112) { //  Outdoor Double Banner Stand
                var Material_770 = $('#select_770').find(":selected").attr('value');
                Material_770 = (isNaN(Material_770)) ? 0 : parseFloat(Material_770);
                var Turnaround_774 = $('#select_774').find(":selected").attr('value');
                Turnaround_774 = (isNaN(Turnaround_774)) ? 0 : parseFloat(Turnaround_774);
                if(Material_770 == 1251){
                    $('.Grommets_773').addClass('Addactive');
                    $('.Hemming_772').addClass('Addactive');
                }else{
                    $('.Hemming_772').removeClass('Addactive');
                }

                if((Turnaround_774 ==1257) && (Material_770 == 1252)){
                    total = (99 * 1.7) - 80;

                } else if((Turnaround_774 ==1257) && (Material_770 == 1251)){
                    total = (125 * 1.7) - 80;

                } else if((Turnaround_774 ==1256) && (Material_770 == 1252)){
                    total = 99;
                } else if((Turnaround_774 ==1256) && (Material_770 == 1251)){
                     total = 125;
                }
                else{
                    total = 0;
                }
                isDefault = false;

            } else if (id == 141) { // X-Frame with Supersmooth

                var Size_963 = $('#select_963').find(":selected").attr('value');
                Size_963 = (isNaN(Size_963)) ? 0 : parseFloat(Size_963);
                var Turnaround_808 = $('#select_808').find(":selected").attr('value');
                Turnaround_808 = (isNaN(Turnaround_808)) ? 0 : parseFloat(Turnaround_808);
                // get width
                var widthVal_965 = $('#options_965_text').attr('value');
                widthVal_965 = (isNaN(widthVal_965)) ? 0 : parseFloat(widthVal_965);

                var HeightVal_966 = $('#options_966_text').attr('value');
                HeightVal_966 = (isNaN(HeightVal_966)) ? 0 : parseFloat(HeightVal_966);
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_1060').addClass('Addactive');
                }else{
                     $('.Art_1060').removeClass('Addactive');
                     $('.Artworks_1061').hide();
                     $("#select_1060 option:selected").removeAttr("selected");
                }
                var Size1 = 0;
                var Coso = 0;
                if(Size_963 == 1569){
                    Size1 = 29.62; 
                    if(Turnaround_808 ==1300){
                        Coso = 15.35;
                    } else{
                        Coso = 0;
                    }
                } else if(Size_963 == 1570){
                    Size1 = 40.40; 
                    if(Turnaround_808 ==1300){
                        Coso = 21.94;
                    }else{
                        Coso = 0;
                    }
                } else if(Size_963 == 1571){
                    Size1 = 60.47;
                    if(Turnaround_808 ==1300){
                        Coso = 31.69;
                    }else{
                        Coso = 0;
                    }
                } else if(Size_963 == 1572){
                  
                    if ((widthVal_965 < 24) || (widthVal_965 > 35)) { alert("Please enter a value Width: between 24 and 33."); }
                    if ((HeightVal_966 < 60) || (HeightVal_966 > 78)) { alert("Please enter a value Height:  between 60 and 78."); }
                    Size1 = 15;
                    if(Turnaround_808 ==1299){
                        
                        Coso = ((widthVal_965 * HeightVal_966)/ 144) * 1.95; 
                        Coso = (isNaN(Coso)) ? 0 : parseFloat(Coso);
                        // if(Coso ==0){
                        //      Size1 = 0;   
                        // }
                    } else{
                        Coso = ((widthVal_965 * HeightVal_966)/ 144) * 3.41; 
                        Coso = (isNaN(Coso)) ? 0 : parseFloat(Coso);
                    }
                } else{
                    if ((widthVal_965 < 24) || (widthVal_965 > 35)) { alert("Please enter a value Width: between 24 and 35."); }
                    if ((HeightVal_966 < 60) || (HeightVal_966 > 78)) { alert("Please enter a value Height:  between 60 and 78."); }
                    Size1 = 23;
                    if(Turnaround_808 ==1299){
                        Coso = ((widthVal_965 * HeightVal_966)/ 144) * 1.95; 
                        Coso = (isNaN(Coso)) ? 0 : parseFloat(Coso);
                    } else{
                         Coso = ((widthVal_965 * HeightVal_966)/ 144) * 3.41;
                         Coso = (isNaN(Coso)) ? 0 : parseFloat(Coso);
                    }
                }
                isDefault = false;  
                total = Size1 + Coso;

            } else if (id == 142) { // X-Frame with Polypropylene (PET)
                var Size_964 = $('#select_964').find(":selected").attr('value');
                Size_964 = (isNaN(Size_964)) ? 0 : parseFloat(Size_964);
                var Turnaround_801 = $('#select_801').find(":selected").attr('value');
                Turnaround_801 = (isNaN(Turnaround_801)) ? 0 : parseFloat(Turnaround_801);
                // get width
                var widthVal_969 = $('#options_969_text').attr('value');
                widthVal_969 = (isNaN(widthVal_969)) ? 0 : parseFloat(widthVal_969);
                console.log(widthVal_969);
                // get height
                var HeightVal_970 = $('#options_970_text').attr('value');
                HeightVal_970 = (isNaN(HeightVal_970)) ? 0 : parseFloat(HeightVal_970);
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_1062').addClass('Addactive');
                }else{
                     $('.Art_1062').removeClass('Addactive');
                     $('.Artworks_1063').hide();
                     $("#select_1062 option:selected").removeAttr("selected");
                }
            
                isDefault = false;
                var Size1 = 0;
                var Coso = 0;
                if(Size_964 == 1574){
                    Size1 = 35.40; 
                    if(Turnaround_801 ==1290){
                        Coso = 19.69;
                    } else{
                        Coso = 0;
                    }
                } else if(Size_964 == 1575){
                    Size1 = 48.65; 
                    if(Turnaround_801 ==1290){
                        Coso = 28.13;
                    }else{
                        Coso = 0;
                    }
                } else if(Size_964 == 1576){
                    Size1 = 72.39;
                    if(Turnaround_801 ==1290){
                        Coso = 40.63;
                    }else{
                        Coso = 0;
                    }
                } else if(Size_964 == 1577){
                  
                    if ((widthVal_969 < 24) || (widthVal_969 > 35)) { alert("Please enter a value Width: between 24 and 33."); }
                    if ((HeightVal_970 < 60) || (HeightVal_970 > 78)) { alert("Please enter a value Height:  between 60 and 78."); }
                    Size1 = 15;
                    if(Turnaround_801 ==1289){
                        Coso = ((widthVal_969 * HeightVal_970)/ 144) * 2.50; 
                        Coso = (isNaN(Coso)) ? 0 : parseFloat(Coso);                        
                    } else{
                        Coso = ((widthVal_969 * HeightVal_970)/ 144) * 4.38; 
                        Coso = (isNaN(Coso)) ? 0 : parseFloat(Coso);
                        // if(Coso ==0){
                        //      Size1 = 0;   
                        // }
                    }
                } else{
                    if ((widthVal_969 < 24) || (widthVal_969 > 35)) { alert("Please enter a value Width: between 24 and 36."); }
                    if ((HeightVal_970 < 60) || (HeightVal_970 > 78)) { alert("Please enter a value Height:  between 60 and 78."); }
                    Size1 = 23;
                    if(Turnaround_801 ==1289){
                        Coso = ((widthVal_969 * HeightVal_970)/ 144) * 2.50;
                        Coso = (isNaN(Coso)) ? 0 : parseFloat(Coso);
                    } else{
                        Coso = ((widthVal_969 * HeightVal_970)/ 144) * 4.38; 
                        Coso = (isNaN(Coso)) ? 0 : parseFloat(Coso);
                    }
                }
                isDefault = false;  
                total = Size1 + Coso;

            } else if (id == 143) { // X-Frame with Banner
                var Size_978 = $('#select_978').find(":selected").attr('value');
                Size_978 = (isNaN(Size_978)) ? 0 : parseFloat(Size_978);
                var Turnaround_794 = $('#select_794').find(":selected").attr('value');
                Turnaround_794 = (isNaN(Turnaround_794)) ? 0 : parseFloat(Turnaround_794);
                // get width
                var widthVal_979 = $('#options_979_text').attr('value');
                widthVal_979 = (isNaN(widthVal_979)) ? 0 : parseFloat(widthVal_979);
                // get height
                var HeightVal_980 = $('#options_980_text').attr('value');
                HeightVal_980 = (isNaN(HeightVal_980)) ? 0 : parseFloat(HeightVal_980);
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_1064').addClass('Addactive');
                }else{
                     $('.Art_1064').removeClass('Addactive');
                     $('.Artworks_1065').hide();
                     $("#select_1064 option:selected").removeAttr("selected");
                }              
                var Size1 = 0;
                var Coso = 0;
                if(Size_978 == 1594){
                    Size1 = 18.50; 
                    if(Turnaround_794 ==1280){
                        Coso = 7.01;
                    } else{
                        Coso = 0;
                    }
                } else if(Size_978 == 1595){
                    Size1 = 24.50; 
                    if(Turnaround_794 ==1290){
                        Coso = 10.01;
                    }else{
                        Coso = 0;
                    }
                } else if(Size_978 == 1596){
                    Size1 = 37.50;
                    if(Turnaround_794 ==1290){
                        Coso = 14.46;
                    }else{
                        Coso = 0;
                    }
                } else if(Size_978 == 1597){
                  
                    if ((widthVal_979 < 24) || (widthVal_979 > 35)) { alert("Please enter a value Width: between 24 and 33."); }
                    if ((HeightVal_980 < 60) || (HeightVal_980 > 78)) { alert("Please enter a value Height:  between 60 and 78."); }
                    Size1 = 15;
                    if(Turnaround_794 ==1279){
                        Coso = ((widthVal_979 * HeightVal_980)/ 144) * 0.89; 
                        Coso = (isNaN(Coso)) ? 0 : parseFloat(Coso);                        
                    } else{
                        Coso = ((widthVal_979 * HeightVal_980)/ 144) * 1.50; 
                        Coso = (isNaN(Coso)) ? 0 : parseFloat(Coso);
                        // if(Coso ==0){
                        //      Size1 = 0;   
                        // }
                    }
                } else{
                    if ((widthVal_979 < 24) || (widthVal_979 > 35)) { alert("Please enter a value Width: between 24 and 36."); }
                    if ((HeightVal_980 < 60) || (HeightVal_980 > 78)) { alert("Please enter a value Height:  between 60 and 78."); }
                    Size1 = 23;
                    if(Turnaround_794 ==1279){
                        Coso = ((widthVal_979 * HeightVal_980)/ 144) * 0.89;
                        Coso = (isNaN(Coso)) ? 0 : parseFloat(Coso);
                    } else{
                        Coso = ((widthVal_979 * HeightVal_980)/ 144) * 1.50; 
                        Coso = (isNaN(Coso)) ? 0 : parseFloat(Coso);
                    }
                }
                isDefault = false;  
                total = Size1 + Coso;

            } else if (id == 144) { // Step and Repeat Banners
                var Turnaround_786 = $('#select_786').find(":selected").attr('value');
                Turnaround_786 = (isNaN(Turnaround_786)) ? 0 : parseFloat(Turnaround_786);
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_1066').addClass('Addactive');
                }else{
                     $('.Art_1066').removeClass('Addactive');
                     $('.Artworks_1067').hide();
                     $("#select_1066 option:selected").removeAttr("selected");
                }
                if(Turnaround_786 ==1266){
                    total = (heso * 0.89) + 153.80;
                }else if(Turnaround_786 ==1267){
                    total = (heso * 1.513)  + 153.80;
                }
                else{
                    total = 0.00;
                }
                isDefault = false;

            } else if (id == 145) { // Retractable Stand
                var Material_976 = $('#select_976').find(":selected").attr('value');
                Material_976 = (isNaN(Material_976)) ? 0 : parseFloat(Material_976);
                var Size_975 = $('#select_975').find(":selected").attr('value');
                Size_975 = (isNaN(Size_975)) ? 0 : parseFloat(Size_975);
                var Turnaround_698 = $('#select_698').find(":selected").attr('value');
                Turnaround_698 = (isNaN(Turnaround_698)) ? 0 : parseFloat(Turnaround_698);
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_1068').addClass('Addactive');
                }else{
                     $('.Art_1068').removeClass('Addactive');
                     $('.Artworks_1069').hide();
                     $("#select_1068 option:selected").removeAttr("selected");
                }
                var Size_price =0;
                var add_heso = 0;
                if(Material_976 ==1590){
                    if(Size_975 == 1586){
                        Size_price = 75;
                        add_heso =  17.5;                
                    } else if(Size_975 == 1587){
                        Size_price = 85; 
                        add_heso =  26;  
                    } else if(Size_975 == 1588){
                        Size_price = 95;
                        add_heso =  27;
                    } else if(Size_975 == 1589){
                        Size_price = 115.00;
                        add_heso =  36; 
                    }
                    if(Turnaround_698 == 1173){
                        total = Size_price + add_heso;
                    } else{
                        total = Size_price;
                    } 
                }else if(Material_976 ==1591){  
                    if(Size_975 == 1586){
                        Size_price = 69.00;
                        add_heso =  14;                 
                    } else if(Size_975 == 1587){
                        Size_price = 79.00; 
                        add_heso =  19.50;
                    } else if(Size_975 == 1588){
                        Size_price = 89.00;
                        add_heso =  20.5; 
                    } else if(Size_975 == 1589){
                        Size_price = 110.00;
                        add_heso =  27.50; 
                    }
                    if(Turnaround_698 == 1173){
                        total = Size_price + add_heso;
                    } else if(Turnaround_698 == 1172){
                        total = Size_price;
                    }else{
                        total = 0;
                    }
                } else if(Material_976 ==1592){  
                    if(Size_975 == 1586){
                        Size_price = 82; 
                        add_heso =  22.5;                 
                    } else if(Size_975 == 1587){
                        Size_price = 95; 
                        add_heso =  32.50; 
                    } else if(Size_975 == 1588){
                        Size_price = 105; 
                        add_heso =  34.5; 
                    } else if(Size_975 == 1589){
                        Size_price = 120; 
                        add_heso =  46; 
                    }
                    if(Turnaround_698 == 1173){
                        total = Size_price + add_heso;
                    } else if(Turnaround_698 == 1172){
                        total = Size_price;
                    } else{
                        total = 0;
                    }
                } else{
                    total = 0;
                }

                isDefault = false;

            } else if (id == 113) { // Custom Sublimation Transfers
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_981').addClass('Addactive');
                }else{
                     $('.Art_981').removeClass('Addactive');
                     $('.Artworks_982').hide();
                     $("#select_981 option:selected").removeAttr("selected");
                }
                var Turnaround_709 = $('#select_709').find(":selected").attr('value');
                Turnaround_709 = (isNaN(Turnaround_709)) ? 0 : parseFloat(Turnaround_709);
                if(Turnaround_709 ==1190){
                    isTurnaround = 1.7;
                } else{
                    isTurnaround = 1;
                }
                isDefault = false;
                total = (heso * 0.79) * isTurnaround;

            } else if (id == 114) { // Flag Banners (Sublimation)
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_983').addClass('Addactive');
                }else{
                     $('.Art_983').removeClass('Addactive');
                     $('.Artworks_984').hide();
                     $("#select_983 option:selected").removeAttr("selected");
                }
                var Material_748 = $('#select_748').find(":selected").attr('value');
                Material_748 = (isNaN(Material_748)) ? 0 : parseFloat(Material_748);

                var Turnaround_750 = $('#select_750').find(":selected").attr('value');
                Turnaround_750 = (isNaN(Turnaround_750)) ? 0 : parseFloat(Turnaround_750);
                if((Turnaround_750 ==1229) && (Material_748 == 1227)){
                    total = 68;
                }
                else{
                    total = 0;
                }
                isDefault = false;

            } else if (id == 115) { // 3M Controltac (IJ 180C) Contour
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_985').addClass('Addactive');
                }else{
                     $('.Art_985').removeClass('Addactive');
                     $('.Artworks_986').hide();
                     $("#select_985 option:selected").removeAttr("selected");
                }
                var Lamination_716_price = $('#select_716').find(":selected").attr('price');
                Lamination_716_price = (isNaN(Lamination_716_price)) ? 0 : parseFloat(Lamination_716_price);

                var Turnaround_717 = $('#select_717').find(":selected").attr('value');
                Turnaround_717 = (isNaN(Turnaround_717)) ? 0 : parseFloat(Turnaround_717);
                if(Turnaround_717 == 1197){
                    isTurnaround =  1.7;
                } else if(Turnaround_717 == 1196){
                    isTurnaround = 1.5;
                } else{
                    isTurnaround = 1;
                }
                isDefault = false;
                total = (heso * (4.40 + Lamination_716_price)) * isTurnaround;

            } else if (id == 116) { // Car Magnets Contour
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_987').addClass('Addactive');
                }else{
                     $('.Art_987').removeClass('Addactive');
                     $('.Artworks_988').hide();
                     $("#select_987 option:selected").removeAttr("selected");
                }
                var Lamination_724 = $('#select_724').find(":selected").attr('price');
                Lamination_724 = (isNaN(Lamination_724)) ? 0 : parseFloat(Lamination_724);
                var Die_725 = $('#select_725').find(":selected").attr('price');
                Die_725 = (isNaN(Die_725)) ? 0 : parseFloat(Die_725);

                var Turnaround_726 = $('#select_726').find(":selected").attr('value');
                Turnaround_726 = (isNaN(Turnaround_726)) ? 0 : parseFloat(Turnaround_726);
                if(Turnaround_726 == 1207){
                    isTurnaround = 1.7;
                } else if(Turnaround_726 == 1205){
                    isTurnaround = 1.5;
                } else{
                    isTurnaround = 1;
                }
                isDefault = false;
                 total = (heso * (Die_725 + Lamination_724)) * isTurnaround;

            } else if (id == 117) { // Floor Graphics – Contour
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_989').addClass('Addactive');
                }else{
                     $('.Art_989').removeClass('Addactive');
                     $('.Artworks_990').hide();
                     $("#select_989 option:selected").removeAttr("selected");
                }
                var Turnaround_735 = $('#select_735').find(":selected").attr('value');
                Turnaround_735 = (isNaN(Turnaround_735)) ? 0 : parseFloat(Turnaround_735);
                if(Turnaround_735 == 1214){
                    isTurnaround =  1.7;
                } else if(Turnaround_735 == 1212){
                    isTurnaround =  1.5;
                } else{
                    isTurnaround = 1;
                }
                isDefault = false;
                total = (heso * (5.88 + 0)) * isTurnaround;

            } else if (id == 133) { // Yard Signs (Coroplast) Contour Cut             
                var Color_547 = $('#select_547').find(":selected").attr('value');
                Color_547 = (isNaN(Color_547)) ? 0 : parseFloat(Color_547);
                var Stakes_549 = $('#select_549').find(":selected").attr('price');
                Stakes_549 = (isNaN(Stakes_549)) ? 0 : parseFloat(Stakes_549);
                var Material_548 = $('#select_548').find(":selected").attr('value');
                Material_548 = (isNaN(Material_548)) ? 0 : parseFloat(Material_548);
                var Turnaround_552 = $('#select_552').find(":selected").attr('value');
                Turnaround_552 = (isNaN(Turnaround_552)) ? 0 : parseFloat(Turnaround_552);
                value_qty = $('#qty').attr('value');
                if((value_qty > 1) || (Color_547 == 940)){
                    $('.Art_959').addClass('Addactive');
                }else{
                     $('.Art_959').removeClass('Addactive');
                     $('.Artworks_960').hide();
                     $("#select_959 option:selected").removeAttr("selected");
                }
                // var add_heso = 0;
                var Color_price = 0;
                var Die_price = 0;
                if(Material_548 ==941){
                    if(Color_547 == 939){
                        Color_price = 1.25;
                    } else if(Color_547 == 940){
                        Color_price = 1.55;
                    } else{
                        Color_price = 0;
                    }
                    Die_price = 1.89;

                } else if(Material_548 ==942){  
                    if(Color_547 == 939){
                        Color_price = 2.25;
                    } else if(Color_547 == 940){
                        Color_price = 2.55;
                    } else{
                        Color_price = 0;
                    }
                    Die_price = 1.99;
                } else{
                   Color_price = 0;
                   Die_price = 0;
                }
                if(Turnaround_552 == 949){
                    isTurnaround = 1.5; 
                } else if(Turnaround_552 == 951){
                    isTurnaround =  1.7; 
                } else{
                    total = 1;
                }
                isDefault = false;
                total = ((heso * (Color_price + Die_price)) + Stakes_549) * isTurnaround;

            } else if (id == 134) { // Ultra(Gator) Board Contour
                var Lamination_559 = $('#select_559').find(":selected").attr('price');
                Lamination_559 = (isNaN(Lamination_559)) ? 0 : parseFloat(Lamination_559);           
                var Color_557 = $('#select_557').find(":selected").attr('value');
                Color_557 = (isNaN(Color_557)) ? 0 : parseFloat(Color_557);

                var Material_Single_558 = $('#select_558').find(":selected").attr('value');
                Material_Single_558 = (isNaN(Material_Single_558)) ? 0 : parseFloat(Material_Single_558);

                var Material_Double_938 = $('#select_938').find(":selected").attr('value');
                Material_Double_938 = (isNaN(Material_Double_938)) ? 0 : parseFloat(Material_Double_938);

                var Turnaround_562 = $('#select_562').find(":selected").attr('value');
                Turnaround_562 = (isNaN(Turnaround_562)) ? 0 : parseFloat(Turnaround_562);
                value_qty = $('#qty').attr('value');
                if((value_qty > 1) || (Color_557 == 953)){
                    $('.Art_941').addClass('Addactive');
                }else{
                     $('.Art_941').removeClass('Addactive');
                     $('.Artworks_942').hide();
                     $("#select_941 option:selected").removeAttr("selected");
                }
                if((Material_Single_558 == 955) || (Material_Single_558 == 957) || (Material_Double_938 == 1535)){
                    $('.Advised_1070').addClass('Addactive');
                }else{
                     $('.Advised_1070').removeClass('Addactive');
                }
                // var add_heso = 0;
                var Material_Single_price = 0;
                var Material_Double_price = 0;
                if(Color_557 == 952){
                    if(Material_Single_558 == 954){
                        Material_Single_price = 3.50;
                    } else if(Material_Single_558 == 955){
                        Material_Single_price = 3.80;
                    } else if(Material_Single_558 == 956){
                        Material_Single_price = 5.50;
                    } else if(Material_Single_558 == 957){
                        Material_Single_price = 6.00;
                    }else{
                        Material_Single_price = 0;
                    }
                    if(Turnaround_562 == 965){
                        isTurnaround =  1.5; 
                    } else if(Turnaround_562 == 967){
                        isTurnaround =  1.7; 
                    } else{
                        isTurnaround = 1;
                    }
                    total = (heso * (Lamination_559 + 1.99 + Material_Single_price)) * isTurnaround; 
                } else if(Color_557 ==953){  
                    if(Material_Double_938 == 1534){
                        Material_Double_price = 4.90;
                    } else if(Material_Double_938 == 1535){
                        Material_Double_price = 5.20;
                    } else if(Material_Double_938 == 1536){
                        Material_Double_price = 7.70;
                    }else{
                        Material_Double_price = 0;
                    }
                    if(Turnaround_562 == 965){
                        isTurnaround =  1.5; 
                    } else if(Turnaround_562 == 967){
                        isTurnaround =  1.7; 
                    } else{
                        isTurnaround = 1;
                    }
                    total = (heso * (Lamination_559 + 1.99 + Material_Double_price)) * isTurnaround; 
                } else{
                   total = 0;
                }
                isDefault = false;

            } else if (id == 135) { // Styrene Boards Contour
                var Material_568 = $('#select_568').find(":selected").attr('price');
                Material_568 = (isNaN(Material_568)) ? 0 : parseFloat(Material_568);
                var Lamination_569 = $('#select_569').find(":selected").attr('price');
                Lamination_569 = (isNaN(Lamination_569)) ? 0 : parseFloat(Lamination_569);
                var Grommets_570 = $('#select_570').find(":selected").attr('price');
                Grommets_570 = (isNaN(Grommets_570)) ? 0 : parseFloat(Grommets_570);
                var Turnaround_572 = $('#select_572').find(":selected").attr('value');
                Turnaround_572 = (isNaN(Turnaround_572)) ? 0 : parseFloat(Turnaround_572);
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_995').addClass('Addactive');
                }else{
                     $('.Art_995').removeClass('Addactive');
                     $('.Artworks_996').hide();
                     $("#select_995 option:selected").removeAttr("selected");
                }

                if(Turnaround_572 ==981){
                    isTurnaround =  1.5;
                } else if(Turnaround_572 ==982){
                    isTurnaround =  1.7;
                }
                else{
                    isTurnaround = 1;
                }
                isDefault = false;
                total = ((heso * (Lamination_569 + Material_568)) + Grommets_570) * isTurnaround;

            } else if (id == 136) { // PVC Sintra Board Contour
                var Material_578 = $('#select_578').find(":selected").attr('value');
                Material_578 = (isNaN(Material_578)) ? 0 : parseFloat(Material_578);

                var Color_577 = $('#select_577').find(":selected").attr('value');
                Color_577 = (isNaN(Color_577)) ? 0 : parseFloat(Color_577);

                var Lamination_579 = $('#select_579').find(":selected").attr('price');
                Lamination_579 = (isNaN(Lamination_579)) ? 0 : parseFloat(Lamination_579);


                var Turnaround_582 = $('#select_582').find(":selected").attr('value');
                Turnaround_582 = (isNaN(Turnaround_582)) ? 0 : parseFloat(Turnaround_582);
                value_qty = $('#qty').attr('value');
                if((value_qty > 1) || (Color_577 == 984)){
                    $('.Art_934').addClass('Addactive');
                }else{
                     $('.Art_934').removeClass('Addactive');
                     $('.Artworks_935').hide();
                     $("#select_934 option:selected").removeAttr("selected");
                }
                var Material_Single_price = 0;
                var Material_Double_price = 0;
                var Die_cut = 0;
                if(Color_577 == 983){
                    if(Material_578 == 985){
                        Material_Single_price = 2.49;
                        Die_cut = 1.89;
                    } else if(Material_578 == 986){
                        Material_Single_price = 2.99;
                        Die_cut = 1.89;
                    } else if(Material_578 == 987){
                        Material_Single_price = 4.25;
                        Die_cut = 1.99;
                    } else if(Material_578 == 988){
                        Material_Single_price = 6.50;
                        Die_cut = 1.99;
                    }else{
                        Material_Single_price = 0;
                        Die_cut = 0;
                    }
                    if(Turnaround_582 == 996){
                        isTurnaround =  1.5; 
                    } else if(Turnaround_582 == 998){
                        isTurnaround = 1.7; 
                    } else{
                        isTurnaround = 1;
                    }
                    total = (heso * (Lamination_579 + Die_cut + Material_Single_price)) * isTurnaround; 
                } else if(Color_577 ==984){  
                    if(Material_578 == 985){
                        Material_Double_price = 3.50;
                        Die_cut = 1.89;
                    } else if(Material_578 == 986){
                        Material_Double_price = 3.99;
                        Die_cut = 1.89;
                    } else if(Material_578 == 987){
                        Material_Double_price = 5.95;
                        Die_cut = 1.99;
                    } else if(Material_578 == 988){
                        Material_Double_price = 9.00;
                        Die_cut = 1.99;
                    } else{
                        Material_Double_price = 0;
                    }
                    if(Turnaround_582 == 996){
                        isTurnaround =  1.5; 
                    } else if(Turnaround_582 == 997){
                        isTurnaround = 1;
                    } else if(Turnaround_582 == 998){
                        isTurnaround =  1.7; 
                    } else{
                        isTurnaround = 1;
                    }
                    total = (heso * (Lamination_579 + Die_cut + Material_Double_price)) * isTurnaround; 
                } else{
                   total = 0;
                }
                isDefault = false;

            } else if (id == 137) { // Foam Boards- Contour
                var Material_Single_588 = $('#select_588').find(":selected").attr('value');
                Material_Single_588 = (isNaN(Material_Single_588)) ? 0 : parseFloat(Material_Single_588);
                var Material_Double_955 = $('#select_955').find(":selected").attr('value');
                Material_Double_955 = (isNaN(Material_Double_955)) ? 0 : parseFloat(Material_Double_955);

                var Color_587 = $('#select_587').find(":selected").attr('value');
                Color_587 = (isNaN(Color_587)) ? 0 : parseFloat(Color_587);

                var Lamination_589 = $('#select_589').find(":selected").attr('price');
                Lamination_589 = (isNaN(Lamination_589)) ? 0 : parseFloat(Lamination_589);


                var Turnaround_592 = $('#select_592').find(":selected").attr('value');
                Turnaround_592 = (isNaN(Turnaround_592)) ? 0 : parseFloat(Turnaround_592);
                value_qty = $('#qty').attr('value');
                if((value_qty > 1) || (Color_587 == 1000)){
                    $('.Art_929').addClass('Addactive');
                }else{
                     $('.Art_929').removeClass('Addactive');
                     $('.Artworks_930').hide();
                     $("#select_929 option:selected").removeAttr("selected");
                }
                var Material_Single_price = 0;
                var Material_Double_price = 0;
                var Die_cut = 0;
                if(Color_587 == 999){
                    if(Material_Single_588 == 1001){
                        Material_Single_price = 2.49;
                        Die_cut = 1.89;
                    } else if(Material_Single_588 == 1002){
                        Material_Single_price = 4;
                        Die_cut = 1.99;
                    } else if(Material_Single_588 == 1003){
                        Material_Single_price = 4.50;
                        Die_cut = 1.99;
                    } else{
                        Material_Single_price = 0;
                        Die_cut = 0;
                    }
                    if(Turnaround_592 == 1011){
                        total = (heso * (Lamination_589 + Die_cut + Material_Single_price)) * 1.5; 
                    } else if(Turnaround_592 == 1012){
                        total = heso * (Lamination_589 + Die_cut + Material_Single_price); 
                    } else if(Turnaround_592 == 1013){
                        total = (heso * (Lamination_589 + Die_cut + Material_Single_price)) * 1.7; 
                    } else{
                        total = 0;
                    }
                } else if(Color_587 ==1000){  
                    if(Material_Double_955 == 1556){
                        Material_Double_price = 3.30;
                        Die_cut = 1.89;
                    } else if(Material_Double_955 == 1557){
                        Material_Double_price = 5.40;
                        Die_cut = 1.99;
                    } else{
                        Material_Double_price = 0;
                    }
                    if(Turnaround_592 == 1011){
                        total = (heso * (Lamination_589 + Die_cut + Material_Double_price)) * 1.5; 
                    } else if(Turnaround_592 == 1012){
                        total = heso * (Lamination_589 + Die_cut + Material_Double_price); 
                    } else if(Turnaround_592 == 1013){
                        total = (heso * (Lamination_589 + Die_cut + Material_Double_price)) * 1.7; 
                    } else{
                        total = 0;
                    }
                } else{
                   total = 0;
                }
                isDefault = false;

            } else if (id == 138) { // Wall Vinyl Decals Contour
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_997').addClass('Addactive');
                }else{
                     $('.Art_997').removeClass('Addactive');
                     $('.Artworks_998').hide();
                     $("#select_997 option:selected").removeAttr("selected");
                }
                var Material_597 = $('#select_597').find(":selected").attr('price');
                Material_597 = (isNaN(Material_597)) ? 0 : parseFloat(Material_597);
                var Lamination_599 = $('#select_599').find(":selected").attr('price');
                Lamination_599 = (isNaN(Lamination_599)) ? 0 : parseFloat(Lamination_599);

                var Turnaround_601 = $('#select_601').find(":selected").attr('value');
                Turnaround_601 = (isNaN(Turnaround_601)) ? 0 : parseFloat(Turnaround_601);
                if(Turnaround_601 == 1021){
                    total = (heso * (Material_597 + Lamination_599)) * 1.5;
                } else if(Turnaround_601 == 1022){
                    total = heso * (Material_597 + Lamination_599);
                } else if(Turnaround_601 == 1023){
                    total = (heso * (Material_597 + Lamination_599)) * 2;
                } else{
                    total = 0;
                }
                isDefault = false;

            } else if (id == 139) { // Vinyl Stickers (Window Decal) Contour
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_999').addClass('Addactive');
                }else{
                     $('.Art_999').removeClass('Addactive');
                     $('.Artworks_1000').hide();
                     $("#select_999 option:selected").removeAttr("selected");
                }
                var Material_606 = $('#select_606').find(":selected").attr('price');
                Material_606 = (isNaN(Material_606)) ? 0 : parseFloat(Material_606);
                var Lamination_609 = $('#select_609').find(":selected").attr('price');
                Lamination_609 = (isNaN(Lamination_609)) ? 0 : parseFloat(Lamination_609);

                var Turnaround_610 = $('#select_610').find(":selected").attr('value');
                Turnaround_610 = (isNaN(Turnaround_610)) ? 0 : parseFloat(Turnaround_610);
                if(Turnaround_610 == 1033){
                    isTurnaround = 1;
                } else if(Turnaround_610 == 1034){
                    isTurnaround =  1.5;
                } else if(Turnaround_610 == 1035){
                    isTurnaround = 1.7;
                } else{
                    isTurnaround = 1;
                }
                isDefault = false;
                total = (heso * (Material_606 + Lamination_609)) * isTurnaround;

            } else if (id == 140) { // Static Clings (Window Clings) Contour
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_1001').addClass('Addactive');
                }else{
                     $('.Art_1001').removeClass('Addactive');
                     $('.Artworks_1002').hide();
                     $("#select_1001 option:selected").removeAttr("selected");
                }
                var Material_539 = $('#select_539').find(":selected").attr('price');
                Material_539 = (isNaN(Material_539)) ? 0 : parseFloat(Material_539);

                var Turnaround_542 = $('#select_542').find(":selected").attr('value');
                Turnaround_542 = (isNaN(Turnaround_542)) ? 0 : parseFloat(Turnaround_542);
                if(Turnaround_542 == 936){
                    total = heso * Material_539;
                } else if(Turnaround_542 == 937){
                    total = heso * Material_539 * 1.5;
                } else if(Turnaround_542 == 938){
                    total = heso * Material_539  * 1.7;
                } else{
                    total = 0;
                }
                isDefault = false;

            } else if (id == 119) { // Retractable Stand (stand ONLY)
                value_qty = $('#qty').attr('value');
                if(value_qty > 1){
                    $('.Art_1004').addClass('Addactive');
                }else{
                     $('.Art_1004').removeClass('Addactive');
                     $('.Artworks_1005').hide();
                     $("#select_1004 option:selected").removeAttr("selected");
                }
                var Size_699 = $('#select_699').find(":selected").attr('price');
                Size_699 = (isNaN(Size_699)) ? 0 : parseFloat(Size_699);
                total = Size_699;
                isDefault = false;

            }

            // Cong thuc binh thuong
            if (isDefault) {
                var ops = $('.changeSelectOp > select');
                $.each(ops, function(i, seclect){
                    var p = $(seclect).find(":selected").attr('price');
                    p = (p) ? parseFloat(p) : 0;
                    pricePerUnit += p;
                });
                total = pricePerUnit + price;
            }


            // tinh discount 1-5 %
            var qty = parseInt($('#qty').attr('value'));  
            qty = (qty < 0) ? 0 : qty;

            // discountCustom = total * Ptram/100;           
            // discountCustom = Number(Math.round(discountCustom * 100) / 100);
            // var totalDiscount = total - discountCustom;
            // End cach cu

     
            // Get Discount 
            var rateDiscount = getDiscountRate(qty * area);
            // console.log(rateDiscount);
            discountCustom =  (total * rateDiscount / 100) * qty;
            discountCustom = Number(Math.round(discountCustom * 100) / 100);

            

            // var subTotal = total * qty; 

            // Check 8 USD
            if (total > 0 && id != 109) {   
                     
                if ( (total * qty) < 8 ) {
                    var a = 8.0 / qty; 
                    var b = a.toString().split("."); 
                    var x =  (b.length == 2) ? b[1].length : 0;
                    if (x > 2) {
                        a = parseInt(a * 100) / 100 + 0.01;
                    }
                    total = a;
                } 
            }

            var subTotal = Number(Math.round(total * 100) / 100) * qty; 

            totalDiscount = subTotal - subTotal * rateDiscount / 100;

            // Tong ket gia            
            $('#pricePerUnit').text('$' + total.toFixed(2));
            $('#subTotalPrice').text('$' + subTotal.toFixed(2));
            
            $('#ptram').text(rateDiscount + '%');
            $('#discountCustom').text('$' + discountCustom.toFixed(2));
            $('#totalDiscount').text('$' + totalDiscount.toFixed(2));
            if(discountCustom > 0){
                $('.Discount-price').addClass('hasDiscount');
                $('.noDiscount').removeClass('hasDiscount');
            }else{
                $('.Discount-price').removeClass('hasDiscount');
                $('.noDiscount').addClass('hasDiscount');
            }
        }

        $('.changeSelectOp > select').change(function () {
            showFinalPrice();
        });
        // REQUEST: X-Frame with Polypropylene (PET)
        $('#options_969_text').change(function () {
            showFinalPrice();
        });
        $('#options_970_text').change(function () {     
            showFinalPrice(); 
        });
        // REQUEST: Aluminum Sheets
        $('#options_1140_text').change(function () {
            showFinalPrice();
        });
        $('#options_1141_text').change(function () {     
            showFinalPrice(); 
        });

        // REQUEST: X-Frame with Banner
        $('#options_979_text').change(function () {
            showFinalPrice();
        });
        $('#options_980_text').change(function () {     
            showFinalPrice(); 
        });

        $('#options_965_text').change(function () {
            showFinalPrice();
        });
        $('#options_966_text').change(function () {     
            showFinalPrice(); 
        });
        
        showFinalPrice();

        $('#qty').change(function () {     
            showFinalPrice(); 
        });

    });


</script>