
<div class="button-to-top">
    <a href="#"><img src="/pub/media/images/button-to-top.png"></a>
</div>

<div class="clearfix pad40"></div>


<div id="tradeFooter">
    <div class="container">
        <div class="footer-content row" style="padding: 20px 0 10px 0">
            <div class="col-xs-12 col-sm-12">
                <div class="footer-header">
                    <p>ABOUT US</p>
                    <img src="/pub/media/images/icon/footer-line.png">
                </div>

                <div class="row">
                    <div class="col-xs-12 col-sm-3">
                        <div class="footer-logo">
                            <img src="/pub/media/images/icon/logo.png" />
                        </div>
                        <div class="footer-detail">Trade Only Banner & Sign</div>
                    </div>

                    <div class="col-xs-12 col-sm-offset-1 col-sm-8">
                        <div class="row">
                            <div class="col-xs-12 col-sm-6">
                                <div class="footer-detail">
                                    <img src="/pub/media/images/icon/icon-footer-home.png">
                                    6012 Clara St. Bell Gardens, CA 90201
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-6">
                                <div class="footer-detail">
                                    <img src="/pub/media/images/icon/icon-footer-phone.png">
                                    1-888-900-6539
                                </div>
                            </div>

                            <div class="clearfix"></div>
                       
                            <div class="col-xs-12 col-sm-6">
                                <div class="footer-detail">
                                    <img src="/pub/media/images/icon/icon-footer-email.png">
                                    info@tradebanner.com
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-6">
                                <div class="footer-detail">
                                    <img src="/pub/media/images/icon/icon-footer-clock.png">
                                    M-F: 8:00AM-5:00PM PST
                                </div>
                            </div>
                        </div>                          
                        
                    </div>
                </div>  
            </div>


        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            <div class="copyright-text">
                All rights reserved 2019, Tradebanner.com
            </div>
        </div>
    </div>
</div>
<div id="popup-mpdal" style="display:none;">
    <div  class="text-popup">
        <span class="first-content">We cover with exactly same turnaround and shipping speed as ordered</span>
        <span class="second-content">Need extra rush shipping customer cover that</span>
    </div>
</div> 

<script type="text/javascript">
    require(['jquery', 'Magento_Ui/js/modal/modal'],function($, modal) {
           $(document).ready(function($) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: '',
                buttons: [{
                    text: $.mage.__('Ok'),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };
            var popup = modal(options, $('#popup-mpdal'));
            setTimeout(
            secondFunction =  function() 
            { 
                if($('#checkout-shipping-method-load tbody tr label').prop('id')=='label_method_freeshipping_freeshipping'){
                    $('#checkout-shipping-method-load tbody tr').click(function() {

                        var nth_child = $(this).parent().children().length - $(this).nextAll().length;
                        if(nth_child  > 4){
                            
                            $("#popup-mpdal").modal("openModal");
                        }
                    });
                }else{ 
                    $('#checkout-shipping-method-load tbody tr').click(function() {

                        var nth_child = $(this).parent().children().length - $(this).nextAll().length;
                        if(nth_child  > 3){
                            
                            $("#popup-mpdal").modal("openModal");
                        }
                    });
                }
            }, 4000);

            $("#select_1698 option[value='2923']").each(function() {
                    $(this).remove();
                });

        });
    });
</script>

<style type="text/css">
    
.Notice_2112,.Notice_2113,.Notice_2114,.Notice_2115,.Notice_2116,.Notice_2117,.Notice_2118,.Notice_2119,.Notice_2120,.Notice_2121{
    display: none;
}
#options-2112-list .admin__field-option:nth-child(1),
#options-2113-list .admin__field-option:nth-child(1),
#options-2114-list .admin__field-option:nth-child(1),
#options-2115-list .admin__field-option:nth-child(1),
#options-2116-list .admin__field-option:nth-child(1),
#options-2117-list .admin__field-option:nth-child(1),
#options-2118-list .admin__field-option:nth-child(1),
#options-2119-list .admin__field-option:nth-child(1),
#options-2120-list .admin__field-option:nth-child(1),
#options-2121-list .admin__field-option:nth-child(1)
{
    display: none;
}

</style>