<?php
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$newsCat = $_objectManager->create('Magefan\Blog\Model\Category')->load('news');
$news = $_objectManager->create('Magefan\Blog\Model\ResourceModel\Post\Collection')
    ->addActiveFilter()->addCategoryFilter($newsCat)->setOrder('creation_time', 'DESC')->setPageSize(6);
?>

<div class="button-to-top">
    <a href="#"><img src="/pub/media/images/button-to-top.png"></a>
</div>

<div id="tradeFooter">
    <div class="container">
        <div class="footer-content row">
            <div class="col-xs-12 col-sm-4">
                <div class="footer-header">
                    <p>ABOUT US</p>
                    <img src="/pub/media/images/icon/footer-line.png">
                </div>
                <div class="footer-logo">
                    <img src="/pub/media/images/icon/logo.png" />
                </div>
                <div class="footer-detail">Trade Only Banner & Sign</div>
                <div class="footer-detail">
                    <img src="/pub/media/images/icon/icon-footer-home.png">
                    6012 Clara St. Bell Gardens, CA 90201</div>
                <div class="footer-detail">
                    <img src="/pub/media/images/icon/icon-footer-phone.png">
                    1-888-900-6539
                </div>
                <div class="footer-detail">
                    <img src="/pub/media/images/icon/icon-footer-fax.png">
                    1-562-381-2114
                </div>
                <div class="footer-detail">
                    <img src="/pub/media/images/icon/icon-footer-email.png">
                    info@tradebanner.com
                </div>
                <div class="footer-detail">
                    <img src="/pub/media/images/icon/icon-footer-clock.png">
                    M-F: 8:30AM-5:00PM PST
                </div>
            </div>
            <div class="col-xs-12 col-sm-4">
                <div class="footer-header">
                    <p>RECENT SPECIALS</p>
                    <img src="/pub/media/images/icon/footer-line.png">
                </div>
                <?php foreach($news as $item) { ?>
                <div class="footer-detail">
                    <a href="<?= $item->getPostUrl() ?>"><p><?= $item->getTitle() ?></p></a>
                    <?php
                    $d = "";
                    if (!is_null($item->getCreationTime())) {
                        $date = new DateTime($item->getCreationTime());
                        $d = $date->format('F d, Y');
                    }
                    echo $d;
                    ?>
                </div>
                <?php } ?>


<!--                <div class="footer-detail">-->
<!--                    <p>New File Upload Server</p>-->
<!--                    February 27, 2015</div>-->
            </div>
            <div class="col-xs-12 col-sm-4">
                <div class="footer-header">
                    <p>TOP RATED PRODUCTS</p>
                    <img src="/pub/media/images/icon/footer-line.png">
                </div>
                <div class="footer-detail rated">
                    <p>13oz Vinyl Banner</p>
                    <img src="/pub/media/images/icon/icon-footer-star.png">
                    <img src="/pub/media/images/icon/icon-footer-star.png">
                    <img src="/pub/media/images/icon/icon-footer-star.png">
                    <img src="/pub/media/images/icon/icon-footer-star.png">
                    <img src="/pub/media/images/icon/icon-footer-star.png"></div>
                <div class="footer-detail rated">
                    <p>3M IJ35 Adhesive Vinyl</p>
                    <img src="/pub/media/images/icon/icon-footer-star.png">
                    <img src="/pub/media/images/icon/icon-footer-star.png">
                    <img src="/pub/media/images/icon/icon-footer-star.png">
                    <img src="/pub/media/images/icon/icon-footer-star.png"></div>
                <div class="footer-detail rated">
                    <p>Double Retractable Stand</p>
                    <img src="/pub/media/images/icon/icon-footer-star.png">
                    <img src="/pub/media/images/icon/icon-footer-star.png">
                    <img src="/pub/media/images/icon/icon-footer-star.png">
                    <img src="/pub/media/images/icon/icon-footer-star.png"></div>
                <div class="footer-detail rated">
                    <p>H-Stakes</p>
                    <img src="/pub/media/images/icon/icon-footer-star.png">
                    <img src="/pub/media/images/icon/icon-footer-star.png"></div>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            <div class="copyright-text">
                All rights reserved 2016, Tradebanner.com
            </div>
        </div>
    </div>
</div>