<?php
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface');
$currentStore = $storeManager->getStore();
$baseUrl = $currentStore->getBaseUrl();
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$linkUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_LINK);

$banners = $_objectManager->get('Sahy\Banner\Block\Frontend\Banners');
$collection = $banners->getAllBannerByType($banners::TYPE_HOME_BANNER);
?>

<?php if (isset($collection) && count($collection) > 0) { ?>
    <?php $size = count($collection); ?>
    <div class="clearfix"></div>
    <div id="bannerHS" class="carousel slide" data-ride="carousel" data-interval="false">
        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <?php $i = 1; ?>
            <?php foreach($collection as $bn) { ?>
                <div class="item <?= ($i == 1) ? 'active':'' ?>">
                    <img src="<?= $mediaUrl . $bn['image']?>" />
                    <div class="innerHS">
                        <p class="titHS"><?= ($bn['name'] == '.') ? "" :  $bn['name'] ?></p>
                        <p class="sumHS"><?= $bn['details'] ?></p>
                        <?php if ($bn['link'] != '') { ?>
                            <a href="<?=$bn['link']?>" class="clickHereHS">CLICK HERE</a>
                        <?php } ?>
                    </div>
                </div>
                <?php $i++; ?>
            <?php } ?>
        </div>
        <!-- Controls -->
        <a href="#bannerHS" role="button" data-slide="prev">
            <div class="prevButtonWrap btHomeSlider" aria-hidden="true"><span></span></div>
        </a>
        <a href="#bannerHS" role="button" data-slide="next">
            <div class="nextButtonWrap btHomeSlider" aria-hidden="true"><span></span></div>
        </a>

        <!-- Indicators -->
        <ol class="carousel-indicators hidden">
            <?php $i =0 ?>
            <?php foreach($collection as $bn) { ?>
                <li data-target="#bannerHS" data-slide-to="<?= $i ?>" class="<?= ($i == 0) ? 'active':'' ?>"></li>
                <?php $i++; ?>
            <?php } ?>
        </ol>
    </div>
    <div class="clearfix pad40"></div>

<?php } ?>

