<div class="row">
    <div class="col-xs-12 col-sm-3 hidden-xs">
        <?php
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $categoryFac = $objectManager->create('Magento\Catalog\Model\ResourceModel\Category\CollectionFactory');
        $categories = $categoryFac->create()
            ->addAttributeToSelect('*')
            ->addAttributeToFilter('parent_id', array('gt' => '1'))
            ->addAttributeToFilter('is_active', '1');

        $productFac = $objectManager->create('Magento\Catalog\Model\ResourceModel\Product\CollectionFactory');

        $product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');//get current product
        $pId = 0;
        $catArray = [];
        if (!is_null($product)) {
            $pId = intval($product->getId());
            $catArray = $product->getCategoryIds();
        }

        ?>


        <div class="menuLeftSidebar hidden-xs">
            <ul id="leftMenuUl">


                <?php foreach ($categories as $cate) { ?>
                    <li class="<?= (in_array($cate->getId(), $catArray)) ? 'open' : '' ?>">
                        <?php $products = $productFac->create()
                            ->addAttributeToSelect('*')
                            ->addCategoryFilter($cate)
                            ->addAttributeToFilter('status', '1')
                            ->load();
                        ?>
                        <?php if (count($products) > 0) { ?>
                            <span class="dropLeftMenu"></span>
                        <?php } ?>
                        <a href="<?= $cate->getUrl() ?>"><?= $cate->getName() ?></a>
                        <ul class="submenu">
                            <?php foreach ($products as $p) { ?>
                                <li class="<?= ($pId > 0 && $pId == intval($p->getId())) ? 'active' : '' ?>">
                                    <a href="<?= $p->getProductUrl() ?>"><?= $p->getName() ?></a>
                                </li>
                            <?php } ?>
                        </ul>
                    </li>
                <?php } ?>
            </ul>
        </div>
    </div>

    <div class="col-xs-12 col-sm-9">
        <?php
        $_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface');
        $currentStore = $storeManager->getStore();
        $baseUrl = $currentStore->getBaseUrl();
        $mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
        $linkUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_LINK);

        $banners = $_objectManager->get('Sahy\Banner\Block\Frontend\Banners');
        $collection1 = $banners->getAllBannerByType($banners::TYPE_HOME_BANNER);

        ?>
        <?php if (isset($collection1) && count($collection1) > 0) { ?>

            <?php $size = count($collection1);
            $collection1_tam = array();
            $count_collection = count($collection1);
            $k = $count_collection;
            while ($k > 0) {
                array_push($collection1_tam, $collection1[$k - 1]);
                $k--;
            }
            $collection1 = $collection1_tam;
            ?>
            <div class="clearfix"></div>
            <div id="bannerHS" class="carousel slide" data-ride="carousel" data-interval="3000">
                <!-- Wrapper for slides -->
                <div class="carousel-inner" role="listbox">
                    <?php $i = 1; ?>
                    <?php foreach ($collection1 as $bn) { ?>
                        <div class="item <?= ($i == 1) ? 'active' : '' ?>">
                            <img src="<?= $mediaUrl . $bn['image'] ?>"/>
                            <div class="innerHS">
                                <p class="titHS">
                                    <? //= ($bn['name'] == '.') ? "" :  $bn['name'] ?>
                                </p>
                                <p class="sumHS"><?= $bn['details'] ?></p>
                                <?php if ($bn['link'] != '') { ?>
                                    <a href="<?= $bn['link'] ?>" class="clickHereHS">CLICK HERE</a>
                                <?php } ?>
                            </div>
                        </div>
                        <?php $i++; ?>
                    <?php } ?>
                </div>
                <!-- Controls -->
                <a href="#bannerHS" role="button" data-slide="prev">
                    <div class="prevButtonWrap btHomeSlider" aria-hidden="true"><span></span></div>
                </a>
                <a href="#bannerHS" role="button" data-slide="next">
                    <div class="nextButtonWrap btHomeSlider" aria-hidden="true"><span></span></div>
                </a>

                <!-- Indicators -->
                <ol class="carousel-indicators hidden">
                    <?php $i = 0 ?>
                    <?php foreach ($collection1 as $bn) { ?>
                        <li data-target="#bannerHS" data-slide-to="<?= $i ?>" class="<?= ($i == 0) ? 'active' : '' ?>"></li>
                        <?php $i++; ?>
                    <?php } ?>
                </ol>
            </div>
            <div class="clearfix pad40"></div>

        <?php } ?>

        <div id="topContentHome">
            <div class="item odd">
                <div class="inner-wrap">
                    <div class="img">
                        <img src="/pub/media/images/home/icon-price.png"/>
                    </div>
                    <div class="tit">Lower Price</div>
                    <p class="sum">We 100% guarantee to give the lowest possible price for EVERY product. Not just the
                        banner like other places, but everything is guaranteed.</p>
                </div>
            </div>
            <div class="item even">
                <div class="inner-wrap">
                    <div class="img">
                        <img src="/pub/media/images/home/icon-quality.png"/>
                    </div>
                    <div class="tit">Premium Quality</div>
                    <p class="sum">Not like other printing companies, we use MADE IN USA ink and premium materials only.
                        You will be amazed with TradeBanner's final product.</p>
                </div>
            </div>
            <div class="item odd">
                <div class="inner-wrap">
                    <div class="img">
                        <img src="/pub/media/images/home/icon-broker.png"/>
                    </div>
                    <div class="tit">Broker Friendly</div>
                    <p class="sum">Our biggest vision is to support broker & wholesalers. When you succeed, we succeed.
                        Not only we will have best price and quality, but we give 100% support for any of your custom
                        job.<br>Just talk to us.</p>
                </div>
            </div>
            <div class="item even">
                <div class="inner-wrap">
                    <div class="img">
                        <img src="/pub/media/images/home/icon-order.png"/>
                    </div>
                    <div class="tit">Custom Orders</div>
                    <p class="sum">From 1 print of custom job or to 1,000 pieces of custom print, we will work with you.
                        Just talk to our staff for your unordinary custom job.<br>Just talk to us.</p>
                </div>
            </div>
        </div>

        <div class="clearfix pad50"></div>

        <?php
        $_objectManager = \Magento\Framework\App\ObjectManager::getInstance();

        $newsCat = $_objectManager->create('Magefan\Blog\Model\Category')->load('news');
        $proCat = $_objectManager->create('Magefan\Blog\Model\Category')->load('promotion');
        $news = $_objectManager->create('Magefan\Blog\Model\ResourceModel\Post\Collection')
            ->addActiveFilter()->addCategoryFilter($newsCat)->setOrder('creation_time', 'DESC')->setPageSize(5);
        $promotions = $_objectManager->create('Magefan\Blog\Model\ResourceModel\Post\Collection')
            ->addActiveFilter()->addCategoryFilter($proCat)->setOrder('creation_time', 'DESC')->setPageSize(3);
        //             $magentoDateObject = $_objectManager->create('Magento\Framework\Stdlib\DateTime\DateTime');
        // echo $magentoDate = $magentoDateObject->gmtDate();
        ?>

        <div class="row" id="promotionHome">
            <?php foreach ($promotions as $proItem) { ?>
                <div class="col-xs-12 col-sm-4">
                    <img src="<?= $proItem->getFeaturedImage() ?>"/>
                    <p class="tit"><?= $proItem->getTitle() ?></p>
                    <div class="sum"><?= $proItem->getContent() ?></div>
                    <a href="<?= $proItem->getPostUrl() ?>">
                        <div class="promoHomeBt">CLICK FOR DETAILS</div>
                    </a>
                </div>
            <?php } ?>
        </div>
        <div class="clearfix pad50"></div>

        <!--
        <div id="recent-product">
            <p class="recent-head">Recent News</p>
            <p class="recent-tit">Product & Gift</p>
            <div class="clearfix pad40"></div>
            <div class="recent-list">
                <php $i = 0;
                foreach ($news as $newItem) { ?>
                    <php if ($i == 0) { ?>
                        <div class="left-recent">
                            <div class="right-rc-item">
                                <div class="img-resp img100">
                                    <img src="<= $newItem->getFeaturedImage() ?>"/>
                                    <div class="main-rc-info">
                                        <span><= $newItem->getTitle() ?></span>
                                        <a href="<= $newItem->getPostUrl() ?>">Details</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <php } else { ?>

                        <php if ($i == 1) { ?>
                            <div class="right-recent">
                        <php } ?>

                        <div class="rc-item">
                            <div class="img-resp img100">
                                <img src="<= $newItem->getFeaturedImage() ?>"/>
                            </div>
                            <p class="tit"><= $newItem->getTitle() ?></p>
                            <div class="main-bt">
                                <a href="<= $newItem->getPostUrl() ?>"><span>Details</span></a>
                            </div>
                        </div>

                        <php if ($i == 4 || ($i + 1) == count($newItem)) { ?>
                            </div>
                        <php } ?>

                    <php } ?>
                    <php $i++;
                } ?>

            </div>
        </div>
        -->
    </div>
</div>

