<div class="">
    <!-- Slide home    <-->

</div>

<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-4">
            <?php
            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            // Get Menu
            $menu = $objectManager->get('\Magento\Theme\Block\Html\Topmenu');
            $_menu = $menu->getHtml('level-top', 'submenu');
            ?>

            <ul id="leftHomeMenu"><?= $_menu ?></ul>
        </div>

        <div class="col-xs-12 col-sm-8">
            <div class="row" id="topContentHome">
                <div class="col-xs-6 col-sm-6 col-md-3 odd">
                    <div class="img">
                        <img src="/pub/media/images/home/icon-price.png" />
                    </div>
                    <div class="tit">Lower Price</div>
                    <p class="sum">We 100% guarantee to give the lowest possible price for EVERY product. Not just the banner like other places, but everything is guaranteed.</p>
                </div>
                <div class="col-xs-6 col-sm-6 col-md-3 even">
                    <div class="img">
                        <img src="/pub/media/images/home/icon-quality.png" />
                    </div>
                    <div class="tit">Premium Quality</div>
                    <p class="sum">Not like other printing companies, we use MADE IN USA ink and premium materials only. You will be amazed with TradeBanner's final product.</p>
                </div>
                <div class="col-xs-6 col-sm-6 col-md-3 odd">
                    <div class="img">
                        <img src="/pub/media/images/home/icon-broker.png" />
                    </div>
                    <div class="tit">Broker Friendly</div>
                    <p class="sum">Our biggest vision is to support broken & wholesalers. When you succeed, we succeed. Not only we will have best price and quality, but we give 100% support for any of your custom job.<br>Just talk to us.</p>
                </div>
                <div class="col-xs-6 col-sm-6 col-md-3 even">
                    <div class="img">
                        <img src="/pub/media/images/home/icon-order.png" />
                    </div>
                    <div class="tit">Custom Orders</div>
                    <p class="sum">From 1 print of custom job or to 1,000 pieces of custom print, we will work with you. Just talk to our staff for your unordinary custom job.<br>Just talk to us.</p>
                </div>
            </div>

            <div class="clearfix pad40"></div>

            <div class="row" id="promotionHome">
                <div class="col-xs-4 col-sm-4">
                    <img src="/pub/media/images/product/promotion-1.png" />
                    <p class="tit">PROMOTION #1</p>
                    <p class="sum">13oz Vinyl Banner - 89c per square foot</p>
                    <a href="#" >
                        <div class="promoHomeBt">CLICK FOR DETAILS</div>
                    </a>
                </div>
                <div class="col-xs-4 col-sm-4">
                    <img src="/pub/media/images/product/promotion-2.png" />
                    <p class="tit">PROMOTION #2</p>
                    <p class="sum">NEXT DAY Turnaround on all orders under 100sq/ft*</p>
                    <a href="#" >
                        <div class="promoHomeBt">CLICK FOR DETAILS</div>
                    </a>
                </div>
                <div class="col-xs-4 col-sm-4">
                    <img src="/pub/media/images/product/promotion-3.png" />
                    <p class="tit">PROMOTION #3</p>
                    <p class="sum">FREE LOCAL DELIVERY TO LOS ANGELES* Not all Areas qualify</p>
                    <a href="#" >
                        <div class="promoHomeBt">CLICK FOR DETAILS</div>
                    </a>
                </div>
            </div>
        </div>
    </div>

</div>