<?php
//$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
//$menu = $objectManager->get('\Magento\Theme\Block\Html\Topmenu');
//$_menu = $menu->getHtml('level-top', 'submenu');
//$currentCategory = $objectManager->get('Magento\Framework\Registry')->registry('current_category');

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$categoryFac =  $objectManager->create('Magento\Catalog\Model\ResourceModel\Category\CollectionFactory');
$categories = $categoryFac->create()
    ->addAttributeToSelect('*')
    ->addAttributeToFilter('parent_id', array('gt' => '1'))
    ->addAttributeToFilter('is_active', '1');

$productFac = $objectManager->create('Magento\Catalog\Model\ResourceModel\Product\CollectionFactory');

$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');//get current product
$pId = 0; 
$catArray = [];
if (!is_null($product)) {
    $pId = intval($product->getId());
    $catArray = $product->getCategoryIds();
}

?>

<div class="menuLeftSidebar hidden-xs">
    <ul id="leftMenuUl">
        <div class="titleLeftSidebar">CATEGORIES</div>

        <?php foreach($categories as $cate ) { ?>  
        <li class="<?= ( in_array($cate->getId(), $catArray) )  ? 'open' : '' ?>">
            <?php $products = $productFac->create()
                ->addAttributeToSelect('*')
                ->addCategoryFilter($cate)
                ->addAttributeToFilter('status', '1')
                ->load();
            ?>
            <?php if (count($products) > 0) { ?>
                <span class="dropLeftMenu"></span>
            <?php } ?>
            <a href="<?= $cate->getUrl() ?>"><?= $cate->getName() ?></a>
            <ul class="submenu">
                <?php foreach($products as $p) { ?>
                    <li class="<?= ($pId > 0 && $pId == intval($p->getId())) ? 'active': '' ?>">
                        <a href="<?= $p->getProductUrl() ?>"><?= $p->getName() ?></a>
                    </li>
                <?php } ?>
            </ul>
        </li>
        <?php } ?>
    </ul>
</div>

<script type="text/javascript">
    require(['jquery', 'jquery/ui'], function ($) {
        $(document).ready(function () {
//            $('#leftMenuUl li.parent').each(function () {
//                var data = $(this).hasClass("has-active") ? "-" : "+";
//                var curWidth = $(window).width();
//                if (curWidth <= 767) data = "+";
//                $(this).prepend('<span class="dropLeftMenu">' + data + '</span>');
//            });

            // $('#leftMenuUl .dropLeftMenu').click(function () {
            //     var selectCt = $(this).parent().find('ul.submenu').first();
            //     if (selectCt.is(':visible')) {
            //         $(this).text("+");
            //         selectCt.slideUp('normal');
            //     } else {
            //         $(this).text("-");
            //         selectCt.slideDown('normal');
            //     }
            // });
        })
    });
</script>

