<?php
/**
 * Top menu for store
 * @see \Magento\Theme\Block\Html\Topmenu
 */
?>

<?php
//$columnsLimit = $block->getColumnsLimit() ?: 0;
//$_menu = $block->getHtml('level-top', 'submenu', $columnsLimit);
?>

<nav role="navigation" id="topMenuNav" data-xs="0">
    <ul>
        <li id="allProductLi">
            <a href="javascript:void(0)" id="clickAllProduct">ALL PRODUCT <span class="visible-xs" id="plusDefault">+</span></a>
            <ul id="topMegaMenu">
                <?php
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $categoryFac = $objectManager->create('Magento\Catalog\Model\ResourceModel\Category\CollectionFactory');
                $categories = $categoryFac->create()
                    ->addAttributeToSelect('*')
                    ->addAttributeToFilter('parent_id', array('gt' => '1'))
                    ->addAttributeToFilter('is_active', '1');

                $productFac = $objectManager->create('Magento\Catalog\Model\ResourceModel\Product\CollectionFactory');
                ?>
                <?php foreach ($categories as $cate) { ?>
                <li class="item">
                    <a href="javascript:void(0)" class="clickCateTopMenu"><?= $cate->getName() ?></a>
                    <?php
                    $products = $productFac->create()
                        ->addAttributeToSelect('*')
                        ->addCategoryFilter($cate)
                        ->addAttributeToFilter('status', '1')
                        ->load();
                    ?>
                    <ul style="display: none">
                        <?php foreach ($products as $p) { ?>
                            <li><a href="<?= $p->getProductUrl() ?>"><?= $p->getName() ?></a></li>
                        <?php } ?>
                    </ul>
                    <?php } ?>
                </li>
            </ul>
        </li>
        <li><a href="/custom-estimate">CUSTOM ESTIMATE</a></li>
        <li><a href="/promotion-news">PROMOTION & NEWS</a></li>
        <li><a href="/contact">CONTACT US</a></li>
    </ul>
</nav>

<script type="text/javascript">
    require(['jquery', 'jquery/ui'], function ($) {
        $(document).ready(function ($) {
            // Init
            var menu = $('#topMegaMenu');
            var menuWrap = $('#topMenuNav');
            var xs = ($(window).width() > 767) ? 0 : 1;
            menu.attr('data-xs', xs);

            // Click all product
            $('#clickAllProduct').click(function () {
                if ($(window).width() < 768) {
                    if (menu.is(':visible')) {
                        $(this).find('span').first().text("+");
                        menu.slideUp('normal');
                    } else {
                        $(this).find('span').first().text("-");
                        menu.slideDown('normal');
                    }
                }
            });

            // Drop-down sub-menu on top menu
            $('.clickCateTopMenu').click(function () {
                var ul = $(this).find('+ ul');
                if(ul.is(':visible')) {
                    ul.slideUp('normal');
                } else {
                    ul.slideDown('normal');
                }
            });

            // Click Search
            $('#clickTopSearchIcon').click(function(){
                if ($(window).width() < 1024) {
                    $('#topSearchWrap > .block-content').toggle();
                }
            });

            // Click menu on xs
            $('#menuIcon').click(function () {
                $('#topMenuNav').toggle();
            });

            // Handle menu when has resize event
            function resizeTopMenu() {
                var w = $(window).width();
                var curXs = parseInt(menuWrap.attr('data-xs'));
                if ( (w > 767 && curXs == 1) || (w < 768 && curXs == 0) ) {
                    menuWrap.attr('style', '');
                    menu.attr('style', '');
                    $('#plusDefault').text('+');
                    xs = ($(window).width() > 767) ? 0 : 1;
                    menuWrap.attr('data-xs', xs);
                }

                // Search event
                if (w > 1024) {
                    $('#topSearchWrap > .block-content').attr('style','');
                }
            }

            // Listen resize window event
            $(window).resize(function () {
                resizeTopMenu();
            });
            resizeTopMenu();
        });
    });
</script>

<div class="clearfix pad20 visible-xs"></div>
<div class="clearfix"></div>