<?php
/**
 * Top menu for store
 *
 * @see \Magento\Theme\Block\Html\Topmenu
 */
?>

<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>

<nav role="navigation" id="topMenuNav">
    <ul>
        <li>
            <a href="javascript:void(0)">ALL PRODUCT</a>
            <ul id="topMegaMenu">
                <?= $_menu; ?>
            </ul>
        </li>
        <li><a href="javascript:void(0)">CUSTOM ESTIMATE</a></li>
        <li><a href="/promotion-news">PROMOTION & NEWS</a></li>
        <li><a href="/contact">CONTACT US</a></li>
    </ul>
</nav>
