<div id="topRightInfo">
    <div class="tri-item">
        <span class="header-cross">|</span>
        <span><a href="/faq">Frequently Asked Questions</a></span>
    </div>
    <div class="tri-item">
        <img src="/pub/media/images/icon/icon-header-phone.png" />
        <span>1-888-900-6539</span>
    </div>
    <div class="tri-item">
        <img src="/pub/media/images/icon/icon-header-mail.png" />
        <span>info@tradebanner.com</span>
    </div>
</div>