<div id="topLeftInfo" class="hidden-xs">
    <span><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('memory_alld_day')->toHtml();?></span>
</div>
<div id="topRightInfo" class="hidden-xs">
    <div class="tri-item">
        <img src="/pub/media/images/icon/icon-header-phone.png" />
        <span>1-888-900-6539</span>
    </div>
    <div class="tri-item">
        <img src="/pub/media/images/icon/icon-header-mail.png" />
        <span>info@tradebanner.com</span>
    </div>
</div>