<?php
/**
 * Create CMS page
 * content: <div>{{block class="Magento\Framework\View\Element\Template" name="upload_page" template="Magento_Theme::html/uploadpage.phtml"}}</div>
 * url key: upload-file-transfer
 */
?>

<div id="uploadCMSpage">
    <p class="tit">Please make sure to write your correct order number to TRANSFER NAME</p>

    <p>ORDER CANCELLATION If client would like to cancel a placed order, they must notify our CSR immediately before
        your order is processed through the system. No order can be cancelled once the status has been changed to
        “Printing.” You may cancel for a Full Refund before the artwork is uploaded. No refund will be issued to the
        services we have provided you such as Design services, Marketing information, Business consulting, etc. We do
        not issue refunds once an order has been Printed or any process thereafter.<br>
    <b>By uploading your file you acknowledge the fact that you are aware of the cancellation policy.</b></p>

    <div class="clearfix pad20"></div>

    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-7 col-lg-8">

            <p><b>Please make sure to have your order number at Transfer Name.</b></p>

            <p>You can find your order number in your order email or at <a href="/customer/account">MY ACCOUNT</a>.</p>

            <p>Please also write your company name under “Your Name”</p>

            <p>Thank you</p>
            <div class="clearfix pad20"></div>
        </div>

        <div class="col-xs-12 col-sm-6 col-md-5 col-lg-4">
            <div id="tbfjs" style="margin: 0 auto; display: inline-block; width: 354px;"></div>
            <script type="text/javascript">
                (function (w, d) {
                    var p = d.getElementById('tbfjs'), f = '';
                    f += '<iframe scrolling="no" frameborder="0" style="border-style:none; border-width:initial; border-color:initial; border-image:initial; overflow-x:hidden; overflow-y:hidden; height:420px; width:355px;" allowtransparency="true"';
                    f += ' src="https://www.transferbigfiles.com/upload/privatedropbox/4213c411-5e70-40ad-91eb-cf87e4d39f0b"></iframe>';
                    p.innerHTML = f;
                }(window, document));
            </script>
        </div>
    </div>

</div>



