<div class="body"
     style="position: relative; width: 21cm; height: 29.7cm; margin: 0 auto; color: #555555; background: #FFFFFF; font-size: 14px;">
    <div class="main">
        <table class="email-items"
               style="width: 100%; font-family: 'Frank Ruhl Libre', sans-serif; border-collapse: collapse; border-spacing: 0; margin-bottom: 20px;"
               border="0">
            <thead style="display: none">
            <tr>
                <th class="no"></th>
                <th class="desc"></th>
            </tr>
            </thead>
            <tbody>
            {{var ea_barcode_c39_invoice.increment_id}}
            <div class="pdfTable">
                ##productlist_start##
                <tr>
                    <td>Name</td>
                    <td>{{var item.name}}</td>
                </tr>
                <tr>
                    <td>Sku</td>
                    <td>{{var item.name}}</td>
                </tr>

                {{var item.item_options}}
                <tr>
                    <td>Qty</td>
                    <td>{{var ea_item.qty}}</td>
                </tr>
                <tr>
                    <td>Price</td>
                    <td>{{var ea_item.price}}/{{var ea_item.row_total}}</td>
                </tr>
                ##productlist_end##
            </div>
            </tbody>

            <tfoot>
                <tr>
                    <td>SUBTOTAL</td>
                    <td>{{var ea_invoice.subtotal}}</td>
                </tr>
                <tr>
                    <td>SHIPPING TAX</td>
                    <td>{{var ea_invoice.base_shipping_amount}}{{depend invoice_if.base_shipping_amount}}</td>
                </tr>
                <tr>
                    <td>DEPEND SHIPPING TAX</td>
                    <td>{{var invoice.base_shipping_amount}}{{/depend}}</td>
                </tr>
                <tr>
                    <td class="grandtotal"
                        style="color: #f26522; font-weight: bold; font-size: 1.6em; border-top: 1px solid #f26522;">
                        GRAND TOTAL
                    </td>
                    <td class="grandtotal"
                        style="color: #f26522; font-weight: bold; font-size: 1.6em; border-top: 1px solid #f26522;">
                        {{var ea_invoice.grand_total}}
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
</div>