<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
/** @var $block \Magento\ConfigurableProduct\Block\Product\View\Type\Configurable*/
$_product    = $block->getProduct();
$_attributes = $block->decorateArray($block->getAllowAttributes());
?>
<?php if ($_product->isSaleable() && count($_attributes)):?>
    <script type="text/x-magento-init">
        {
            ".swatch-opt": {
                "rewardpointsColorswatch": {
                    "spConfig": <?php /* @escapeNotVerified */ echo $block->getJsonConfig() ?>
                }
            }
        }
    </script>
<?php endif;?>
