<?php if ($popup = $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('popup')->toHtml()) : ?>
<div id="popup_modal" class="modal">
	<div class="modal-window">
		<div class="modal-header">
			<div class="modal-close">X</div>
		</div>
		<div class="modal-body">
            <?php echo $popup ?>
		</div>
	</div>
</div>
<script>
    require(['jquery'],function(jQuery) {
        jQuery(window).load(function() {
            if (getCookie('popup') != 'dontshow') {
                setTimeout(function(){
                    jQuery('#popup_modal').show();
	                jQuery('body').addClass('modal-open');
                }, 500);
            }

            jQuery('#popup_modal .modal-close').click(function() {
                closePopup();
            });
        });

        function getCookie(cname) {
            var name = cname + '=';
            var ca = document.cookie.split(';');
            for (var i = 0; i < ca.length; i++) {
                var c = ca[i];
                while (c.charAt(0) == ' ') c = c.substring(1);
                if (c.indexOf(name) == 0) return c.substring(name.length,c.length);
            }
            return '';
        }

        function closePopup(){
            var d = new Date();
            d.setTime(d.getTime() + (24*60*60*1000));
            document.cookie = 'popup=dontshow; expires=' + d.toUTCString();
            jQuery('#popup_modal').hide();
            jQuery('body').removeClass('modal-open');
        }
    });
</script>
<style>
	body.modal-open {
		overflow: hidden;
	}

	#popup_modal {
		position: fixed;
		top: 0;
		left: 0;
		width: 100%;
		height: 100%;
		background: rgba(0, 0, 0, 0.5);
		z-index: 10000000000;
		display: none;
	}
	#popup_modal .modal-window {
		position: absolute;
		top: 50%;
		left: 50%;
		transform: translate(-50%, -50%);
		padding: 50px;
		background: #ffffff;
		border: 1px solid #d8d8d8;
		text-align: center;
		line-height: 2;
		box-shadow: 10px 10px 20px 5px;
	}
	#popup_modal .modal-window .modal-header .modal-close {
		position: absolute;
		top: 15px;
		right: 15px;
		height: 17px;
		width: 17px;
		cursor: pointer;
		z-index: 10;
	}
</style>
<?php endif; ?>