<?php
/** @var $block \Magento\Customer\Block\Account\AuthorizationLink */

$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>

<li class="authorization-link" data-label="<?= $block->escapeHtml(__('or')); ?>">
    <a <?= $block->getLinkAttributes(); ?><?= $dataPostParam; ?>>
        <?= $block->escapeHtml($block->getLabel()); ?>
    </a>
</li>

<li><a href="javascript:void(0)">|</a></li>