<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="actions">
    <?php  $_order = $block->getOrder() ?>
    <?php if ($this->helper('Magento\Sales\Helper\Reorder')->canReorder($_order->getEntityId())) : ?>
        <a href="#" data-post='<?php /* @escapeNotVerified */ echo
        $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
            ->getPostData($block->getReorderUrl($_order))
        ?>' class="action order">
            <span><?php /* @escapeNotVerified */ echo __('Reorder') ?></span>
        </a>
    <?php endif ?>

    <?php if($block->addPDFLink($_order)):?>
        <a href="<?php /* @escapeNotVerified */ echo  $block->getPrintPDFUrl($_order) ?>"
           onclick="this.target='_blank'"
           class="action print">
            <span> <?php /* @escapeNotVerified */ echo __('Print PDF order') ?>&nbsp; </span>
        </a>
    <?php endif?>
    <?php echo $block->getChildHtml(); ?>
</div>
