<?php
/**
 * Copyright © 2016 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */

use Magento\Framework\App\Action\Action;

?>
<?php
/**
 * Blog post list template
 *
 * @var $block \Magefan\Blog\Block\Post\PostList
 */
?>
<?php
$_postCollection = $block->getPostCollection();
?>
<?php if (!$_postCollection->count()): ?>
    <div class="message info empty">
        <div><?php echo __('We can\'t find posts matching the selection.') ?></div>
    </div>
<?php else: ?>
    <?php echo $block->getAdditionalHtml() ?>
    <div class="post-list-wrapper">
        <div class="flex-row row">
            <?php foreach ($_postCollection as $_post) { ?>
                <div class="col-xs-6 col-sm-6 col-md-4 recent-news-item">
                    <?php echo $block->getPostHtml($_post) ?>
                </div>
            <?php } ?>
        </div>
    </div>

    <?php echo $block->getToolbarHtml() ?>

<?php endif; ?>
