<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>

<style type="text/css">
    .selectFileGroup select {
        margin: 0 12px 12px 0;
        width: calc(50% - 15px);
        height: auto;
        float: left;
        clear: both;
    }

    .selectFileGroup input {
        margin: 0 0 12px;
        width: 48%;
        float: left;
    }

    #s3ActionBar > button {
        border: 0;
        border-radius: 0;
        color: #fff;
        background: #1ca1ac;
    }

    #s3Result p {
        margin: 0 0 15px;
        color: #0000ff;
    }

    #s3Result span {
        font-size: 16px;
        font-weight: bold;
        padding: 5px 10px;
        border-radius: 4px;
    }

    .success {
        color: #fff;
        background: #00909e;
        border: 1px solid #00909e;

    }

    .error {
        color: #a94442;
        background: #f2dede;
        border: 1px solid #ebccd1;
    }

    .warning {
        color: #8a6d3b;
        background: #fcf8e3;
        border: 1px solid #faebcc;
    }

    button#s3Submit {
        background: #f05624;
    }

    .progress {
        height: 30px;
        line-height: 30px;
        overflow: hidden;
        background: #bbb;
    }

    .progress .bar {
        float: left;
        width: 0;
        height: 100%;
        font-size: 12px;
        background: #1da1ad;
        text-align: right;
        font-weight: bold;
        color: #fff;
        padding-right: 10px;
        -moz-transition: width 0.6s ease 0s;
        -webkit-transition: width 0.6s ease 0s;
        -o-transition: width 0.6s ease 0s;
        transition: width 0.6s ease 0s;
    }

    @media only screen and (max-width: 680px) {
        .selectFileGroup select, .selectFileGroup input {
            width: 100%;
        }
    }
</style>

<?php
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
?>

<div class="checkout-success">
    <?php $orderId = $block->getOrderId(); ?>
    <?php if ($orderId) : ?>
        <?php $oIdHtml = $block->escapeHtml($orderId); ?>
        <?php if ($block->getCanViewOrder()) : ?>
        <p>Your order number is: <a href="<?= $block->escapeHtml($block->getViewOrderUrl()) ?>" target="_blank" class="order-number"><strong><?= $oIdHtml ?></strong></a></p>
    <?php else : ?>
        <p>Your order # is: <span><?= $oIdHtml ?></span></p>
    <?php endif; ?>

        <div class="clearfix pad20"></div>
    <?php // Get Order items by order id
    $order = $_objectManager->create('Magento\Sales\Model\Order')->loadByIncrementId($orderId);
    $orders = $order->getAllItems();
    $items = [];
    foreach ($orders as $item) {
        array_push($items, $item->getName());
    }
    $items = array_unique($items);
    $total = count($items);
    ?>
        <form action="" enctype="multipart/form-data" method="post" id="s3Form">
            <input type="hidden" name="order" value="<?= $orderId ?>">

            <div class="selectFileGroup">
                <select name="upload[0][]" multiple>
                    <?php
                    $i = 0;
                    foreach ($items as $key => $name) {
                        $selected = ($i == 0) ? 'selected' : '';
                        echo '<option value="' . $name . '" '. $selected . '>' . $name . '</option>';
                        $i++;
                    } ?>
                </select>
                <input type="file" name="file[0]" />
            </div>

            <div id="bodyS3Form" class="selectFileGroup">
                <?php
                for ($j = 1; $j <= $total - 1; $j++) { ?>
                    <select name="upload[<?= $j ?>][]" multiple>
                        <?php
                        $i = 0;
                        foreach ($items as $key => $name) {
                            $selected = ($i == $j) ? 'selected' : '';
                            echo '<option value="' . $name . '" '. $selected . '>' . $name . '</option>';
                            $i++;
                        } ?>
                    </select>
                    <input type="file" name="file[<?= $j ?>]" />
                <?php } ?>
            </div>

            <div class="clearfix pad10"></div>
            <p>Only jpeg, jpg, png, psd, tiff, pdf, aiff files are allowed.<br>Image size should be less than 1GB.</p>
            <div class="clearfix pad20"></div>

            <div id="s3ActionBar">
                <button type="button" name="s3AddMore" id="s3AddMore">Add more file</button>
                <button type="button" name="s3Reset" id="s3Reset">Reset</button>
                <button type="button" name="submit" id="s3Submit">Submit</button>
            </div>

        </form>


        <div class="clearfix pad20"></div>

        <div style="text-align: center; display: none" id="fedexLoading">
            <!-- <img "/pub/media/images/icon/loading.gif"/> -->
            <div class="progress">
                <div style="width: 0" class="bar" id="progressArchiveFile"></div>
            </div>
            <div class="clearfix pad20"></div>
        </div>
        <div id="s3Result"></div>

        <script type="text/javascript">
            require(['jquery', 'jquery/validate', 'jquery/ui', 'mage/mage'], function ($) {
                $(document).ready(function ($) {
                    var indexer = <?= $total - 1 ?>; // the number of select tag
                    var name = [  <?php foreach ($items as $i => $name) {
                        echo '"' . $name . '"';
                        echo (($i + 1) == count($items)) ? '' : ',';
                    } ?>  ];

                    $('#s3Submit').click(function () {
                        $('#s3Result').html('');
                        $('#fedexLoading').css('display', 'block');
                        $('#s3Submit').prop('disabled', true);
                        $('#s3AddMore').prop('disabled', true);
                        $('#s3Reset').prop('disabled', true);

                        var form = $('#s3Form')[0];
                        var data = new FormData(form);

                        $.ajax({
                            url: '/upload.php',
                            type: 'post',
                            data: data,
                            cache: false,
                            contentType: false,
                            processData: false,                     
                            xhr: function() {
                                var myXhr = $.ajaxSettings.xhr();                               
                                myXhr.upload.addEventListener('progress', function(evt){
                                    if (evt.lengthComputable) {
                                        var percentComplete = evt.loaded / evt.total * 100;
                                        var percentFloat = Math.round(percentComplete * 100) / 100;                          
                                        var percentVal = (percentFloat >= 100) ? '99.99%' : percentFloat + '%'; 
                                        $('#progressArchiveFile').text(percentVal).css("width",percentVal);                                     
                                    }
                                }, false);
                               
                                return myXhr;
                            },
                            success: function (rs) {
                                $('#progressArchiveFile').text("100%").css("width","100%");
                                setTimeout(function(){ 
                                    $('#fedexLoading').css('display', 'none');
                                    $('#s3Submit').prop('disabled', false);
                                    $('#s3AddMore').prop('disabled', false);
                                    $('#s3Reset').prop('disabled', false);
                                    $('#s3Result').html(rs);
                                    $('#progressArchiveFile').text("0%").css("width","0");
                                    form.reset();
                                }, 1000);
                                
                            }
                        });
                    });


                    function addMoreFile() {
                        indexer++;
                        var html = '';

                        html += '<select name="upload[' + indexer + '][]" multiple>';
                        var dem = 0;
                        var selected = '';
                        name.forEach(function (s) {
                            selected = (dem == 0) ? 'selected' : '';
                            html += '<option value="' + s + '" ' + selected + '>' + s + '</option>';
                            dem++;
                        });
                        html += '</select><input type="file" name="file[' + indexer + ']" />';

                        return html;
                    }

                    $('#s3Reset').click(function () {
                        indexer = 0;
                        $('#bodyS3Form').html('');
                        $('#s3Form')[0].reset();
                    });

                    $('#s3AddMore').click(function () {
                        $('#bodyS3Form').append(addMoreFile());
                    });

                });
            });
        </script>

        <div class="clearfix pad20"></div>
        <p><?= 'We\'ll email you an order confirmation with details and tracking info.' ?></p>
    <?php endif; ?>

    <?php echo $block->getAdditionalInfoHtml() ?>

    <div class="clearfix pad20"></div>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue"
               href="<?= $block->getUrl() ?>"><span><?= 'Continue Shopping' ?></span></a>
        </div>
    </div>
</div>
