<?php
/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper('Magento\Msrp\Helper\Data');
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
?>
<tbody class="cart item">
<tr class="item-info">
    <td data-th="<?= $block->escapeHtml(__('Item')); ?>" class="col item itemCartCol">

        <a href="<?= $block->getProductUrl() ?>" tabindex="-1" class="product-item-photo">
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml(); ?>
        </a>

        <div class="product-item-details">
            <?php if ($block->hasProductUrl()): ?>
                <a class="titCartCol" href="<?= $block->getProductUrl() ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
            <?php else: ?>
                <p class="titCartCol"><?= $block->escapeHtml($block->getProductName()) ?></p>
            <?php endif; ?>

            <?php if ($_options = $block->getOptionList()): ?>
                <div class="clearfix pad10"></div>
                <div class="optionDetailBlock">
                    <a href="javascript:void(0)" class="showDetailCartCol">See details</a>
                    <dl class="item-options" style="display: none">
                        <?php foreach ($_options as $_option) : ?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                            <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                            <dd>
                                <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                    <?= $_formatedOptionValue['full_view'] ?>
                                <?php else: ?>
                                    <?= $_formatedOptionValue['value'] ?>
                                <?php endif; ?>
                            </dd>
                        <?php endforeach; ?>
                    </dl>
                </div>
            <?php endif; ?>

            <?php if ($messages = $block->getMessages()): ?>
                <?php foreach ($messages as $message): ?>
                    <div class="cart item message <?= $message['type'] ?>"><div><?= $block->escapeHtml($message['text']) ?></div></div>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock): ?>
                <?= $addInfoBlock->setItem($_item)->toHtml() ?>
            <?php endif;?>
        </div>

        <div class="clearfix"></div>
        <div class="actionsBar"><?= $block->getActions($_item) ?></div>
    </td>

    <?php if ($canApplyMsrp): ?>
        <td class="col msrp align-center" data-th="<?= $block->escapeHtml(__('Price')); ?>">
                <span class="pricing msrp">
                    <span class="msrp notice"><?= __('See price before order confirmation.'); ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map" id="<?=($helpLinkId); ?>" data-mage-init='{"addToCart":{"helpLinkId": "#<?= $helpLinkId;?>","productName": "<?= $product->getName(); ?>","showAddToCart": false}}'>
                        <span><?= __("What's this?"); ?></span>
                    </a>
                </span>
        </td>
    <?php else: ?>
        <td class="col price align-center" data-th="<?= $block->escapeHtml(__('Price')); ?>">
            <?= $block->getUnitPriceHtml($_item); ?>
        </td>
    <?php endif; ?>
    <td class="col qty" data-th="<?= $block->escapeHtml(__('Qty')); ?>">
        <div class="field qty">
            <div class="control qty">
                <input id="cart-<?= $_item->getId() ?>-qty"
                       name="cart[<?= $_item->getId() ?>][qty]"
                       data-cart-item-id="<?= $_item->getSku() ?>"
                       value="<?= $block->getQty() ?>"
                       type="number"
                       size="4"
                       title="<?= $block->escapeHtml(__('Qty')); ?>"
                       class="input-text qty align-center"
                       maxlength="12"
                       data-validate="{required:true,'validate-greater-than-zero':true}"
                       data-role="cart-item-qty"/>
            </div>
        </div>
    </td>

    <td class="col subtotal align-center" data-th="<?= $block->escapeHtml(__('Subtotal'));?>">
        <?php if ($canApplyMsrp): ?>
            <span class="cart msrp subtotal">--</span>
        <?php else: ?>
            <?= $block->getRowTotalHtml($_item); ?>
        <?php endif; ?>
    </td>
</tr>

</tbody>
