<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post list item template
 *
 * @var $block \Magefan\Blog\Block\Post\AbstractPost
 */
?>
<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
?>
<div class="inner post-holder-<?= $_post->getId() ?>">
    <div class="post-content">
        <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
        <div class="post-ftimg-hld">
            <a href="<?= $_postUrl ?>" title="<?= $_postName ?>">
                <img src="<?= $featuredImage ?>" alt="<?= $_postName ?>" />
            </a>
            <?= $this->getInfoHtml() ?>
        </div>
        <?php } ?>
        <div class="post-news-content">
            <div class="post-title-holder clearfix">
                <h2 class="post-title">
                    <a class="post-item-link"
                       href="<?= $_postUrl ?>">
                        <?= $_postName; ?>
                    </a>
                </h2>
            </div>

            <div class="post-text-hld clearfix">
                <?php $shortNewsContent = implode(' ', array_slice(explode(' ', $block->getShorContent()), 0, 30)); ?>
                <?php if(str_word_count($block->getShorContent()) > 30) $shortNewsContent = $shortNewsContent . ' ...'; ?>
                <?= $shortNewsContent; ?>
            </div>

            <a class="post-read-more" href="<?= $_postUrl ?>" title="<?= $_postName ?>">
               <?= __('Details') ?>
            </a>
        </div>
    </div> 
</div>